### ISSUE TITLE
Use GUIDs for ID attributes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#1006]
```
Any way to use GUIDs in Task IDs, and other ID attributes in the gan file?
```

Original issue reported on code.google.com by `carlom.i...@gmail.com` on 27 Oct 2014 at 9:41

**Comment by YKSoftware** [comment]
In fact, when sharing .gan files with git, you run into ID conflicts when others add tasks to each other. It would be great to change the ID to her GUID to solve this problem.

**Comment by dbarashev** [comment]
If you version-control your project files using Git, you're going to have a lot of other conflicts regardless of using GUIDs.
