### ISSUE TITLE
Task renumbering feature

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#1075]
```
The task number increases always, so after much editing I have 95% of my task 
numbers at 1000 or above, even though there are only ~50 tasks.

It's hard to remember the task ids when the numbers are large.

A button (or optionally automatic on load/save) that would re-map all the IDs 
from 1 would solve this.

Great project btw! I've just started using it.
```

Original issue reported on code.google.com by `marcus.l...@bitaddict.se` on 5 Feb 2015 at 2:30

**Comment by jayconroy** [comment]
This bug/feature is still open, is there motivation to implement this? I think renumbering task IDs would be very helpful.

**Comment by dbarashev** [comment]
In my opinion, this "feature", as it is described makes no sense. There are outline numbers for referencing in the meetings. We can add row numbers if outline numbers are too annoying to spell. Search by ID (and in the predecessors table as well) will be added in the next major update We can make IDs not changing frequently. But as I said above, renumbering is a weird hack which "fixes" a bad designed functionality. We don't need weird hacks, we need to fix the design.
