### ISSUE TITLE
Mac OS Retina display compatibility

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#1108]
```
Would it be possible to make GanttProject compatible with retina display?

I love GanttProject, but would be hugely improved for mac users with a retina 
display if it was compatible :) 
```

Original issue reported on code.google.com by `liberty....@googlemail.com` on 24 Mar 2015 at 9:04

**Comment by ryanthara** [comment]
There will be a two step solution. See the screenshot below.

<img width="693" alt="ganttproject_on_retina" src="https://cloud.githubusercontent.com/assets/7117072/16712499/7ff9cd4c-4689-11e6-816b-d02258260003.png">

First one is, add the key `<key>NSHighResolutionCapable</key>
<true/>` to the Info.plist file. All the font rendering and the look and feel are "retina like".

Second one is, prepare high resolution images and add support for this. Just take the idea from [Bulenkov](http://bulenkov.com/2013/06/23/retina-support-in-oracle-jdk-1-7/) and the [icon loader library](http://bulenkov.com/iconloader/), which is still working in RyCON to do this job.

Then, ganttproject is retina ready.

**Comment by none86** [comment]
Hello community,

I have a similar problem, see picture.
Resolution (native: 3240x2160, scaling at 200% / MS Surface Book 2)

The readability of the input fields is hardly given, also the date/calendar week overview.

Unfortunately, the changes in the settings did not give usable results.

Is something in the works?

Thanks

![image](https://user-images.githubusercontent.com/38491902/38923548-1e78611c-42fb-11e8-975c-797c15d76f59.png)

**Comment by dbarashev** [comment]
Did you try changing DPI setting as [described here](http://ganttproject.blogspot.com/2017/03/ganttproject-284-scalable-ui-on-high.html) ?

**Comment by none86** [comment]
The problem was buried somewhere else
I accidentally caught version 2.7, which doesn't have the scaling yet.

now it looks good, thanks you anyway!
