### ISSUE TITLE
When removing predecessors tasks to not move back to next first avalible date

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#1124]
```
What steps will reproduce the problem?
1. Create 2 Task
2. Make Task 2 predecessor to Task 1
3. Save
4. Delete Task 1 as a predecessor to Task 2, 

What is the expected output? What do you see instead?
the start date of Task 2 remains fixed where it was before with the predecessor 
attached.

I would expect the task to revert to the earliest available date based on other 
predecessors (or today in the case of no predecessors)

What version of the product are you using? On what operating system?
2.7 on Windows 7 64-bit

Please provide any additional information below.
Thanks!
```

Original issue reported on code.google.com by `ajbela...@gmail.com` on 13 May 2015 at 10:07

**Comment by euanbrown** [comment]
Can this issue be reopened as I see the same issue as reported.

When a sub task is modified resulting in the super set task duration shortening other tasked linked to it do not snap back in time to the new task start date.
It is best explained in the attached image.
 
Version 2.7.1 build 1924.
Java Version 8 update 60
Windows 7 Pro SP1

![predecessor](https://cloud.githubusercontent.com/assets/14225873/9803198/99424212-5863-11e5-8cce-9fa67f694eec.jpg)

**Comment by dbarashev** [comment]
@euanbrown I created a new issue #1173 Thanks for reporting!
