### ISSUE TITLE
I am trying to start a new chart - when I get to task properties I can input a start date but not an end date.  

### ISSUE THREAD

**Issue by Troutie** [bardsoftware/ganttproject#1153]
the box does not light up - remains in background.  I have double clicked, gone to edit etc but cannot get task to light up the end date

**Comment by dbarashev** [comment]
One out of three fields which control task dates (start date, end date, duration) must be calculated, and thus disabled in the interface. Which one is calculated is shown in the dropdown "Scheduling options" just above the "Begin date" field. By default "end date is calculated" is chosen. Change it the way you like.

**Comment by Troutie** [comment]
Thanks
