### ISSUE TITLE
ganttproject save in server

### ISSUE THREAD

**Issue by halim90** [bardsoftware/ganttproject#1155]
Hello

we have installed gantproject 2.7, we need tu use option save as server, but we have thise error:

net.sourceforge.ganttproject.document.webdav.WebDavResource$WebDavException: Conflict when accessing webcom Conflict when accessing webcom

best regards

**Comment by dbarashev** [comment]
Any additional details? What is webcom? What exactly you did and how server configuration looked? What is in the log?

**Comment by dbarashev** [comment]
No response from the issue submitter, closing.
