### ISSUE TITLE
keyboard in Hebrew

### ISSUE THREAD

**Issue by DinaJane** [bardsoftware/ganttproject#1158]
Hi

I see that there are already some discussions concerning Hebrew.
I however am not able to type in Hebrew when I convert the keyboard.

The program just types squares.

**Comment by dbarashev** [comment]
Please choose appropriate font with Hebrew glyphs in the Application UI settings.

See also http://forum.ganttproject.biz/view/20150514112816_-4b9mzmf95256sv91k1d7vod5q

**Comment by DinaJane** [comment]
Thank you
I tried that already – but for some reason if I choose Hebrew the whole thing turns into squares.

I try changing the language on my keyboard (because I have no issue with the English layout) but that doesn't work either.



Best Regards,

Dina Slutzkin
Marketing Manager
Carmor Integrated Vehicle Solutions Ltd.
Tel: +972-4-6410-650
Fax: +972-4-6418-555
Mobile: +972-547725364
dina@carmor.com
www.carmor.com<http://www.carmor.com/>
[carmor - sig]
[cid:image002.jpg@01D0C88C.45A87930]<https://www.linkedin.com/company/carmor-by-hatehof---integrated-vehicle-solutions?trk=biz-companies-cym>[cid:image002.png@01D03FB2.8520C3F0]<https://www.facebook.com/Hatehof?ref=hl>

**Comment by dbarashev** [comment]
Please choose **appropriate font**, not the language. You may want to change the interface language too, but if your chosen **font** has no Hebrew glyphs then it will show Hebrew symbols as squares

**Comment by DinaJane** [comment]
THANK YOU ☺


Best Regards,

Dina Slutzkin
Marketing Manager
Carmor Integrated Vehicle Solutions Ltd.
Tel: +972-4-6410-650
Fax: +972-4-6418-555
Mobile: +972-547725364
dina@carmor.com
www.carmor.com<http://www.carmor.com/>
[carmor - sig]
[cid:image002.jpg@01D0C88E.72038950]<https://www.linkedin.com/company/carmor-by-hatehof---integrated-vehicle-solutions?trk=biz-companies-cym>[cid:image002.png@01D03FB2.8520C3F0]<https://www.facebook.com/Hatehof?ref=hl>
