### ISSUE TITLE
Resource assignments

### ISSUE THREAD

**Issue by bjjohns** [bardsoftware/ganttproject#1160]
New resources created after a task cannot be added to existing tasks. GanttProject 2.7.1 Ostrava (build 1924). 
![image 2](https://cloud.githubusercontent.com/assets/13238817/8983406/15c81214-3698-11e5-8939-92d6f217c8bd.png)
![image 1](https://cloud.githubusercontent.com/assets/13238817/8983405/15c5ee1c-3698-11e5-9be2-dd3ff60b358b.png)

**Comment by dbarashev** [comment]
Resource and resource roles are different things. Think of resource as a human, and role as is its job. You added a job and you're looking at the list of humans.

**Comment by bjjohns** [comment]
I understand that. I see where I goofed. I failed to assign a resource with that role.

Sorry about this.

Thank you.
Bill J
From phone.
