### ISSUE TITLE
Usabilty - mouse drag start date (confused with %complete)

### ISSUE THREAD

**Issue by juzzle** [bardsoftware/ganttproject#1161]
When dragging the start date, the mouse selection is often confused with the %complete drag. I have no use for %complete. Ideally, the %complete internal bar should be supressed from the Gantt view so that selection of start and end handles is clear.  

This 'problem' severly limits my use of the application at the moment.

**Comment by dbarashev** [comment]
This mostly duplicates issue #762 so I am closing it as duplicate
