### ISSUE TITLE
Can't install on Mac 10.9.5

### ISSUE THREAD

**Issue by neoriddle** [bardsoftware/ganttproject#1163]
I have downloaded `dmg`file (https://dl.ganttproject.biz/ganttproject-2.7.1/ganttproject-2.7.1-r1924.dmg), then mount it and double-click GanttProject executable file. After that, GanttProject does not start as expected and some applications begin closing (Terminal, Safari, etc.).

I do not know if there a log file that can be adjoint here to help.

**Comment by dbarashev** [comment]
What version of Mac OSX do you use and do you have Java Runtime on your Mac?

**Comment by neoriddle** [comment]
Mac OSX 10.9.5 and Java 1.7.0_75-b13

Checking `~/.ganttproject.d/.ganttproject-20150812150627.log` file, it logs:

```
...
java.runtime.version: 1.7.0_75-b13
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 24.75-b04
os.arch: x86_64
os.name: Mac OS X
os.version: 10.9.5
...

**Comment by dbarashev** [comment]
Anything else in the log?

**Comment by neoriddle** [comment]
Previous log was generated using ZIP archive version and is the only way that I can execute GanttProject.

If I try with `dmg` version, after open `dmg` file some apps become "crazy" and they start failing and closing unexpectedly, so I can have a log on execution properly.

**Comment by dbarashev** [comment]
Can you run `GanttProject.app/Contents/MacOS/JavaAppLauncher` from the Terminal in the directory where GanttProject.app resides?

**Comment by marti1959it** [comment]
I have the very same problem.
The app looks like starting correctly but I can't see anything except for the splash screen and the menu bar has just the GanttProject menu (not edit, project and so on).
![image](https://cloud.githubusercontent.com/assets/3177354/10014173/c0bb5394-6117-11e5-9a04-fe1e452dde29.png)

Here is log:

GanttProject 2.7.1 Ostrava (build 1924)
Settings file:
	location: /Users/roberto/.ganttproject
	size:4134
	is readable: true
java.class.path: /Applications/GanttProject.app/Contents/Java/Classes:/Applications/GanttProject.app/Contents/Java/eclipsito.jar
java.home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
java.ext.dirs: /Users/roberto/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.io.tmpdir: /var/folders/mx/6h77scqn68nd13_rlssy735w0000gn/T/
java.runtime.version: 1.8.0_60-b27
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.60-b23
os.arch: x86_64
os.name: Mac OS X
os.version: 10.10.5
sun.java.command: org.bardsoftware.eclipsito.Boot -app net.sourceforge.ganttproject.GanttProject -plugins-dir /Applications/GanttProject.app/Contents/Java/plugins
user.country: IT
user.dir: /Users/roberto
user.home: /Users/roberto
user.language: it
user.timezone: Europe/Rome

Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. changing look'n'feel ...
8. finalizing...
Main frame created
Splash closed
set 22, 2015 10:43:49 AM net.sourceforge.ganttproject.GPLogger log
INFORMAZIONI: [GanttOptions] save(): finished!!
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
set 22, 2015 10:43:49 AM org.bardsoftware.impl.eclipsito.BootImpl shutdown
INFORMAZIONI: Eclipsito platform is shut down.
 
Running GanttProject.app/Contents/MacOS/JavaAppLauncher from the terminal has no effect
Can you help me?

**Comment by dbarashev** [comment]
> Running GanttProject.app/Contents/MacOS/JavaAppLauncher from the terminal has no effect

Ummm... really absolutely no effect?

Anyway, can you remove `GanttProject.app/Contents/Java/plugins/org.ganttproject.impex.htmlpdf` from your GanttProject app and see if it helps? Also, can you try using ZIP distro?
https://github.com/bardsoftware/ganttproject/wiki/Installing-from-ZIP

**Comment by marti1959it** [comment]
a) I removed GanttProject.app/Contents/Java/plugins/org.ganttproject.impex.htmlpdf from GanttProject app; it happened something strange: after the splash screen, the whole menu bar quickly flashed (in Italian, my Mac's language setting), but disappeared in a second
b) ZIP distro: sure I tried, but that's what happened:
   I run the shell, the splash screen came out, but no GanttProject menu bar, just Boot (?) menu bar
![image](https://cloud.githubusercontent.com/assets/3177354/10019788/9fdf48e2-613f-11e5-87cf-09e90d6d7c08.png)

**Comment by dbarashev** [comment]
anything in the console when running zip distro?

**Comment by marti1959it** [comment]
MacBook-Pro-di-roberto:ganttproject-2.7.1-r1924 roberto$ ./ganttproject.command
MacBook-Pro-di-roberto:ganttproject-2.7.1-r1924 roberto$ set 22, 2015 3:34:25 PM org.bardsoftware.eclipsito.Boot main
INFORMAZIONI: No options passed to Eclipsito. Searching for config in ganttproject-eclipsito-config.xml
set 22, 2015 3:34:25 PM org.bardsoftware.eclipsito.Boot main
INFORMAZIONI: Args: -plugins-dir=null -plugins-res=/plugins descriptor-pattern=plugin.xml app=net.sourceforge.ganttproject.GanttProject
set 22, 2015 3:34:25 PM org.bardsoftware.impl.eclipsito.BootImpl run
INFORMAZIONI: Eclipsito platform is running.
set 22, 2015 3:34:25 PM org.bardsoftware.impl.eclipsito.BootImpl getPlugins
INFORMAZIONI: Searching for plugins in /Users/roberto/Downloads/ganttproject-2.7.1-r1924/plugins
[DescriptorParser] parse(): plugin descriptor url=file:/Users/roberto/Downloads/ganttproject-2.7.1-r1924/plugins/biz.ganttproject.core/plugin.xml
[DescriptorParser] parse(): plugin descriptor url=file:/Users/roberto/Downloads/ganttproject-2.7.1-r1924/plugins/biz.ganttproject.impex.ical/plugin.xml
[DescriptorParser] parse(): plugin descriptor url=file:/Users/roberto/Downloads/ganttproject-2.7.1-r1924/plugins/biz.ganttproject.impex.msproject2/plugin.xml
[DescriptorParser] parse(): plugin descriptor url=file:/Users/roberto/Downloads/ganttproject-2.7.1-r1924/plugins/net.sourceforge.ganttproject/plugin.xml
[DescriptorParser] parse(): plugin descriptor url=file:/Users/roberto/Downloads/ganttproject-2.7.1-r1924/plugins/org.ganttproject.chart.pert/plugin.xml
[DescriptorParser] parse(): plugin descriptor url=file:/Users/roberto/Downloads/ganttproject-2.7.1-r1924/plugins/org.ganttproject.impex.htmlpdf/plugin.xml
set 22, 2015 3:34:25 PM org.bardsoftware.impl.eclipsito.BootImpl run
INFORMAZIONI: Command line args: [-log, -log_file, /Users/roberto/.ganttproject.d/.ganttproject-20150922153425.log]
Writing log to /Users/roberto/.ganttproject.d/.ganttproject-20150922153425.log

**Comment by dbarashev** [comment]
According to the log, everything is fine and GanttProject is supposed to be running. Can you run any other Java program on your Mac, e.g. FreeMind?

**Comment by marti1959it** [comment]
Dmitri,
I've just installed FreeMind and it works fine.

2015-09-24 13:34 GMT+02:00 Dmitry Barashev <notifications@github.com>:

**Comment by dbarashev** [comment]
I am closing this because it is already two years old and many things changed since that time. Please try GanttProject 2.8.3 if you still have a need to run GP on your Mac and feel free to reopen this issue or file a new one in case of troubles.
