### ISSUE TITLE
Make the items in combobox sorted

### ISSUE THREAD

**Issue by bero** [bardsoftware/ganttproject#1165]
![image](https://cloud.githubusercontent.com/assets/138818/9274300/2eb053de-429d-11e5-8486-7861406624c4.png)

Much easier to find the item you looking for when amount  is thousands.

**Comment by dbarashev** [comment]
Currently this dropdown shows tasks in the same order as they go in the document.

I am closing this in favor of previously submitted #750. It doesn't mention lexicographical ordering explicitly, but suggest other options and autocompletion which will probably solve the issue: if you know where to search in the sorted list then you can type the first letters of the task name in the field.

See also #176 which also is related to autocompletion
