### ISSUE TITLE
Dialogue Box is placed off screen when using 2 externel monitors

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1166]
my laptop uses 2 external screens
OS: w7 64bit

opening the property dialog results on the primary screen even when opening from the secondary screen. Part of the dialog  is placed outside of the window

a similar issue was reported in · Issue #1092 · but the proposed solution is not solving this issue. 

![2015-08-16](https://cloud.githubusercontent.com/assets/13802775/9300927/f386e8b0-44ca-11e5-9944-5f0c7acd9c9f.png)

**Comment by dbarashev** [comment]
Diplicates #939
