### ISSUE TITLE
Calendar days not displayed correctly 

### ISSUE THREAD

**Issue by dgm3333** [bardsoftware/ganttproject#1167]
on Windows10. The gant chart isn't showing every correctly - some are merged into one number even at maximal zoom
![gantproject1](https://cloud.githubusercontent.com/assets/51210/9319935/e17fe956-454b-11e5-81aa-af02fb541f4b.jpg)

**Comment by dbarashev** [comment]
Thanks for reporting.
FYI: we show weekend days "compressed" to save horizontal space, and normally do not show their day numbers because they just don't fit. However, sometimes when weekend day number is a single digit, they do fit and we show the dates
