### ISSUE TITLE
lines in timeline showing weeks

### ISSUE THREAD

**Issue by miguel-negrao** [bardsoftware/ganttproject#1168]
For me it would be useful to have the timeline display a grid with the division in weeks, so a vertical line to left of each monday. This is useful for me even when there is work being done on weekends, and specially in that case, since without those lines there is no indication of where the week ends. It is normal (in western society) to divide time in weeks, so it makes it easier to grasp the ammount of time tasks are taking and what should be done this week, even when one is working through the weekend. The weeks are already display with a small tick on the top of the timeline, but it would be nice to have the option of having the tick become a full vertical line.

**Comment by dbarashev** [comment]
Vertical stripes across the whole chart show up if weekend days are non-working days. If they are working days, you still can choose to show weekend days in the Project Calendar settings (option "On weekends" with value "all tasks run as on other days").

**Comment by miguel-negrao** [comment]
In my case weekends are working days, so the last option you suggest gets it closer to what I described. Still I'm more interested in the transition from sunday to monday then to distinguish weekend from non weekend days, so it's still not exactly what I was looking for.

**Comment by dbarashev** [comment]
If you choose Sunday as the only weekend day and set the option, you'll get  vertical stripes indicating end-of-week day.
