### ISSUE TITLE
Editing baseline colors in baseline dialog fails

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1171]
changing default colors e.g. on time or delayed - creates an error message in the baseline setup box.
![select color in baseline](https://cloud.githubusercontent.com/assets/13802775/9718070/c8f3154c-5578-11e5-942c-6cdda974d95c.png)

**Comment by dbarashev** [comment]
Thanks for reporting!

**Comment by steffenfritz** [comment]
+1
