### ISSUE TITLE
Removing predecessor doesn't respect begin date of Master task Begin date

### ISSUE THREAD

**Issue by danielfalsetti** [bardsoftware/ganttproject#1172]
Step 1:
- Create Tasks like this
  ![image](https://cloud.githubusercontent.com/assets/2716001/9799315/c2088b16-57dc-11e5-9c5f-4f687f411d05.png)

Step2: 
- Set predecessor on id 14 to 14 (like print)
  The task 17 was changed to begin 09/09/2015 - ok 
  ![image](https://cloud.githubusercontent.com/assets/2716001/9799340/f192f9b6-57dc-11e5-8833-e5b807fd2d12.png)

Step3:
- remove predecessor of task 17
  Bug: begin date must back to 09/04/2015 instead of 09/08/2015 as print below

![image](https://cloud.githubusercontent.com/assets/2716001/9799399/4371fcb4-57dd-11e5-8e2c-4e09e18938b6.png)

**Comment by dbarashev** [comment]
GanttProject doesn't distinguish between begin date set by user and begin date set by the scheduler, sorry. You may use "Earliest begin" constraint for this purpose. See [GP 2.8 announcement](http://ganttproject.blogspot.ru/2016/07/announcing-ganttproject-28-pilsen.html) for details.
