### ISSUE TITLE
Can't Open Granttproject without administrator rights

### ISSUE THREAD

**Issue by sdevospidy** [bardsoftware/ganttproject#1174]
Hi,

Since a few days i can't open Granttproject. The only possibility is to open the program as administrator. 
Sure i can give rights on the installation folder for all the users and give them full rights but's that's not wat i want. It workes before... 

Is there any other solution ? Has this something to do with the new java 60  ? 

Best Regards,

**Comment by dbarashev** [comment]
Did you install Java for administrator user only by any chance? Can you run `java` command from the command line prompt?

**Comment by sdevospidy** [comment]
I did an update via PDQ Deploy to java 60 on that computer. But the problem starts a day or 2 after the update...

**Comment by dbarashev** [comment]
Frankly, I have no idea what is PDQ Deploy and what is Java 60. I am aware of Java 6, Java 7 and Java 8. Did you mean Java 6?

**Comment by sdevospidy** [comment]
I'm sorry it's Java 8 Update 60

**Comment by dbarashev** [comment]
So can you run `java` command in the commmand line prompt?

**Comment by sdevospidy** [comment]
Hi Dbrashev,

How must I use the command ? i did open the commend line and typet : java
but he didn't reconize the command.

**Comment by dbarashev** [comment]
Okay, thanks. What happens if you do the same on behalf of administrator?

**Comment by sdevospidy** [comment]
Also 'java' is not recognized as an internal or external command operable program or batch file.

**Comment by dbarashev** [comment]
Okay, so I think you now have Java Runtime installed for administrator only. Try reinstalling it. You can download Java Runtime from http://java.com

When Java Runtime is installed normally it is accessible via the command line (typing `java` in the command line gives meaningful results). GanttProject may work even when `java` it is not found in the command line (and that seems to be the case for your administrator user) but having `java` command available almost guarantees that everything is fine.

**Comment by sdevospidy** [comment]
Hi dbarashev,

I gone give that a try, thanks for your fast answers ! 
I will let you know soon if it works.

Appriciat your help !

Best Regards,

**Comment by sdevospidy** [comment]
Hi dbarashev,

It's seems working now, we updated to the latest version with our deployment kit and it works now.
Thank you for your help !

Best Regards,
