### ISSUE TITLE
Task order is reversed after CSV export + import

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/ganttproject#1178]
_from email_

Export HouseBuildingSample to CSV and import it back. The order of tasks is reversed.

![unnamed](https://cloud.githubusercontent.com/assets/2028330/9992684/56b456da-607c-11e5-95de-70da54e4c7ea.png)

**Comment by dbarashev** [comment]
@swiatkot 

The following scenario works fine in GP 2.7.2 with default export settings

1. Start GP
2. Open HouseBuildingSample.gan
3. Export to CSV
4. Close GP
5. Start GP again
6. Import file produced at step 3.

Task order is left as it was in the original file. This issue IS solved.

With respect to duplicated columns, you may want to check your settings (Edit->Settings->CSV) or even better delete file `.ganttproject` from the home directory. There was a bug which added some columns twice and since export settings are stored persistently, it is possible that GP is using your old setup.

**Comment by swiatkot** [comment]
​Hi,

Please try this with attached file.
If the project has more than 10 items at the same level (at least in
highest as in attached example) exporting to csv and importing back gives
wrong order. For me it looks that column with ID is sorted as "string" not
as "integer".

Please feedback me if you can't replicate the problem.

​
​BRgds
swiatkot


2016-06-08 14:52 GMT+02:00 Dmitry Barashev <notifications@github.com>:

**Comment by dbarashev** [comment]
No attachment found.GitHub issue tracker does not support attachments through email replies. Please attach the file in the web interface or send it to contact@ganttproject.biz

**Comment by swiatkot** [comment]
attached file to test

[Project to test.zip](https://github.com/bardsoftware/ganttproject/files/318594/Project.to.test.zip)

**Comment by dbarashev** [comment]
Okay, you're right. Outline numbers are compared as strings which is wrong when the number of sibling tasks exceeds 10. Reopening.

Thanks for reporting!

**Comment by dbarashev** [comment]
@swiatkot outline numbers comparison is fixed; with respect to Coordinator and Cost, it seems that you have custom columns with exactly these names in your project and CSV export writes custom columns thus confusing CSV import. You can remove or rename custom columns.
