### ISSUE TITLE
Another language problem German/English

### ISSUE THREAD

**Issue by AndySymons** [bardsoftware/ganttproject#1179]
When I first installed GANTTProject on my Mac with Yosemite (10.10.5) I had the system preferences set to the German language. I since changed it to English and restarted. Most apps then switch to English, but GANTTProject is still in German. I wiped the .app file and re-installed it from ganttproject.biz but still it persists in German. How can I persuade it to speak English? I guess there must be config file that has persisted but I cannot find it.

**Comment by dbarashev** [comment]
Edit->Settings->Application UI->Interface Language

**Comment by dbarashev** [comment]
Config file, if you need it, sits in `$HOME/.ganttproject`

**Comment by AndySymons** [comment]
Great. I deleted the .ganttproject file and then reinstalled GAnttproject from the .dmg, now it is in English :-) 
It would be better if the installer re-wrote the .ganttproject file every time instead of leaving it. 
Note that .ganttproject is normally a hidden file, so you have to take steps to show it first, and it does not show up in searches. 

Regards, 
 
Andy

**Comment by dbarashev** [comment]
Not sure that you really want to remove all your settings every time you upgrade GP from one minor version to the next one. Besides, there is no installer on Mac. You just copy GanttProject.app to Applications (you can even do not bother with doing that).

Hope the issue is resolved now.

**Comment by AndySymons** [comment]
It was easier than trying to figure out the format of the config file! 
A better fix would be for your program to follow the system settings, as most apps do. 

Andy
