### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by sedanielson** [bardsoftware/ganttproject#1181]
Just downloaded ganttproject; best and easiest project planning tool I've found. I would like to be able to print the notes I attach to tasks. Perhaps on the export file a page that lists the task and note could be added.

**Comment by dbarashev** [comment]
There is an option in PDF export to export or not to export the notes and it is switched on by default

![export](https://cloud.githubusercontent.com/assets/2028330/10426897/3d5a59f6-70ed-11e5-8be0-75cb418710de.png)

**Comment by sedanielson** [comment]
Hmmm. I did export to pdf and the notes did not follow. I’ll take another look.
