### ISSUE TITLE
Changing the begin date after the date has passed

### ISSUE THREAD

**Issue by mariahhope** [bardsoftware/ganttproject#1182]
I developed my Gantt Chart based on the information I had, which said the project would start on Monday. It is now Wednesday, and the project is starting tomorrow. I need to change all the dates on the chart to the new start date, but the software won't let me make any revisions. Do I have to save it under a new name to change the dates or retype all the entries. If you are using this software for project tracking, how do you update the dates as delays and rescheduling occurs if they happen after the initial start date? Do you delete the line and replace it?

**Comment by dbarashev** [comment]
If you want to move the whole project use Project->Properties->Calendar

Individual tasks can be moved with start date change or dragndrop, provided that dependencies do not object

**Comment by mariahhope** [comment]
Thank you, it worked.
