### ISSUE TITLE
Default disable 'Check for GanttProject updates daily' 

### ISSUE THREAD

**Issue by grey-s0n** [bardsoftware/ganttproject#1183]
Hi.  Trying to deploy the latest version to several users at my organisation, however require the option 'Check for GanttProject updates daily' to be disabled by default on install and first run.  Is there any way to accomplish this?

**Comment by dbarashev** [comment]
Hello, 
you can deploy the options file with the required settings to your users along with GanttProject distro. File should be named `.ganttproject` and should be put into user's home directory.
