### ISSUE TITLE
Week Numbers wrong: year 2015 has 53 weeks, but only 52 are shown.

### ISSUE THREAD

**Issue by tomgru** [bardsoftware/ganttproject#1184]
using: GanttProject 2.7.1 Ostrava (build 1924) on OS X 10.11 (15A284)

The year 2015 actually has 53 weeks, but Gantt Project only shows 52.

21. December - 27. December is Week 52.
28. December - 03. December is Week 53.
Then comes Week 01

Now this means that for 2016, the week numbers are wrong. Week 01 for 2016 should start on 04. December, but in Gantt Project it starts already on 28. December.

thank you,
-tom

**Comment by dbarashev** [comment]
Please have a look at this discussion:https://forum.ganttproject.biz/view/20150817124654_27ziajhopwjtxserosos6mtui

TL;DR: set your interface language to English (United Kingdom)

**Comment by tomgru** [comment]
thank you! works fine now!
