### ISSUE TITLE
non ascii charecters in source code prevents building from source

### ISSUE THREAD

**Issue by lumnis** [bardsoftware/ganttproject#1186]
When trying to compile version 2.7.1 from source, I'll get the following error's

[   20s] build:
[   20s]      [echo] biz.ganttproject.core: ganttproject-2.7.1-src/biz.ganttproject.core/build.xml
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/build-user.xml:24: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
[   20s]     [javac] Compiling 106 source files to ganttproject-2.7.1-src/biz.ganttproject.core/bin
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/DateParser.java:18: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                ^
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/DateParser.java:18: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                 ^
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/DateParser.java:18: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                       ^
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/DateParser.java:18: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                        ^
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/InvalidDateException.java:9: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                ^
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/InvalidDateException.java:9: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                 ^
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/InvalidDateException.java:9: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                       ^
[   20s]     [javac] ganttproject-2.7.1-src/biz.ganttproject.core/src/org/w3c/util/InvalidDateException.java:9: error: unmappable character for encoding ASCII
[   20s]     [javac]  * @author Beno??t Mah?? (bmahe@w3.org)
[   20s]     [javac]                        ^
[   20s]     [javac] 8 errors

Please consider avoiding the use of non ascii characters within source files.

regards,
Denny

**Comment by dbarashev** [comment]
Please consider using UTF-8 encoding in the compiler options. We will add explicit encoding parameter value to our build files.
