### ISSUE TITLE
During CSV import indented tasks are unindent

### ISSUE THREAD

**Issue by hardikdangar** [bardsoftware/ganttproject#1189]
when you import csv tasks which are indented becomes unindented. to test this you can create two tasks and indent second task within first task. export csv. create new project and import the same csv. you can notice indented tasks are unintended.

My os : ubuntu 14.04
My build : GanttProject 2.7.1 Ostrava ( build 1924)

**Comment by hardikdangar** [comment]
i believe this is similar to  issue #969

**Comment by dbarashev** [comment]
Please make sure that you have "Outline Number" column switched on in the CSV export settings (Edit->Settings->CSV)

**Comment by hardikdangar** [comment]
Above solution fixed the problem. Thank you very much for your help on this.
