### ISSUE TITLE
Missing wiki pages

### ISSUE THREAD

**Issue by wiktorn** [bardsoftware/ganttproject#1192]
On your page (http://www.ganttproject.biz/participate - section development) one may read that there are some information that could can be read at wiki pages:
https://code.google.com/p/ganttproject/wiki/BuildingGanttProject
https://code.google.com/p/ganttproject/wiki/SendingPatches

But both links direct to main page of the project and there are no such wiki pages in project.

Please fix the links and reintroduce pages in github project repository

**Comment by dbarashev** [comment]
I hope it is fixed now.
