### ISSUE TITLE
how to zoom back further?

### ISSUE THREAD

**Issue by foice** [bardsoftware/ganttproject#1193]
Is there a way to zoom out to a level where I do not see the months anytmore? I am planning on 5 years and I have only 1-year blocks, so the months are pretty useless ... they just make very hard to produce a readable export ... 
how can I zoom back more?

**Comment by dbarashev** [comment]
There are no other zoom levels except those which are accessible with zoom in/out buttons, sorry.

**Comment by foice** [comment]
not event playing with .ganttchart file ?

**Comment by dbarashev** [comment]
We have no such file (did you mean .ganttproject ?) but anyway, all zoom levels are those which you see in the UI.

**Comment by foice** [comment]
sorry for the wrong name, . ganttproject is the file I meant.
thanks anyways for replying. I hope zoom can be changed to wider ones in future versions.

**Comment by RadialAdmin** [comment]
But on the contrary I would like to have a more detailed plan to within minutes and seconds.
It may be necessary to make it a optional in the project properties.

**Comment by dbarashev** [comment]
Duplicates #336, #225
