### ISSUE TITLE
GanttProject leaks shared memory until the desktop starts breaking

### ISSUE THREAD

**Issue by ssokolow** [bardsoftware/ganttproject#1197]
On Ubuntu Linux 14.04, GanttProject 2.7.1 Ostrava (build 1924) slowly allocates more and more shared memory until, after maybe 24-48 hours left open, applications start presenting this error message via `stderr` on launch and, if they're Qt-based, they render garbled windows.

    shmget failed: error 28 (No space left on device)

I first encountered the problem when K3b (DVD-burning utility) opened up garbled but this Ask Ubuntu question contains a screenshot of a similar bug in PyCharm causing it to happen to Skype.

https://askubuntu.com/questions/692825/how-to-fix-graphical-issues-with-skype-gdk-warning

One of the answers explains how to identify the source of the problem. (Basically, you use `ipcs -mp` to find the culprit's PID and then resolve that to the process name via whatever approach you prefer)

**Comment by dbarashev** [comment]
Is it your case by any chance? https://bugs.archlinux.org/task/45824

**Comment by ssokolow** [comment]
Yep, that fixed it. 

Following the enhanced testing in those bugs, I discovered that simply moving my mouse over GanttProject caused open SHM segments to skyrocket into the thousands.
Finding a PPA with a backport of OpenJDK 8 caused the SHM segments to remain steady at 77.
