### ISSUE TITLE
Create task lasting hours

### ISSUE THREAD

**Issue by lucap261** [bardsoftware/ganttproject#1198]
Hi,

compliments for you great software! I was wondering if you could add an interesting feature:

- when you create or update a task could be possible to set as duration not only days but also hours?

It is a huge problem to plan activities that can last only days, there are also tasks that last hours. It could be useful in order to plan activities in a fine-grain way, for instance, activities of programmers that fits better the reality, where there are a lot of tasks that require hours.

Please, say to me if it is possible to implement and notify me, please, when the feature will be available.

Thank you very much in advance,

Best Regards,

Luca

**Comment by dbarashev** [comment]
Duplicates issue #225
