### ISSUE TITLE
Summary task progress won't update after deleting child task

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1200]
for a task which is subdevided into multible subtask the main task is computing somehow the resulting progress - here 90%.
![before](https://cloud.githubusercontent.com/assets/13802775/11381427/5b85c47a-92fc-11e5-8f88-8b90d5a316bf.PNG)
When now a task is deleted, one would expect that for the main task the resulting new progress will be recomputed.
![after](https://cloud.githubusercontent.com/assets/13802775/11381571/0b26a0ac-92fd-11e5-9c59-554a0d0cec61.PNG)
Unfortunate, the main task wil not be recalculated even if F5 is pressed.or the ganttshart is saved and than reloaded. The expected progress shoud be 100%
 The go-around I found is to change one progess to a dummy value - now the progress is recomputed - and than change it back to prevous progress value
![dummy input](https://cloud.githubusercontent.com/assets/13802775/11381919/41e29a54-92ff-11e5-8a1c-84602c5356ac.PNG)

**Comment by dbarashev** [comment]
Thanks for reporting!
