### ISSUE TITLE
Connection refused when converting project to PDF

### ISSUE THREAD

**Issue by vanesaferrandis** [bardsoftware/ganttproject#1202]
I tried with company network and outside one.
I attach the
[RedCorporativaLogGantt.txt](https://github.com/bardsoftware/ganttproject/files/47317/RedCorporativaLogGantt.txt)
[RedExternaMovistarLogGantt.txt](https://github.com/bardsoftware/ganttproject/files/47316/RedExternaMovistarLogGantt.txt)

 files.

**Comment by dbarashev** [comment]
The logs say that you're trying to publish PDF on some FTP server. If you really meant that, please make sure that FTP credentials are correct and you have write permissions. If you didn't mean to publish PDF, please uncheck the cirresponding option in the export wizard.

**Comment by vanesaferrandis** [comment]
Hi there,

We don´t want to publish in any FTP. Bu t  I couldn´t find any check to uncheck.

I attach the screenshots.

Can you give a hint how to disable it?

Thanks in advance,

[SanLucar Party]<http://www.sanlucar.com/aktionen/heidi/>


Vanesa Ferrandis | IT Helpdesk Technician

Phone: +34 96 142 40 40 | Extn.2203
Mobile: +34 686 044 745 | Fax: +34 961 424 235
vanesa.ferrandis@sanlucar.com<mailto:vanesa.ferrandis@sanlucar.com>

SanLucar Fruit S.L.
Serra Llarga, 24 | 46530 Puzol | Valencia | España
www.sanlucar.com <http://www.sanlucar.com>

Este correo y cualquier fichero adjunto contiene información confidencial y se dirige exclusivamente a su destinatario. Si ha recibido este mensaje por error, por favor notifíquelo a office@sanlucar.com<mailto:office@sanlucar.com>. Si Vd. no es el destinatario, por favor, elimínelo y notifíquelo al remitente.
This email and any attached files are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email by error please notify to office@sanlucar.com<mailto:office@sanlucar.com>. If you are not the named recipient, you should return this message without reading further and delete it from your system.
Diese E-Mail und sämtliche angehängten Dateien enthalten vertrauliche Informationen und sind ausschließlich für den Adressaten bestimmt. Falls Sie diese E-Mail irrtümlich erhalten haben, bitten wir Sie uns unter office@sanlucar.com<mailto:office@sanlucar.com> über diesen Vorgang zu informieren, die E-Mail ungelesen an uns zurückzusenden und aus Ihrem System zu löschen.

**Comment by dbarashev** [comment]
No screenshots found. Please use web interface to attach files. Thanks.

**Comment by vanesaferrandis** [comment]
I attach the screenshots
![gantt_exportation_wizard](https://cloud.githubusercontent.com/assets/16083196/11505059/bee6acea-9848-11e5-8f9e-324bbafae84c.jpg)
![gantt_properties](https://cloud.githubusercontent.com/assets/16083196/11505060/beed086a-9848-11e5-9934-ae89b10d4e04.jpg)

**Comment by dbarashev** [comment]
Right, there is no this option in the PDF export which is strange. However, it is common for all exports, so if you  try exporting to say PNG image, you'll find this option "Publish files on FTP" and I believe it will be in the state "Yes". Switch it to "No".

**Comment by vanesaferrandis** [comment]
It was activated in PNG option.
I deactivated it and it worked.
Thanks a lot!
