### ISSUE TITLE
Wrong dates of milestones exported to MS Project XML

### ISSUE THREAD

**Issue by WulfChang** [bardsoftware/ganttproject#1203]
Hi:
I found that milestone's start date overpass end date while making a XML MS project file.
For example,
When I set milestone start from 11/20 and end at 11/20, XML shows start: 11/20, end: 11/19.

Hope you understand.

Thank!

**Comment by dbarashev** [comment]
Thanks for reporting!

**Comment by steffenfritz** [comment]
This bug also occurs when exporting to pdf

**Comment by dbarashev** [comment]
@steffenfritz what version of GanttProject are you using? PDF export was fixed long ago. See issue #763

**Comment by steffenfritz** [comment]
@dbarashev GanttProject 2.7.1 Ostrava (build 1924)

**Comment by dbarashev** [comment]
And what exactly do you observe? I am asking because what is described in this issue - milestone end date appears one day before the start date - is not reproducible in PDF export. In the table where task dates are printed milestone start and end date are the same.
