### ISSUE TITLE
Problem in displaying GANTT - Chart 

### ISSUE THREAD

**Issue by KerblEbenthal** [bardsoftware/ganttproject#1204]
Hi,

I'm usin German version of "Ganttproject 2.7.1 build 1924"
 
After having edited and exported a project, I 
- changed the Font in "Einstellungen" and finally choose "Arial"
- entered a filename for a logo
After changing the font, the list of activities left in the GANTT-chart appeared in Bold letters 
I closed and reopened the Programm - now there is NOTHING  to be seen in GANTT Chart -(neither in the left side list nor in the Calendar chart - except the Chart's headline)
Adding new activities is still possible (they can be shown in PERT-Chart) and exporting into .pdf is possible, too - seems to be a problem of displaying the Gantt-list/chart...

What can I do ?
kind Regards
Lothar Kerbl

**Comment by dbarashev** [comment]
Can you share the project file?

**Comment by KerblEbenthal** [comment]
Thank you für your quick answer

You‘ll find attached;

-          The project (kerbl_kompetenzen.gan)

-          Screenshot of GANTT Chart (… is empty !!…)

-          Screenshot of PERT Chart (seems to be o.k.)

-          Exported pdf (seems to be  o.k.)

As far as I see, it is not a problem oft he Projectfile, because „ganttproject“ shows the same behaviour when started  without loading a project file resp. With any Project file loaded … …

I have even deinstalled and reinstalled the programm …. (I didn’t mention it yet: OS is „Windows 7 Professional (SP1)“ on a „DELL PRECISION  M6600“ Notebook)


Up to now I have planned apx. 10 projects with ganttproject and it has worked quite fine up to now ….

By the way: I didn’t find a possibility to define the „Project Manager“ (planned tob e shown on the first page oft he PDF-Export) One thing: I find

Kind regards
Lothar Kerbl


Von: Dmitry Barashev [mailto:notifications@github.com]
Gesendet: Mittwoch, 02. Dezember 2015 14:58
An: bardsoftware/ganttproject
Cc: KERBL, Lothar
Betreff: Re: [ganttproject] Problem in displaying GANTT - Chart (#1204)


Can you share the project file?

**Comment by dbarashev** [comment]
No attachments found. GitHub issue tracker doesn't support attachments in email. Please use web interface. Please be aware that this issue is public visible.

**Comment by KerblEbenthal** [comment]
System response:
"Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF"

... to make uploading possible, I renamed the ".gan" File into ".txt"
[Kerbl_kompetenzen - Kopie.txt](https://github.com/bardsoftware/ganttproject/files/50254/Kerbl_kompetenzen.-.Kopie.txt) .

..."pdf" upload didn't work, therefore I RENAMED the files !
[PROJECT_EXPORT_pdf.txt](https://github.com/bardsoftware/ganttproject/files/50272/PROJECT_EXPORT_pdf.txt)
[PERT_CHART_Screenshot_PDF.txt](https://github.com/bardsoftware/ganttproject/files/50271/PERT_CHART_Screenshot_PDF.txt)
[GANTT_CHART_Screenshot_PDF.txt](https://github.com/bardsoftware/ganttproject/files/50268/GANTT_CHART_Screenshot_PDF.txt)

**Comment by KerblEbenthal** [comment]
Hallo, 
after switching the language to "English" and rebooting the PC, everything seems to work well again ...
Up to now I could not reproduce the situation of "empty Gantt-Chart" ...

Lothar Kerbl
