### ISSUE TITLE
Ressource not lasting for the full task

### ISSUE THREAD

**Issue by Jean-Rpi** [bardsoftware/ganttproject#1206]
Hello everyone,
I need to use different ressources on different tasks on the same period, but not during the entire task.
For example:
My task n°1 lasts 5 days. I need ressource n°1 to work the 2 first days, and the last day, and ressource n°2 to work days 3 and 4.
Is it a possible thing to do? 
Thank you in advance, that would be extremelly helpful. 
Best Regard,
Jean

**Comment by RadialAdmin** [comment]
IMHO not need to use one task, you must use 3 different subtasks to describe when resources used in work.

**Comment by Jean-Rpi** [comment]
Hi, thank you for your answer! But I'm affraid that method won't work for me:
-to be more precise I have six tasks on the same period, and 7 ressources.
The real duration of the tasks I scheduled is approximatively a year each so with the "subtasks method", it would be a never ending job to create each time a subtask... 
Thanks again for your answer.

**Comment by RadialAdmin** [comment]
Only this method will work for you. I don`t understand why job is never ending. If you can describe in one task how much time each resource spend on this task, why you can`t add subtasks with this information?
You can copy part of tree of subtasks in text mode after export.
I have 50 resources and hundreds tasks with 2-10 subtasks on each. Subtask have duration 5-60 min. But in my system i can create tree of subtasks based on the template system.

**Comment by Jean-Rpi** [comment]
I guess I was expecting something different from this software :)
I will use this method, thank you RadialAdmin!
