### ISSUE TITLE
start date can't be in the past

### ISSUE THREAD

**Issue by paddor** [bardsoftware/ganttproject#1207]
This would be really useful to be able to use this tool for virtual project management, like for studies.

**Comment by dbarashev** [comment]
Can you explain what is the issue?

**Comment by paddor** [comment]
Nothing happens when I set the begin date of a task in the past. There's no error message. The date is just silently set back to today as soon as I confirm.

**Comment by dbarashev** [comment]
Most likely there is a good reason. Please read this: http://forum.ganttproject.biz/view/20151206134010_4np9wjl9m87yr5dqazag9mxyq#1
