### ISSUE TITLE
Drag and drop issues in the task table 

### ISSUE THREAD

**Issue by paddor** [bardsoftware/ganttproject#1209]
* often times when trying to drag it, it starts selecting multiple tasks
* even if I get it to drag, a task item can't easily be moved from one subtree to another

**Comment by dbarashev** [comment]
Ctrl+X and Ctrl+V will hopefully solve the issue.

**Comment by paddor** [comment]
Sorry, but Ctrl-X and Ctrl-V aren't drag&drop.

**Comment by dbarashev** [comment]
Surely not. But they work.

**Comment by dbarashev** [comment]
Reopening note: despite the fact that there is a workaround, it is clearly a usability issue.

**Comment by paddor** [comment]
Could you create a new issue for this? I don't wanna see this issue in my list of open issues anymore.
