### ISSUE TITLE
Print settings

### ISSUE THREAD

**Issue by dmroo** [bardsoftware/ganttproject#1210]
Hi all,
I am very new here so please bare with me.
I have just downloaded the program and think it has sooo much potential. so far job well done.
I do have thought concerning the printing of the project though. During the print setup you can change the Margins but only when you intend to make the print. I think it would be worth while to have it so you can setup a more permanent print setting and if wanting to change according to paper size or project size, it can be altered. Also seems that the printed version are not very clear even though I have experimented with fonts. Just a thought.
Thanks again for your hard work you are doing. I will be following with open eyes.
regards
DMROO

**Comment by dbarashev** [comment]
The best way to print is to export to PDF or PNG and print using appropriate tools.
See #364

**Comment by dmroo** [comment]
Wow, Thanks heaps for your very fast response, Much appreciated, As I mentioned still getting used to it and I still have to play around with Fonts also. I still have Printing concerns though. It seems to just center page and printing A4 just doesnt look correct. But ill keep practising. Thanks again
