### ISSUE TITLE
Summary task progress won't update after changing child task duration

### ISSUE THREAD

**Issue by ParaDogg** [bardsoftware/ganttproject#1211]
The refresh of the progress calculation doesn´t work if I change the task length (e.g. from 1 day to 3 days). Example 
+ GlobalTask 10 %
 - Task 1 - 2 days 20 %
 - Task 2 - 1 day 0 % 
 - Task 3 - 1 day 0 %

change the time of task 1 to 1 day 
+ GlobalTask 10 % <--- the percentage value doesn´t refresh even if I press F5
 - Task 1 - 1 day 20 %
 - Task 2 - 1 day 0 % 
 - Task 3 - 1 day 0 %

The workaround is to change the progress of Task 1 to an other value. Then reset it to the real value.

**Comment by dbarashev** [comment]
Related: issue #1200
