### ISSUE TITLE
Calendar Weeks displayed wrong

### ISSUE THREAD

**Issue by 0x79** [bardsoftware/ganttproject#1212]
The calendar weeks for the year 2016 are starting 1 week too soon. 

2015 hast 53 calendar weeks, 2016 has 52. Calendar week 1 in gantt project should be 53. Therefore the numbering is incorrect.

See the definition here: https://en.wikipedia.org/wiki/ISO_week_date#First_week

Version 2.7.1 Ostrava (build 1924)

**Comment by dbarashev** [comment]
Please read this: http://forum.ganttproject.biz/view/20150817124654_27ziajhopwjtxserosos6mtui

TL;DR: switch interface language to English (United Kingdom)
