### ISSUE TITLE
Add feature for Database (like MySQL) Project Storage for collaborative work

### ISSUE THREAD

**Issue by musahi0128** [bardsoftware/ganttproject#1219]
First time i use the GanttProject, i think this is what i need. Well that's it, until there is need to work collaboratively on a project. A concept where 1 administrator managing the project did'nt work in my case, so i hope there is an option to use database as a project storage where multiple user can work on it.

**Comment by dbarashev** [comment]
Database storage per se won't give you collaborative work. Please consider using WebDAV server 
(this protocol is supported by GP) or just simple shared disk for collaboration.
