### ISSUE TITLE
Standard (ISO 8601) week number 

### ISSUE THREAD

**Issue by ikantor** [bardsoftware/ganttproject#1220]
Currently the app shows wrong week number. Example: today is 13.02.2016. According to ISO 8601 it is calendar week 06, however the Gantt app shows calendar week 07. 

Solution: the app show get local calendar settings. 

More details: http://apple.stackexchange.com/questions/191445/standard-iso-8601-week-number-in-calendar-app

**Comment by dbarashev** [comment]
Please read FAQ: http://ganttproject.blogspot.ru/search/label/faq
