### ISSUE TITLE
Gantt project 2.7.1 doesn't start since I changed my logo

### ISSUE THREAD

**Issue by guillaume7684** [bardsoftware/ganttproject#1223]
Hello,
I use Gantt Project since about 1 year, I created a lot of plannings, and I decided to change the logo of the Dashboard, and now it doesn't want to start.
So i decided to uninstall it, and reinstall the new release 2.7.2, and nothing change.
Could you help me?
Thanks.
Regards,
Guillaume.

**Comment by dbarashev** [comment]
Hello,
the easiest way is to remove your settings file. The settings file is named `.ganttproject` and is stored in your home directory. Home directory on Windows systems is normally something like ```C:\Users\<your username>```

Note the dot in the file name. Some operating systems may hide this file in UI.

**Comment by alvespms** [comment]
It is probably a good option to have a logo that is small enough to fit on the window.
