### ISSUE TITLE
Recurrent tasks/ series of events

### ISSUE THREAD

**Issue by olassozeit** [bardsoftware/ganttproject#1225]
At the moment recurrent tasks could only be planned in the whole duration of the series. They are not visualized as recurrent tasks and the resource calculation could only be set as an average.

As an alternative a series of events (e.g. project meetings) has to be planned as single tasks (optionally bound together through a task group).

The first solution keeps the Gantt Chart smart but is imprecise for resource planning, the alternative leads to unnecessary “waterfalls” in the chart.

Especially for visualization but also for usability issues it would be great having an option for recurrent events. In my eyes his is the only missing feature in relation to MS Project Gantt Charts.

Recurrent tasks should be visualized as an interrupted bar in one line.

From point of linking it is not necessary to link single events of a series, the series should be treated as one task in this aspect.

Event calculation within the series: If a single event would end after the end of the series, it sould be excluded (it should not lead to an shorter last event).

Possible integration in the properties dialog:
![recurrent tasks](https://cloud.githubusercontent.com/assets/12987894/13666021/9ce74e28-e6af-11e5-9c4e-51e89896c5fb.jpg)

(A selection of a number of events as an alternative to the time period is not necessary).

**Comment by dbarashev** [comment]
Duplicates #277

**Comment by olassozeit** [comment]
Dear Dmitry,

sorry I did not check for existing feature requests - though mine came
along with a detailed idea how to do it.

GanttProject is a great piece of software, I was very pleased to find my
translation suggestions for German in the recent version.

Please keep on developing!

Thanx and best regards
Olaf

Am 10.03.2016 um 12:43 schrieb Dmitry Barashev:
