### ISSUE TITLE
Task names are illegible - text area is not tall enough. HD display 3840 x 2160

### ISSUE THREAD

**Issue by Muzzerboy** [bardsoftware/ganttproject#1231]
I can't read the task names and the text resizing options don't help. 

I have a 2016 Dell XPS15 with 3840 x 2160 display. Windows 10/64.

![image](https://cloud.githubusercontent.com/assets/6855686/14348810/c6ff6796-fcb6-11e5-9c87-bc8b0de4689e.png)

**Comment by Muzzerboy** [comment]
Slightly better when I select the largest application font size but still cuts off everything below the line. Also, when I edit the task name, the text becomes too small to read.
![image](https://cloud.githubusercontent.com/assets/6855686/14348969/b35296b8-fcb7-11e5-8f7b-ee148bb5322a.png)

The file dialogue icon sizes are also screwed up:
![image](https://cloud.githubusercontent.com/assets/6855686/14349011/f42007e8-fcb7-11e5-98cd-cea0c9725ef0.png)

**Comment by dbarashev** [comment]
Did you try changing application font and/or appearance? 

> Slightly better when I select the largest application font size

Did you mean _the smallest_?

**Comment by dbarashev** [comment]
Also, make sure that application and chart fonts are similar and have the same size. The height of row in the task table is calculated from the chart font metrics (because it depends on the configuration of chart rows).

**Comment by Muzzerboy** [comment]
No. Bizarrely, the rows were easier to read when the font size is _biggest_. But I couldn't read the text on a HD display if I used the smaller ones...

Funny thing is that I have now closed down the program and when I open the file, the fonts are a better fit: 
![image](https://cloud.githubusercontent.com/assets/6855686/14351527/c0ce647e-fcc7-11e5-9dba-727410d9fd80.png)

But the dialogue boxes scaling is still all over the place:
![image](https://cloud.githubusercontent.com/assets/6855686/14351515/ab24125e-fcc7-11e5-87cd-0d24868608d1.png)

**Comment by Muzzerboy** [comment]
And the menu font and icon sizes are all over the shop:
![image](https://cloud.githubusercontent.com/assets/6855686/14351822/56ea5660-fcc9-11e5-95f1-95b03eaac4d6.png)

I must admit, some Windows and Office apps also can't get the fonts and icons to behave.

**Comment by dbarashev** [comment]
So what's your setup now? Both application and chart fonts the largest ones?

**Comment by Muzzerboy** [comment]
Yes:
![image](https://cloud.githubusercontent.com/assets/6855686/14353421/e89a4f28-fcd0-11e5-9e63-1ab46e01e038.png)

**Comment by Muzzerboy** [comment]
One option that seems to help when running programs on a QHD / 4K monitor that haven't been optimised for them yet is to right click the program icon, select compatibility and tick "Disable display scaling on high DPI settings". For instance, I found that this allowed me to run Solidworks sensibly, whereas I'd been completely unable to work with it before.

I've found Gannt Project easier to use after ticking that option. I've now put the 2 font sizes down to "larger" and the various icons etc seem less extreme in size range.

**Comment by dbarashev** [comment]
This was actually fixed in GP 2.8.3, but in the new GP 2.8.4 it should work even better. Making application font bigger should make the rows bigger as well, and there is new DPI option in the settings which will scale everything in the user interface.
