### ISSUE TITLE
Spontaneous column reorder

### ISSUE THREAD

**Issue by ByronWillis** [bardsoftware/ganttproject#1240]
I find that the columns will spontaneously reorder themselves.  Particularly the column "Coordinator".  I use it as a blank spacer column and I find that it often will move and I have to drag it back to my desired position.

**Comment by dbarashev** [comment]
Sounds similar to #1276

**Comment by dbarashev** [comment]
Can you check if it is reproducible in GP 2.8 beta I? Annuncement: http://ganttproject.blogspot.ru/2016/07/announcing-ganttproject-28-pilsen.html

**Comment by dbarashev** [comment]
Closing as no response and most likely fixed.
