### ISSUE TITLE
Print quality of text

### ISSUE THREAD

**Issue by ByronWillis** [bardsoftware/ganttproject#1242]
I use Bluebeam, a professional PDF editing and creation software.  I can select Bluebeam PDF as a print option, which I often do with other programs.

When I print to PDF from GanttProject, the text quality comes out pretty poor.  It would be nice if the text was either higher DPI or vector.  It was unusable on an 11 X 17 page size.

**Comment by dbarashev** [comment]
Printing is old, rusty and not really maintained. The best way to print is to export to PDF or PNG from GanttProject. Our own PDF export produces high-quality PDF. See also #364

**Comment by ByronWillis** [comment]
OK wow this is a huge difference in quality!  Just test printed one of my schedules using the "export" to pdf option and wow looks nice.  I consider this issue closed unless you are revisiting Printing.  Perhaps just eliminate printing all together and only allow export?
