### ISSUE TITLE
Print settings reset

### ISSUE THREAD

**Issue by ByronWillis** [bardsoftware/ganttproject#1243]
This would be my #1 issue to address.  When I go to print something, I customize the following:
1.) Page size
2.) Date range
3.) Chart zoom

I get it looking mostly right and then I print.  Next time that I go back in to print something all of the print settings have been reset to the defaults.  It would be great if they came back up just as I left them.

**Comment by dbarashev** [comment]
Use PDF export or export to PNG.

**Comment by ByronWillis** [comment]
10-4 way better.  Will do.
