### ISSUE TITLE
Import from CSV or TXT doesn't work correctly

### ISSUE THREAD

**Issue by MHeber** [bardsoftware/ganttproject#1246]
Hi guys,

I can export a gantt project to csv and reimport without troubles. But as soon as I add a line to the csv file to create a new task the Import results in: Nothing. Its worse with text files, because here the whole line gets imported as the task name and the start and end dates are being ignored (they are all set to the current date). I must say this software seems to be a great tool, but if I cannot import data from excel (via csv) it is quite useless. I have read across different forums and many people seem to have troubles with the import function. Could you consider to set that straight for the next release? It can't be that complicated.

Thanks!

**Comment by dbarashev** [comment]
Please attach the contents of the log file after importing (Help->View log) and the CSV file in question.

**Comment by MHeber** [comment]
[gantt_log_file.txt](https://github.com/bardsoftware/ganttproject/files/242142/gantt_log_file.txt)
[GanttImport.txt](https://github.com/bardsoftware/ganttproject/files/242143/GanttImport.txt)

**Comment by MHeber** [comment]
Thanks for your reply, I appreciate  your help!

**Comment by dbarashev** [comment]
So the issue with this file seems to be that it uses semicolons as field delimiters. There is a field delimiter option in GanttProject settings, but for some reasons it is just ignored in GP 2.7.2 -- it always expects commas.

Commit mentioned above fixes the issue in general (will be published in GP 2.7.3). With respect to your files, try changing column delimiters to commas.
