### ISSUE TITLE
CSV DATE IMPORT BUG 

### ISSUE THREAD

**Issue by sanduke** [bardsoftware/ganttproject#1248]
[GP Prob 1.zip](https://github.com/bardsoftware/ganttproject/files/238844/GP.Prob.1.zip)

thanks!

**Comment by dbarashev** [comment]
This file imports fine with GanttProject 2.7.2 and date format set to MM/dd/yy. Please make sure that in your GanttProject date format is set to exactly this, not to "M/d/yy" (which is default for English US locale). When importing with "M/d/yy" task start dates are set to today date and there must be a warning message saying that dates can't be parsed.
![screenshot from 2016-04-27 18 05 18](https://cloud.githubusercontent.com/assets/2028330/14856896/a7088480-0ca2-11e6-9e94-3b038de4b50b.png)

**Comment by sanduke** [comment]
hi
now end date messed.
please advise.
thanks!

[image: Inline image 2]

**Comment by dbarashev** [comment]
GitHub issue tracker doesn't support attachments in replies by email. Please attach file in the web interface.

GanttProject respects holidays and creates tasks starting at the specified date and lasting for the specified duration in working days. Naturally, if your data was created assuming that there are no holidays, end dates will be different. 

You can setup holiday calendar in Project->Properties->Calendar.

**Comment by sanduke** [comment]
[Doc6.docx](https://github.com/bardsoftware/ganttproject/files/238944/Doc6.docx)

thanks!
also -  how do you set up so dates appear in Gantt Chart next to bar like you have
ps
a user manual of some sort would really be nice  :)

**Comment by dbarashev** [comment]
Edit->Settings->Gantt Chart->Task details

**Comment by sanduke** [comment]
didn't work.   
but thanks!

**Comment by dbarashev** [comment]
It does work.

**Comment by sanduke** [comment]
not for me  :)
