### ISSUE TITLE
SCREEN SHOT OF PROPER SETTINGS

### ISSUE THREAD

**Issue by sanduke** [bardsoftware/ganttproject#1249]
re #1248 -- can you send screen shots of your settings etc so i can try and find what is causing the import bug? thanks!

**Comment by dbarashev** [comment]
Dear sanduke, issue tracker is not a chat. Please consider using the same issue for the same topic.

**Comment by sanduke** [comment]
k.sorry. can you send screen shots of your settings etc so i can try and find what is causing the import bug? thanks!

**Comment by dbarashev** [comment]
Sorry, but I have already spent too much of my working time on this. Settings dialog is not that huge, you can easily explore it yourself in five minutes.
