### ISSUE TITLE
Weekend Work FOR SINGLE TASK

### ISSUE THREAD

**Issue by Bastien-D** [bardsoftware/ganttproject#1250]
Why GanttProject cant manage a single weekend override for a single task ?

It should be possible to enforce one specific task during one weekend day with no impact at all on any other task.

Deployment of new IT application version on Sunday to ensure it will not have any impact on customers does not means that all others tasks will also move forward that sunday.

**Comment by dbarashev** [comment]
> Why GanttProject cant manage a single weekend override for a single task ?

Because nobody implemented it.
Duplicates #760
