### ISSUE TITLE
all the columns are a greyed out and i can't create a customized column

### ISSUE THREAD

**Issue by jameskyeba** [bardsoftware/ganttproject#1252]
am using a a trial version of the application but it will not let me add any customised column and most of the available columns are greyed out. how do i solve this

**Comment by dbarashev** [comment]
1, There is no trial version of GanttProject.
2. I am not sure that I clearly understand what do you mean, but if you're talking about _Custom Fields Manager_ dialog then it does work. _Add Column_ adds column. _Show selected_ makes visible those columns which are selected. Columns which are currently hidden are grayed out. No surprise that most of the columns are grayed out -- they are all hidden.

**Comment by jameskyeba** [comment]
why are they hidden. can't i add my own column with my customized name?

**Comment by dbarashev** [comment]
Theyare hidden because you don't see them in the task table. Yes, you can. Use _Add column_button in the _Custom Fields Manager_dialog.
