### ISSUE TITLE
Earliest begin date change makes no effect on the chart

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1254]
I have the problem, that the date setting is **not **updated in the gantt chart. Before I got a warning, unfortunate I did not know how to save the file so it got deleted.

![setting](https://cloud.githubusercontent.com/assets/13802775/15071754/5fcd9b94-138e-11e6-90a4-3b96be227b58.PNG)

![gantt diagram](https://cloud.githubusercontent.com/assets/13802775/15071742/4c0563ee-138e-11e6-819d-191459d40bdb.PNG)

**Comment by dbarashev** [comment]
Can you explain what's wrong on the picture? Do you mean that you set earliest begin date and it is not reflected on the chart?

**Comment by xs133** [comment]
i changed the  earliest beginning date to may 30th but the ganttchart is still May 18th.

**Comment by dbarashev** [comment]
Thanks for the clarification. As a weird workaround, drawing a dependency to the task with earliest begin date makes it moving to that date.

Related: #428

**Comment by xs133** [comment]
thanks for the workaround. In the mean time I found another workaround by setting the earliest new date by typing the date directly into tasklist. It will than adjust to the earliest possible date
