### ISSUE TITLE
Project Calendar actions don't play nice with Undo/Redo stack

### ISSUE THREAD

**Issue by Kuurusch** [bardsoftware/ganttproject#1255]
Hey, I've set in some days-off a color with 50% transparency. This works fine as long I don't use the step-back-button. Then all transparency-settings were deleted.

**Comment by dbarashev** [comment]
Step-back-button? Did you mean "undo"?

**Comment by Kuurusch** [comment]
Yes, the undo Button.

Am 06.05.16 um 18:54 schrieb Dmitry Barashev:

**Comment by dbarashev** [comment]
Okay, assuming that this refers to the Project Calendar dialog (not to Chart settings,where you can also set transparency of the weekend bars), it seems that all calendar actions are not included into undo/redo stack. They should be included because they modify project file. 

Thanks for reporting!

**Comment by dbarashev** [comment]
Scenario which is even worse:
1. Create a task
2. Create a holiday
3. Click Undo: task is removed
4. Click Redo: task appears, but holiday is missing

**Comment by Kuurusch** [comment]
I've just recognised, that the transparency-settings also don't survive
a restart of GanttProject. After reopening the project, the transparency
setting are lost.

Am 10.05.16 um 15:15 schrieb Dmitry Barashev:

**Comment by dbarashev** [comment]
Thanks,created issue #1258
