### ISSUE TITLE
earlier end-date than the start date

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1256]
![date-milestones](https://cloud.githubusercontent.com/assets/13802775/15080131/f456dd42-13bc-11e6-8e2b-4a0662ce1d13.PNG)

why does the summary task of milestones becomes an earlier end-date than the start date

**Comment by dbarashev** [comment]
Where do you see this? What is shown on the picture doesn't look as GanttProject interface.

**Comment by xs133** [comment]
![date-milestones](https://cloud.githubusercontent.com/assets/13802775/15080623/66954b3a-13bf-11e6-8c2c-a57e71241559.PNG)
 here the complete picture

**Comment by dbarashev** [comment]
...and you use GanttProject version... ?

**Comment by dbarashev** [comment]
No response, closing. I suspect that you're using old GanttProject build and facing the issue described in #953. Please update your GanttProject. Feel free to reopen if you have additional information.
