### ISSUE TITLE
warnig message 

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1257]
i receive offen tthe message

![warning](https://cloud.githubusercontent.com/assets/13802775/15138652/8973e614-1691-11e6-993f-89e19c80e386.PNG)

looking into the protocoll does not tell me anything. In my  opinion warnings and errors should be more helpfull for non pramming users.

Why do I get this warning?

**Comment by dbarashev** [comment]
You get this warning because scheduler made some changes in your project when opening. They are logged. Please post the contents here of the log when you see this message.

**Comment by xs133** [comment]
you need all 25xxxx lines or can I send you the file? than which one?

**Comment by dbarashev** [comment]
The first line of the log is the name of the file where it is written to. So yes, you can send that file to contact@ganttproject.biz

**Comment by xs133** [comment]
thanks, a more user frendly warning (e.g. which dates has moved) dersiption might be an issue  for afuture release.
