### ISSUE TITLE
Can not change to an earlier date

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1273]
there are two tasks without any predecessor or any other dependency. When I now try to change the beginning date to a date earlier then  12.8.16 than the datte s set to 12.8.16.

![unbenannt](https://cloud.githubusercontent.com/assets/13802775/16276509/fcb709b4-38ae-11e6-98d4-9b39fb79432b.PNG)
anny idea?

**Comment by dbarashev** [comment]
Please share the project file.

**Comment by dbarashev** [comment]
For the record, there was a summary task above these two tasks which had a FS predecessor and predecessor finished on Jun 12.
