### ISSUE TITLE
GanttProject 2.8 not working on Mac OSX

### ISSUE THREAD

**Issue by Kuurusch** [bardsoftware/ganttproject#1285]
Hey, I've just tested the new pre-release of GanttProject 2.8 but it don't work on my Mac (OSX 10.11.5).
It says, cant open GanttProject

**Comment by dbarashev** [comment]
Did you run GanttProject.app? If yes then can you try using ZIP distro?

**Comment by hape13** [comment]
Same situation here, can't open version 2.8. What is ZIP distro, please??? Couldn't find any helpful information using google, sorry.

**Comment by dbarashev** [comment]
GP 2.8 is released and the released package for Mac OSX with signed app seems to be fine. Download it from http://ganttproject.biz/pilsen
