### ISSUE TITLE
Resource total cost

### ISSUE THREAD

**Issue by StephenAndre** [bardsoftware/ganttproject#1286]
Not a bug, but a suggestion for a future release.

I've found GanttProject to be a very useful tool.

The ability to calculate costs of individual tasks is very welcome.
Also of value would be to calculate the total costs of individual resources.
For example, many tasks may require the use of a piece of hired equipment.  By rearranging some tasks the total hire cost can be reduced.  
Some of my resources can be very expensive (Ships!)

Thanks Stephen Andre

**Comment by dbarashev** [comment]
Duplicates #1101
