### ISSUE TITLE
gtk-update-icon-cache: No theme index file. when trying to install v2.8 DEB package on Debian 8.5.

### ISSUE THREAD

**Issue by Pegasus-RPG** [bardsoftware/ganttproject#1289]
Hello. I'm just trying to install GanttProject 2.8 on Debian Jessie (8.5) and am getting the error:
gtk-update-icon-cache: No theme index file.
...during package configuration. v2.7.2 installs fine.

**Comment by Pegasus-RPG** [comment]
In case it helps, I found this page: https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html which says there is an --ignore-theme-index parameter.

**Comment by dbarashev** [comment]
Thanks for reporting!

**Comment by dbarashev** [comment]
What desktop environment are you using, by the way? Is it Gnome or something else?

**Comment by Pegasus-RPG** [comment]
KDE 4

**Comment by dbarashev** [comment]
I see, not surprising that you have no `/usr/share/icons/gnome`.  

Can you test this deb package? https://www.dropbox.com/s/fmp47gaqitvfc3e/ganttproject_2.8.1-r2018-1_all.deb?dl=0

It should skip updating gnome icons if folder is missing. Please report if you have correct file associations in KDE after installing. Expected that our icon is assigned to ".gan" files and GanttProject opens if you double-click a file in KDE UI.

**Comment by Pegasus-RPG** [comment]
Actually, I do have that folder. (Probably due to installing some GTK+ applications like The GIMP.) It just contains folders named for icon sizes.

That package installs, though I get the following warnings:
`/var/lib/dpkg/info/ganttproject.postinst: 11: [: missing ]
touch: cannot touch ‘/root/.local/share/applications/mimeapps.list’: No such file or directory
/usr/bin/xdg-mime: 781: /usr/bin/xdg-mime: cannot create /root/.local/share/applications/mimeapps.list.new: Directory nonexistent`

The file type association works, and .gan files are listed as GanttChart files, but the icon is missing. (That's fine with me though.)

**Comment by dbarashev** [comment]
Do you know by any chance how KDE associates icons and mime-types ?
