### ISSUE TITLE
Column width is not restored when reopening file

### ISSUE THREAD

**Issue by RICKinSA** [bardsoftware/ganttproject#1290]
If I adjust my column widths, and then **Save**, **close,** and **reopen**, should I see my saved column widths, or are they lost and reset each time I close the file?

I saw that this was fixed in the string, _"Column widths are not restored #422"_ in 2015.

Am I missing something?

_GanttProject 2.8 Pilsen (build 2016) (C) 2003-2016 GanttProject Team. Licensed under General Public License (GPL) version 3_

Thanks,

Rick

**Comment by dbarashev** [comment]
Seems to be a bug. Thanks for reporting!

**Comment by RICKinSA** [comment]
Hi dbarashev!
If this is closed, how long until I should see a software update?
Thanks,
Rick

**Comment by dbarashev** [comment]
We close issues only when fix becomes available. GanttProject 2.8.1 is published: http://ganttproject.blogspot.com/2016/08/ganttproject-281-maintenance-update.html

**Comment by RICKinSA** [comment]
Many thanks! Just downloaded it! The fix works perfectly.

Do you know if there is a way to generate a link from something like MS Word or OneNote which will link to a specific line in my GanttProject chart.
