### ISSUE TITLE
Keyboard command alt + up changes dates

### ISSUE THREAD

**Issue by ryanthara** [bardsoftware/ganttproject#1292]
I have a couple of tasks ("Vorgänge") and when I move them up with the keyboard or mouse, the date of  the upper task is changed to the start date of the project. Both values are changed.

After set up my project it looks like this. Take a look at the start and stop date.

<img width="307" alt="before" src="https://cloud.githubusercontent.com/assets/7117072/17338815/4655aada-58e9-11e6-836e-497b3a96230a.png">

After adding some additional tasks with cmd + T and moving them with alt + arrow up or with the mouse it will looks this way.

<img width="354" alt="after" src="https://cloud.githubusercontent.com/assets/7117072/17338814/46479d1e-58e9-11e6-84df-4cd48eb19a64.png">

Why is the date changed? Why is start and stop date changed to august, the 1st.?

**Comment by dbarashev** [comment]
I can't say that I clearly understand the issue. Please share the project file and/or describe an exact reproducible scenario.

Tasks may change their dates because of many reasons. See soem docs here: http://docs.ganttproject.biz/scheduler.html
