### ISSUE TITLE
Pilsen crashes

### ISSUE THREAD

**Issue by ryanthara** [bardsoftware/ganttproject#1293]
I try to get in touch with GanttProject and try to setup a simple project.

It crashes here under an OS X El Capitan 10.6.11 on an mbp with retina display.

Here is the new log file:

`GanttProject 2.8 Pilsen (build 2016)
Settings file:
    location: /Users/sebastian/.ganttproject
    size:4311
    is readable: true
java.class.path: /Applications/GanttProject.app/Contents/Java/Classes:/Applications/GanttProject.app/Contents/Java/eclipsito.jar
java.home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
java.ext.dirs: /Users/sebastian/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.io.tmpdir: /var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/
java.runtime.version: 1.8.0_92-b14
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.92-b14
os.arch: x86_64
os.name: Mac OS X
os.version: 10.11.6
sun.java.command: org.bardsoftware.eclipsito.Boot -app net.sourceforge.ganttproject.GanttProject -plugins-dir /Applications/GanttProject.app/Contents/Java/plugins -log true
user.country: DE
user.dir: /Users/sebastian
user.home: /Users/sebastian
user.language: de
user.timezone: Europe/Berlin

Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. changing look'n'feel ...
8. finalizing...
Main frame created
Splash closed
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:/windows/fonts is not readable
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Applications/GanttProject.app/Contents/Java/plugins/org.ganttproject.impex.htmlpdf/resource/fonts
Aug 02, 2016 8:33:14 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed
`

**Comment by ryanthara** [comment]
Very strange, but not usable. \-:

**Comment by dbarashev** [comment]
Is it a complete log? You may try removing this directory `/Applications/GanttProject.app/Contents/Java/plugins/org.ganttproject.impex.htmlpdf` just to test if the issue is with some bad font file.

**Comment by ryanthara** [comment]
This helps. No crash since then. :-)

**Comment by dbarashev** [comment]
Great. Would you mind some debugging? It involves using ZIP distro (most likely comes down to `unzip; cd; ./ganttproject`) and some spare time.

**Comment by ryanthara** [comment]
Sorry for my lack of time. I installed the new 2.8.1 version yesterday and deleted the .ganttproject file in my home folder. Everything is fine at the moment and the main window is open centered.
