### ISSUE TITLE
Week numbering is not according to ISO

### ISSUE THREAD

**Issue by robertgalambos** [bardsoftware/ganttproject#1296]
According to ISO week date handling if the first week of the year is too short then it does not counts as first week.
https://en.wikipedia.org/wiki/ISO_week_date

2016 started with Friday (1th January), therefore week 1  is 4th of January to 10th of January.
http://week-number.net/calendar-with-week-numbers-2016.html

Unfortunately even the new 2.8.1 GantProject calculates the week numbers in a wrong way, and because of this the week 4th of January to 10th of January is week 2 which is incorrect according to the ISO standard, and if you use GantProject with other tools, you can mess up the week numbering, and can cause confusion, even misplanning.

Week numbering should be corrected, or appropriate standard should be selectable.

**Comment by dbarashev** [comment]
Please read the very first entry in the FAQ: http://ganttproject.blogspot.ru/search/label/faq
and change interface language in GanttProject settings to English (United Kingdom).

**Comment by robertgalambos** [comment]
Thanks for the information. I have searched the Issue list but not the FAQ.
However it is not very intuitive this way. Also there could be a need to use e.g. French language interface, but with a US week numbering,  because you have to deal with US projects.

Maybe this feature could be separated from the language in the future, to make these kind of settings also possible. Anyway thank you for the information.

**Comment by dbarashev** [comment]
Submitted issue #1297
