### ISSUE TITLE
Changing colors, etc. of multiple tasks - Multi-edit

### ISSUE THREAD

**Issue by Tyree** [bardsoftware/ganttproject#1298]
One thing I find myself wishing for over and over is the ability to do certain function, like changing a task color, to multiple tasks at once. There are way too many things that have to be done by individually selecting each task and changing the same thing. Any way to add a multi-edit or does such a thing exist and I am missing it?

Thanks!

**Comment by dbarashev** [comment]
Duplicates #186
No, multi-edit is not supported, sorry.
