### ISSUE TITLE
MS Project export fails if task starts on "neutral" day (e.g. day after Thanksgiving with US calendar)

### ISSUE THREAD

**Issue by benjamindhill** [bardsoftware/ganttproject#1299]
[ganttproject .docx](https://github.com/bardsoftware/ganttproject/files/439827/ganttproject.docx)

contents of the log file in the attached word document.  Neither MS Project format export will work.  Stopped working earlier this morning after adding additional tasks to the project.

**Comment by dbarashev** [comment]
Can you share the project file?

**Comment by benjamindhill** [comment]
Sure, Dmitry.  Thanks for taking a look.



Regards,

Ben



Benjamin Hill

Transfigure Partners LLC

215-309-1840

ben@transfigurellc.com

https://www.linkedin.com/in/benjamindhill



Calendar: *https://calendar.google.com/calendar/embed?src=ben%40transfigurellc.com&ctz=America/New_York
<https://calendar.google.com/calendar/embed?src=ben%40transfigurellc.com&ctz=America/New_York>*



*From:* Dmitry Barashev [mailto:notifications@github.com]
*Sent:* Friday, August 26, 2016 4:06 PM
*To:* bardsoftware/ganttproject <ganttproject@noreply.github.com>
*Cc:* benjamindhill <ben@transfigurellc.com>; Author <
author@noreply.github.com>
*Subject:* Re: [bardsoftware/ganttproject] Unable to export MS Project
compatible formats (#1299)



Can you share the project file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bardsoftware/ganttproject/issues/1299#issuecomment-242837710>,
or mute the thread

**Comment by dbarashev** [comment]
I don't know if you attached a file to your email, but if you did, please attach it to the issue through the web interface. Issue tracker on GitHub doesn't support email attachments.

**Comment by benjamindhill** [comment]
[implementation_plan.zip](https://github.com/bardsoftware/ganttproject/files/442439/implementation_plan.zip)

**Comment by benjamindhill** [comment]
Thank you for taking a look, Dmitry!

**Comment by dbarashev** [comment]
Thanks for the project file. Apparently export fails when task starts on a day which is marked as "Neutral" in the project calendar -- in your case it is day after thanksgiving. This is a severe issue, we'll fix it soon.

**Comment by dbarashev** [comment]
@benjamindhill You can download build 2027 which fixes this bug from our Dropbox:
https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0

It is 2.8.1 + this bugfix. 2.8.2 release may be slightly different from this build.

**Comment by benjamindhill** [comment]
Thank you, that fixed my problem.



Regards,

Ben



Benjamin Hill

Transfigure Partners LLC

215-309-1840

ben@transfigurellc.com

https://www.linkedin.com/in/benjamindhill



Calendar: *https://calendar.google.com/calendar/embed?src=ben%40transfigurellc.com&ctz=America/New_York
<https://calendar.google.com/calendar/embed?src=ben%40transfigurellc.com&ctz=America/New_York>*



*From:* Dmitry Barashev [mailto:notifications@github.com]
*Sent:* Monday, August 29, 2016 8:06 PM
*To:* bardsoftware/ganttproject <ganttproject@noreply.github.com>
*Cc:* benjamindhill <ben@transfigurellc.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [bardsoftware/ganttproject] MS Project export fails if task
starts on "neutral" day (e.g. day after Thanksgiving with US calendar)
(#1299)



@benjamindhill <https://github.com/benjamindhill> You can download build
2027 which fixes this bug from our Dropbox:
https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0

It is 2.8.1 + this bugfix. 2.8.2 release may be slightly different from
this build.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bardsoftware/ganttproject/issues/1299#issuecomment-243294875>,
or mute the thread
