### ISSUE TITLE
Application screen is displayed scrambled and shifts when mouse moves

### ISSUE THREAD

**Issue by andre-lima** [bardsoftware/ganttproject#1301]
I'm running GanttProject on Win10, on a 2 monitor setup.

After a few minutes of use, the screen gets scrambled. Parts of the application menus or areas gets mixed up. Once I move the window to the other monitor, the issue is fixed for a few moments.

No error is displayed, and once I close the application and open it again, the issue is fixed for a few minutes.

The issues didn't occurs before updating from win8 to win10.

Please see screenshots for more information.

![bug_01](https://cloud.githubusercontent.com/assets/11011917/18097262/3f021886-6eab-11e6-81b5-a52f663cba53.PNG)
![bug_02](https://cloud.githubusercontent.com/assets/11011917/18097261/3eff93a4-6eab-11e6-8fa8-69478a641640.PNG)

**Comment by dbarashev** [comment]
Please post the contents of the log file when it happens. Help->View log or open ganttproject.log from your home directory.

**Comment by andre-lima** [comment]
Here it is:

C:\Users\adantas\ganttproject.log

GanttProject 2.8.1 Pilsen (build 2024)
Settings file:
	location: C:\Users\adantas\.ganttproject
	size:5289
	is readable: true
java.class.path: eclipsito.jar;.
java.home: C:\Program Files\Java\jdk1.8.0_92\jre
java.ext.dirs: C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\adantas\AppData\Local\Temp\
java.runtime.version: 1.8.0_92-b14
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.92-b14
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true
user.country: US
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\adantas
user.language: en
user.timezone: America/Indianapolis

Aug 30, 2016 1:00:40 PM net.sourceforge.ganttproject.GPLogger log
INFO: Options file:C:\Users\adantas\.ganttproject
Aug 30, 2016 1:00:41 PM net.sourceforge.ganttproject.GPLogger log
INFO: Waiting until main window closes
Aug 30, 2016 1:00:41 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Aug 30, 2016 1:00:42 PM net.sourceforge.ganttproject.GPLogger log
INFO: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
8. finalizing...
Main frame created
Aug 30, 2016 1:00:42 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after setVisible: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Splash closed
Resizing window...
Aug 30, 2016 1:00:42 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after opening: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Aug 30, 2016 1:00:42 PM net.sourceforge.ganttproject.GPLogger log
INFO: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Aug 30, 2016 1:00:50 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories...
Aug 30, 2016 1:00:50 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:\Program Files\Java\jdk1.8.0_92\jre/lib/fonts
Aug 30, 2016 1:00:50 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:/windows/fonts
Aug 30, 2016 1:00:52 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/usr/share/fonts/truetype
Aug 30, 2016 1:00:52 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /usr/share/fonts/truetype is not readable
Aug 30, 2016 1:00:52 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/System/Library/Fonts
Aug 30, 2016 1:00:52 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /System/Library/Fonts is not readable
Aug 30, 2016 1:00:52 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins/org.ganttproject.impex.htmlpdf/resource/fonts
Aug 30, 2016 1:00:52 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories completed
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Aug 30, 2016 1:04:46 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Transaction is already running
java.lang.IllegalStateException: Transaction is already running
	at net.sourceforge.ganttproject.AbstractChartImplementation$ChartSelectionImpl.startCopyClipboardTransaction(AbstractChartImplementation.java:505)
	at net.sourceforge.ganttproject.chart.gantt.GanttChartSelection.startCopyClipboardTransaction(GanttChartSelection.java:77)
	at net.sourceforge.ganttproject.action.edit.CopyAction.actionPerformed(CopyAction.java:37)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JTable.processKeyBinding(JTable.java:5259)
	at net.sourceforge.ganttproject.GPTreeTableBase.processKeyBinding(GPTreeTableBase.java:427)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dbarashev** [comment]
This log says that it failed to complete copy action. Did you hit Ctrl+C at this moment?

**Comment by andre-lima** [comment]
I managed to get the same log by hitting ctrl+c but it didn't cause the main issue.
Later, I managed to have the issue happen without hitting ctrl+c. So the issue is not caused by the ctrl+c.
Here's the new log:

C:\Users\adantas\ganttproject.log

GanttProject 2.8.1 Pilsen (build 2024)
Settings file:
	location: C:\Users\adantas\.ganttproject
	size:5289
	is readable: true
java.class.path: eclipsito.jar;.
java.home: C:\Program Files\Java\jdk1.8.0_92\jre
java.ext.dirs: C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\adantas\AppData\Local\Temp\
java.runtime.version: 1.8.0_92-b14
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.92-b14
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true
user.country: US
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\adantas
user.language: en
user.timezone: America/Indianapolis

Aug 30, 2016 2:00:35 PM net.sourceforge.ganttproject.GPLogger log
INFO: Options file:C:\Users\adantas\.ganttproject
Aug 30, 2016 2:00:36 PM net.sourceforge.ganttproject.GPLogger log
INFO: Waiting until main window closes
Aug 30, 2016 2:00:36 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Aug 30, 2016 2:00:36 PM net.sourceforge.ganttproject.GPLogger log
INFO: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
8. finalizing...
Main frame created
Aug 30, 2016 2:00:36 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after setVisible: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Splash closed
Resizing window...
Aug 30, 2016 2:00:36 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after opening: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Aug 30, 2016 2:00:36 PM net.sourceforge.ganttproject.GPLogger log
INFO: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Aug 30, 2016 2:00:45 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories...
Aug 30, 2016 2:00:45 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:\Program Files\Java\jdk1.8.0_92\jre/lib/fonts
Aug 30, 2016 2:00:45 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:/windows/fonts
Aug 30, 2016 2:00:47 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/usr/share/fonts/truetype
Aug 30, 2016 2:00:47 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /usr/share/fonts/truetype is not readable
Aug 30, 2016 2:00:47 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/System/Library/Fonts
Aug 30, 2016 2:00:47 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /System/Library/Fonts is not readable
Aug 30, 2016 2:00:47 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins/org.ganttproject.impex.htmlpdf/resource/fonts
Aug 30, 2016 2:00:47 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories completed

**Comment by andre-lima** [comment]
I managed to reproduce it 100% of the time with these steps:
1) Launch application
2) Create a task
3) Open TASK PROPERTIES for this new task
4) Hover the mouse over the OK or CANCEL button for 2 seconds.
(The issue starts to occurs)
5) Close TASK PROPERTIES and move mouse cursor around the application screen
(Issue occurs more strongly)

**Comment by dbarashev** [comment]
Is it reproducible 
- with 1 monitor? 
- with other Appearance (e.g. Plastic) ?
- with updated java Runtime (update 102 is the latest one)?

**Comment by andre-lima** [comment]
Tried all 3 (although i could only get Java update 101) and the issue still occured everytime.

**Comment by dbarashev** [comment]
Can you install ZIP distro and see if there is anything suspicious printed in the console when it starts misbehaving? Also, with ZIP distro try removing `plugins/org.ganttproject.impex.htmlpdf` folder.

Instructions: https://github.com/bardsoftware/ganttproject/wiki/Installing-from-ZIP

**Comment by andre-lima** [comment]
How can I get this ZIP file?
I'll try it tomorrow.

**Comment by dbarashev** [comment]
http://www.ganttproject.biz/download

**Comment by andre-lima** [comment]
Bug still happens. No apparent changes when launching from ZIP distro:

C:\Users\adantas\ganttproject.log

GanttProject 2.8.1 Pilsen (build 2024)
Settings file:
	location: C:\Users\adantas\.ganttproject
	size:5360
	is readable: true
java.class.path: .;;.\eclipsito.jar;.
java.home: C:\Program Files\Java\jdk1.8.0_92\jre
java.ext.dirs: C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\adantas\AppData\Local\Temp\
java.runtime.version: 1.8.0_92-b14
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.92-b14
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true
user.country: US
user.dir: C:\Users\adantas\Desktop\ganttproject-2.8.1-r2024
user.home: C:\Users\adantas
user.language: en
user.timezone: America/Indianapolis

Aug 31, 2016 9:30:25 AM net.sourceforge.ganttproject.GPLogger log
INFO: Options file:C:\Users\adantas\.ganttproject
Aug 31, 2016 9:30:26 AM net.sourceforge.ganttproject.GPLogger log
INFO: Waiting until main window closes
Aug 31, 2016 9:30:26 AM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Aug 31, 2016 9:30:27 AM net.sourceforge.ganttproject.GPLogger log
INFO: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
8. finalizing...
Main frame created
Aug 31, 2016 9:30:27 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after setVisible: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Splash closed
Resizing window...
Aug 31, 2016 9:30:27 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after opening: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Aug 31, 2016 9:30:27 AM net.sourceforge.ganttproject.GPLogger log
INFO: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]

**Comment by andre-lima** [comment]
I'm not a Java expert, but maybe this can help:
http://arstechnica.com/civis/viewtopic.php?t=328654

**Comment by dbarashev** [comment]
Thanks for the link. However, you issue is not reproducible on my windows 10, neither with 1 monitor, nor with two, and I am almost sure it is not reproducible on thousands of other Windows 10 around the world. That's why I am trying to figure out what's wrong with *your* system. There is no easy ready solution on the internets.

**Comment by dbarashev** [comment]
Can you try any other Java app (e.g. FreeMind) and older versions of GanttProject, e.g.  GP 2.7.2 or 2.6.6? Will they have similar issues?

**Comment by andre-lima** [comment]
FreeMind works.
GP 2.7.2 doesn't.
How can I get 2.6.6? I couldn't find the link on your page.
Thanks.

**Comment by dbarashev** [comment]
http://www.ganttproject.biz/brno

**Comment by dbarashev** [comment]
Can you try this trick: open ganttproject.bat in any text editor and add this line 
```
SET J2D_D3D=false
```

in any place at the top (e.g. just after the first `@echo off` line)

**Comment by andre-lima** [comment]
Yes!
2.6.6 didn't work but the _SET J2D_D3D=false_ thing did.
Thanks a lot.

Is there any change this will be fixed for me on future versions?

**Comment by dbarashev** [comment]
Yes, we'll add this to the launchers. Thanks for the help!

**Comment by maxwailou** [comment]
Hello, I'm a french user of Ganttproject with also windows 10 and same problems of scrambling when mouse mouve. 

I have sometimes some similar problems with FreeMind.

I've tried to fix the problem with editing Ganttproject.bat file and it's ok... maybe transmit the same report bug for freemind will be cool.
