### ISSUE TITLE
Can't see the project

### ISSUE THREAD

**Issue by rutileD** [bardsoftware/ganttproject#1302]
I've used ganttproject for some time, but now can't see the project.  Menu bar appears fine.  Ive downloaded the new version, checked Java version - all fine, but still can't see anything other than the menu bar.  Running on a macbook with El Capitan.

**Comment by dbarashev** [comment]
Hello, do you mean that application window is not visible on the screen? 

if it is not sitting somewhere at the screen endge with minimized size (see issue #1291 ) then try removing file `.ganttproject` from your home directory (typing `rm ~/.ganttproject` in the Terminal will do the trick). This will reset **all** settings to default, including position on the screen which might be somewhere outside of the screen area at the moment.

**Comment by rutileD** [comment]
Removing in home directory did the trick

Many thanks
