### ISSUE TITLE
Position dialogs so that they were visible in dual monitor setup

### ISSUE THREAD

**Issue by dsanguinetti** [bardsoftware/ganttproject#1305]
When I use Ganttproject (version 2.8) in my second monitor it tries to open dialog boxes on my laptop screen. Unfortunately my laptop screen is smaller, and the boxes open at a level near the top of the second screen, meaning that for the larger boxes the bottom is low enough that I can grab the corner and pull them across, but the smaller ones disappear, and the only solution I've found is to force the program to close and re-start. Is there a way to get the dialog boxes to appear where I can see them?

**Comment by dbarashev** [comment]
Thanks for reminding (in addition to #1304)
