### ISSUE TITLE
New empty project asks for saving

### ISSUE THREAD

**Issue by EdvinX** [bardsoftware/ganttproject#1310]
Right after GP 2.8.1 is started, a *(star) appears next to the window title (same way like you do any changes to the project), so before I can open any other project file, GP asks if I want to save changes in current project (which I didn't do any any changes to).

**Comment by dbarashev** [comment]
Are you on Mac OSX by any chance?

**Comment by EdvinX** [comment]
I faced this issue on 2 machines with Win7 Pro and Win7 Ent.

**Comment by GusevVictor** [comment]
I can confirm that. There is no problem on Windows 10, but Windows 7 only.

**Comment by dbarashev** [comment]
Can you please try if this is reproducible in 2.8.4 (released just an hour ago) ?

**Comment by GusevVictor** [comment]
Oooo YES, il looks like fixed. THANK a lot for you. I have wait for it about 1year.
