### ISSUE TITLE
Properties disabled for summary task remain disabled for child tasks

### ISSUE THREAD

**Issue by eeffoc** [bardsoftware/ganttproject#1311]
Unable to change the `Begin Date` of a task which is located in a Project Task (Indented). This bug occurs after going into properties of a Project Task. After closing the properties and opening properties of a task which is inside a project task the scheduling options `start date is calculated` and `duration is calculated` is checked although I never selected `start date is calculated`. Checking the option box `Milestone` (in the task) and then unchecking it fixes the issue and allows to enter the begin date as well as `start date is calculated` is unchecked. 

This bug can be re-created and happens to any tasks which are indented in a project task, you cannot edit the start date for any of them until checking + unchecking the `milestone` checkbox on any of the tasks inside the project.

Let me know if you need screenshots.

**Comment by dbarashev** [comment]
Thanks for reporting!
