### ISSUE TITLE
ganttproject-2.8.1-r2024 error could not open jvm.cfg

### ISSUE THREAD

**Issue by Southwick** [bardsoftware/ganttproject#1312]
I have used Gantt Project in the past. I'm now getting an error:
Java Virtual machine Launcher
Error: Could not open `C:Program Files(x86)\Java\jre1.8.0_60\lib\i386\jvm.cfg'.

I reinstalled and had the same issue.

**Comment by dbarashev** [comment]
It seems that your Java launcher (program which sits in the system path) is not in sync with your JRE installation.  Installing the latest Java runtime should help.
