### ISSUE TITLE
Error When Closing down Ganttproject

### ISSUE THREAD

**Issue by AdamPa** [bardsoftware/ganttproject#1313]
When attempting to close down Ganttproject, the gantt chart i had been working on disappears and a something went wrong error appears. This behavior also happens when trying to undo.
![1](https://cloud.githubusercontent.com/assets/22959046/19560360/19f536e2-96cc-11e6-894c-199c88e2f152.png)

**Comment by dbarashev** [comment]
... and what is written in the log?
