### ISSUE TITLE
Earliest start date on a weekend makes task jump around

### ISSUE THREAD

**Issue by MisterCreosote** [bardsoftware/ganttproject#1315]
I have a task with an earliest start date of Dec 4th of this year (Sunday). Since it is a non-work day on my calendar, I assumed it would just advance the start of the task to the next Monday. 

When I open and close task edit windows, for this or any other task, the task in question jumps back and forth on the calendar view from starting the previous friday or the following monday from the date I picked. 

Picking a earliest start date that does not fall on a weekend fixes the issue.

**Comment by dbarashev** [comment]
Do you mean that you see some sort of animation on the chart?

**Comment by MisterCreosote** [comment]
There was no animation.
I would edit some other event and save it then the task in question would
move a day later. after editing some other task and saving it, the task in
question would move back a day.

**Comment by dbarashev** [comment]
Okay, thanks for the explanation.

For the record, reproducible scenario:

1. Create a new task `Task1` and set its earliest start to weekend day (e.g. Dec 4, Sunday). Initially it is correctly scheduled to start on Dec 5.
1. Start inserting other tasks using `Insert` key. Every odd time `Task1` jumps to Dec 2 and every even time it returns back to Dec 5.
