### ISSUE TITLE
Import/Export to CSV - Missing RESOURCE UNIT field

### ISSUE THREAD

**Issue by lukeit75** [bardsoftware/ganttproject#1319]
Hi all,

The CSV file generated by GanttProject is missing of the "Resource Unit" field and consequentally in the import procedure.
This field, which should be specified for each activity (ex 100%), is extremely important to allow GanttProject to visualize the load for the imported resources and highlight overlapping.

Please fix this

Regards
Luca

**Comment by dbarashev** [comment]
Duplicates #274
