### ISSUE TITLE
Receive Java error and reinstalled GanttProject; stil get same error

### ISSUE THREAD

**Issue by Southwick** [bardsoftware/ganttproject#1321]
After installing ganttproject-2.8.1-r2024, and attempting to run the program I receive the error:

Java Virtual Machine Launcher
Error: could not open 'C:\Program Files(x86)\Java\jre1.9.0_60\lib\i386\jvm.cfg.'

Java version seems ok. It looks like a file location issue.

C:\Users\rdarling>java -version
java version "1.8.0_111"

GantProject seems to be looking fo version jre1.9.0; which hasn't been released. 

Any thoughts?

**Comment by dbarashev** [comment]
Please check if you have JAVA_HOME environment variable set to that path.
