### ISSUE TITLE
Hide milestones from Timeline

### ISSUE THREAD

**Issue by Vinz87** [bardsoftware/ganttproject#1322]
I would like to be able to select which milestones appear in the Timeline with a label and which not.
Currently, if I check the "milestone" checkbox, it always appears its label in the Timeline, whether or not the checkbox "show in timeline" is checked.

**Comment by dbarashev** [comment]
`Edit`.`Settings`.`Gantt Chart`.`Timeline labels`. Uncheck `Show all milestones`.
