### ISSUE TITLE
Crash when pasting tasks from the clipboard

### ISSUE THREAD

**Issue by ryanthara** [bardsoftware/ganttproject#1324]
There are a couple of crashes this morning with the last version of Pilsen.

The information from the java.log file:

`INFORMATION: Scanning font directories completed
Nov 28, 2016 6:39:17 AM net.sourceforge.ganttproject.GPLogger logToLogger
WARNUNG: null
java.lang.NullPointerException
	at net.sourceforge.ganttproject.chart.gantt.ClipboardTaskProcessor.pasteAsChild(ClipboardTaskProcessor.java:65)
	at net.sourceforge.ganttproject.chart.gantt.ClipboardTaskProcessor.pasteAsSibling(ClipboardTaskProcessor.java:57)
	at net.sourceforge.ganttproject.chart.gantt.GanttChartSelection.paste(GanttChartSelection.java:102)
	at net.sourceforge.ganttproject.chart.gantt.GanttChartController.paste(GanttChartController.java:216)
	at net.sourceforge.ganttproject.ChartComponentBase.paste(ChartComponentBase.java:174)
	at net.sourceforge.ganttproject.action.edit.PasteAction$1.run(PasteAction.java:56)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.action.edit.PasteAction.actionPerformed(PasteAction.java:52)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Nov 28, 2016 6:39:24 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: [GanttOptions] save(): finished!!
Nov 28, 2016 6:39:24 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Main window has closed
Nov 28, 2016 6:39:24 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Program terminated
Nov 28, 2016 6:39:24 AM org.bardsoftware.impl.eclipsito.BootImpl shutdown
INFORMATION: Eclipsito platform is shut down.
Nov 28, 2016 6:42:04 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:/Users/sebastian/.ganttproject
Nov 28, 2016 6:42:05 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Nov 28, 2016 6:42:05 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Nov 28, 2016 6:42:07 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:07 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:07 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:07 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:13 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Nov 28, 2016 6:42:13 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Nov 28, 2016 6:42:14 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Nov 28, 2016 6:42:14 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:/windows/fonts is not readable
Nov 28, 2016 6:42:14 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Nov 28, 2016 6:42:14 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Nov 28, 2016 6:42:14 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Nov 28, 2016 6:42:16 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: [GanttOptions] save(): finished!!
Nov 28, 2016 6:42:16 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Main window has closed
Nov 28, 2016 6:42:16 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Program terminated
Nov 28, 2016 6:42:16 AM org.bardsoftware.impl.eclipsito.BootImpl shutdown
INFORMATION: Eclipsito platform is shut down.
Nov 28, 2016 6:42:29 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:/Users/sebastian/.ganttproject
Nov 28, 2016 6:42:30 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Nov 28, 2016 6:42:30 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Nov 28, 2016 6:42:32 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:32 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:32 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:32 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 6:42:39 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Nov 28, 2016 6:42:39 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Nov 28, 2016 6:42:39 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Nov 28, 2016 6:42:39 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:/windows/fonts is not readable
Nov 28, 2016 6:42:39 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Nov 28, 2016 6:42:39 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Nov 28, 2016 6:42:39 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Nov 28, 2016 6:42:43 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/private/var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/AppTranslocation/AD4A5157-1FA6-4482-A931-8CA3A0A518D5/d/GanttProject.app/Contents/Java/plugins/org.ganttproject.impex.htmlpdf/resource/fonts
`

And from the ganttproject.log file

`GanttProject 2.8.1 Pilsen (build 2024)
Settings file:
	location: /Users/sebastian/.ganttproject
	size:4078
	is readable: true
java.class.path: /private/var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/AppTranslocation/82AC44F6-AC0F-447B-8EAC-617781590EBE/d/GanttProject.app/Contents/Java/Classes:/private/var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/AppTranslocation/82AC44F6-AC0F-447B-8EAC-617781590EBE/d/GanttProject.app/Contents/Java/eclipsito.jar
java.home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
java.ext.dirs: /Users/sebastian/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.io.tmpdir: /var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/
java.runtime.version: 1.8.0_111-b14
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.111-b14
os.arch: x86_64
os.name: Mac OS X
os.version: 10.12.1
sun.java.command: org.bardsoftware.eclipsito.Boot -app net.sourceforge.ganttproject.GanttProject -plugins-dir /private/var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/AppTranslocation/82AC44F6-AC0F-447B-8EAC-617781590EBE/d/GanttProject.app/Contents/Java/plugins -log true
user.country: DE
user.dir: /Users/sebastian
user.home: /Users/sebastian
user.language: de
user.timezone: Europe/Berlin

Nov 28, 2016 11:28:27 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:/Users/sebastian/.ganttproject
Nov 28, 2016 11:28:28 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Nov 28, 2016 11:28:28 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Nov 28, 2016 11:28:31 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
8. finalizing...
Main frame created
Nov 28, 2016 11:28:31 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Splash closed
Resizing window...
Nov 28, 2016 11:28:31 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 11:28:31 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Nov 28, 2016 11:28:37 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Nov 28, 2016 11:28:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Nov 28, 2016 11:28:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Nov 28, 2016 11:28:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:/windows/fonts is not readable
Nov 28, 2016 11:28:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Nov 28, 2016 11:28:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Nov 28, 2016 11:28:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Nov 28, 2016 11:28:40 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/private/var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/AppTranslocation/82AC44F6-AC0F-447B-8EAC-617781590EBE/d/GanttProject.app/Contents/Java/plugins/org.ganttproject.impex.htmlpdf/resource/fonts
Nov 28, 2016 11:28:40 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
`

**Comment by dbarashev** [comment]
Do you know any reproducible scenario?

**Comment by ryanthara** [comment]
Not at least. But I was wondering about the fact, that ganttproject tries to read directory C:/windows/fonts, which is not available on a macOS system. Maybe it would be better to ask for the system instead of try to read it.

**Comment by dbarashev** [comment]
I am actually asking about the first stack trace which clearly was produced after some paste action. The second excerpt from the log is either incomplete or doesn't indicate any issues (reading C:/windows/fonts is okay).

**Comment by ryanthara** [comment]
I can’t remember which paste action was done.

**Comment by dbarashev** [comment]
Most likely you pasted tasks from other instance of GanttProject, at least, that's the way of reproducing this issue.

**Comment by ryanthara** [comment]
I think you are right. I had two instances opened at the same time.
