### ISSUE TITLE
new plan corrupted after importing resources from plan created in old (2.7.x) ganttproject

### ISSUE THREAD

**Issue by andrews812** [bardsoftware/ganttproject#1325]
Hello!

I've got a sad issue with a plan file corruption. Below is a scenario:
1. I've created a plan in new Ganttproject (2.8.1).
2. I've imported resources from the plan created in the Ganttproject 2.7.x
3. After saving results i've tried to close application window but instead got an error "Something went wrong". I've repeated infinite times but results are same.
4. I've killed applicaion by sending SIGTERM from the shell. It then closed.
5. I've opened app again and loaded the plan but my task list became empty. The game is over :(. 

The app windown still do not want to close and pop ups same error. 
The corrupted file in the attachment.

[plan.gan.gz](https://github.com/bardsoftware/ganttproject/files/624337/plan.gan.gz)

**Comment by dbarashev** [comment]
Hello,
there are duplicate resource ids in this file, both having id=0. Action `Resources`.`Import Resources...` won't check duplicate resources. Actually, that action is deprecated and we will remove it in the next update. We recommend using `Import`.`GanttProject files` to import resources from one file into another. That way you can specify how to merge resources from two files.
