### ISSUE TITLE
Gantt failed to save properly / Allocation on ... could not be saved

### ISSUE THREAD

**Issue by FGKD** [bardsoftware/ganttproject#1326]
Repro:

- Create new Redmine Ticket "Test Allocation"
  - Set "Begin" Date in the past
  - Set "End" Date in the future
  - Assign to yourself
  - Create
- Open Resource Management
  - All days now show "0" as allocated hours
  - Double click the first day (which lies in the past), and enter a "1"
  - The second day will now show a "-1". This is inconvenient but understandable.
  - Press "Save"

Error Message:

---------------------------------------------------------------------------------------

**Gantt failed to save properly**

**Errors:**
-  Allocation on #5019 for [User] at 2016-11-29 with value 1h could not be saved
-  Allocation on #5019 for [User] at 2016-11-30 with value -1h could not be saved
-  Allocation on #5019 for [User] at 2016-12-01 with value 0h could not be saved
-  Allocation on #5019 for [User] at 2016-12-02 with value 0h could not be saved
-  Allocation on #5019 for [User] at 2016-12-03 with value 0h could not be saved
-  Allocation on #5019 for [User] at 2016-12-04 with value 0h could not be saved

Do you want to ignore unsaved items and reload data from server?

**Yes | No**

---------------------------------------------------------------------------------------

After selecting "Yes", the form reloads and everything was saved correctly. The Error list shows one error for each day of the task, which can get quite long each time you click "Save".

**Comment by dbarashev** [comment]
Are you sure you didn't chose a wrong window in the browser? It is GanttProject, not Redmine.
