### ISSUE TITLE
The number of week in Spanish is not correct.

### ISSUE THREAD

**Issue by CristianDICORISM** [bardsoftware/ganttproject#1327]
I am using the program in the Spanish language.
I find that the week number is not correct.
The year 2016, week 1, begins on 12/29/2016 and has to start on 04/01/2016.
For the year 2017, the program begins on 12/26/2016 and should begin on 02/01/2017.

Is there a way to solve this?

Thank you very much

**Comment by dbarashev** [comment]
Pls see the FAQ: http://ganttproject.blogspot.ru/2009/03/ganttproject-faq.html

**Comment by CristianDICORISM** [comment]
But in Spain there is a dialect that is in Catalan and this is correct.
Spanish:
![imagen](https://cloud.githubusercontent.com/assets/24390645/20889998/87bb3d36-bb05-11e6-984b-86978c662710.png)
Catalan:
![imagen](https://cloud.githubusercontent.com/assets/24390645/20890021/a206e7bc-bb05-11e6-8470-a0633e1269ac.png)

**Comment by dbarashev** [comment]
So you're using Spanish interface, not English? Sad that this works so weird. This might be a bug in the Java Runtime (not sure if it really is). Anyway, there is enhancement request #1297 which requires week numbering to be configured separately from the language choice, so we'll probably fix it some time soon,

**Comment by CristianDICORISM** [comment]
Good afternoon,
Do you have any idea how to solve it?
Thank you very much

**Comment by dbarashev** [comment]
At the moment being, you can switch to English (United Kingdom) interface language/

**Comment by CristianDICORISM** [comment]
I, I have solved temporarily, half.
In the direction
\GanttProject-2.8\plugins\net.sourceforge.ganttproject\data\resources\language
I copied the file: i18n_es (Spanish language) And I've changed the name to: i18n_ca (Catalan language):
![imagen](https://cloud.githubusercontent.com/assets/24390645/21356765/14157ec6-c6d3-11e6-894d-6fa3e4ef575b.png)
In the Ganttproject I have put the language into Catalan.
The result has been satisfactory, less the months:
![imagen](https://cloud.githubusercontent.com/assets/24390645/21357006/fdbb80fc-c6d3-11e6-99cd-a1bab63bd9ab.png)
As you can see, week 1 starts on January 2 and everything is translated into Spanish which is what I am looking for.
But the months continue in Catalan.

I do not know if you have a solution to change the months.

So the problem would be solved temporarily

Thank you very much
