### ISSUE TITLE
Updated versions of calendars

### ISSUE THREAD

**Issue by nmilet** [bardsoftware/ganttproject#1329]
Hi,

I'm preparing my planning for next year and discover that the calendars you're proposing for bank holidays are finishing in 2016... I'm using GanttProject V2.8.1.

Is there any chance that you will provide new dates for years to come?

Many thanks for your support, I adore your tool :)

Nicolas

**Comment by dbarashev** [comment]
Yes, we plan to release 2.8.2 with updated calendars soon.
