### ISSUE TITLE
Task selection may not work properly

### ISSUE THREAD

**Issue by bits-bytes** [bardsoftware/ganttproject#1332]
Hi
using V2.8.1 (Build 2024) - but also with earlier versions) I have amazing problems with selection of tasks. The GUI shows me a task selected, but another one is selected.

I select a task and I move it up / down: no, it is not moving the selected, but another one.
I select a task and I delete it: no, it is deleting another one.

This is really a very bad situation for me, from version to version I was hoping it would be fixed, but it is always the same.... 

Thank you BR
Manfred

**Comment by dbarashev** [comment]
Please share a sample project and exact scenario of reproducing this issue. The contents of the whole log after reproducing could also be useful.

**Comment by dbarashev** [comment]
Ping? If you really suffer from this issue please give us more information. Selection works fine in all my tests and, apparently, I am not alone, otherwise we would have seen lots of similar bug reports. So there must be something in your environment which breaks this function and we can't find out the root cause without your help.

Thanks.

**Comment by bits-bytes** [comment]
Hi
I have a problem because it is in no way reproducable. It just happens so many times after I was changing and / or creating something. Short time after start work in Gantproject. But never found a ‘path’ to the problem. Suddenly starts….

I tried this on a new file with less data, but also could not have the error. So it may have a link to ‘big’ files or even only to my file ?

This answer is published in github ?

Can I send my file to another address ? I definitely don’t want my file public!! Can you guarantee this ?

Thank you for understanding
Manfred


Von: Dmitry Barashev [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. Jänner 2017 15:31
An: bardsoftware/ganttproject
Cc: Strasser Manfred; Author
Betreff: Re: [bardsoftware/ganttproject] Task ('Vorgang') selection just does not work (#1332)


Ping? If you really suffer from this issue please give us more information. Selection works fine in all my tests and, apparently, I am not alone, otherwise we would have seen lots of similar bug reports. So there must be something in your environment which breaks this function and we can't find out the root cause without your help.

Thanks.

**Comment by bits-bytes** [comment]
Where can I find log-files of ganttproject

Von: Strasser Manfred
Gesendet: Mittwoch, 25. Jänner 2017 16:30
An: bardsoftware/ganttproject; bardsoftware/ganttproject
Betreff: AW: [bardsoftware/ganttproject] Task ('Vorgang') selection just does not work (#1332)

Hi
I have a problem because it is in no way reproducable. It just happens so many times after I was changing and / or creating something. Short time after start work in Gantproject. But never found a ‘path’ to the problem. Suddenly starts….

I tried this on a new file with less data, but also could not have the error. So it may have a link to ‘big’ files or even only to my file ?

This answer is published in github ?

Can I send my file to another address ? I definitely don’t want my file public!! Can you guarantee this ?

Thank you for understanding
Manfred


Von: Dmitry Barashev [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. Jänner 2017 15:31
An: bardsoftware/ganttproject
Cc: Strasser Manfred; Author
Betreff: Re: [bardsoftware/ganttproject] Task ('Vorgang') selection just does not work (#1332)


Ping? If you really suffer from this issue please give us more information. Selection works fine in all my tests and, apparently, I am not alone, otherwise we would have seen lots of similar bug reports. So there must be something in your environment which breaks this function and we can't find out the root cause without your help.

Thanks.

**Comment by dbarashev** [comment]
You can view log with `Help`.`View log` menu. If you don't want to make the file public, send it to `contact@ganttproject.biz`. We will keep it confidential. However, if the issue is not reproducible straightforward, we will still need at least approximate scenario.

**Comment by bits-bytes** [comment]
OK,
I will send you the information as soon as I have the problem again. And I try to remember what I did ☺

Von: Dmitry Barashev [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. Jänner 2017 16:37
An: bardsoftware/ganttproject
Cc: Strasser Manfred; Author
Betreff: Re: [bardsoftware/ganttproject] Task selection may not work properly (#1332)


You can view log with Help.View log menu. If you don't want to make the file public, send it to contact@ganttproject.biz<mailto:contact@ganttproject.biz>. We will keep it confidential. However, if the issue is not reproducible straightforward, we will still need at least approximate scenario.
