### ISSUE TITLE
Importing Microsoft Project .mpp dates form tasks are changing unpredicatebly

### ISSUE THREAD

**Issue by jfonline03** [bardsoftware/ganttproject#1333]
[MS Project 2007 MPP Import into GanttProject v2.8.1.zip](https://github.com/bardsoftware/ganttproject/files/719501/MS.Project.2007.MPP.Import.into.GanttProject.v2.8.1.zip)
[MS Project 2016 MPP Import into GanttProject v2.8.1.zip](https://github.com/bardsoftware/ganttproject/files/719502/MS.Project.2016.MPP.Import.into.GanttProject.v2.8.1.zip)

Refer to the ZIP files noted above which contain the source MPP file, the log files from the import and images showing the source MPP tasks and dates side-by-side with those in GanttProject. Regardless of which of the following Project calendar options is choosen during the import (leave existing, replace existing, or merge both) all three cause the various tasks to change unpredictably. I do not understand why this is, in particular with "leave existing" why is the program changing any dates? Thinking it may be possibly be a version issue I have tried it with both 2007 and 2016 MS Project files. Please advise ASAP if this a software issue or something I am doing wrong during the import.

**Comment by dbarashev** [comment]
Hello,
I am on vacation now and can't dive into the details, but what I see in the log looks as if all tasks under Mechanical Model moved slightly to the right. It may mean that there is a dependency which shifted Mechanical Model task as a whole. Can you share the charts so that dependencies were visible?

**Comment by jfonline03** [comment]
Thanks for taking a look. See image for reference. It appears to be changing the Finish date for line item 3 "Prep Work Layout" from 1/28/17 to 1/30/17, which is then throwing off all the subsequent dates. Why would it do this? Does GanttProject not support work activities occurring over the weekend, or is there some setting/preference that I need to set to allow this?

![image](https://cloud.githubusercontent.com/assets/25228040/22157458/d005e0f4-df05-11e6-9a93-e9257aa3052f.png)

**Comment by dbarashev** [comment]
`Project.Properties.Calendar`. Set the weekend days in the project before importing.

**Comment by jfonline03** [comment]
Spot on! Thanks, hoped it was a simple setting somewhere, just didn't know where to look. All these apps hide their "Preference/Options" in different places.
