### ISSUE TITLE
Question on how best to import milestones from .gan

### ISSUE THREAD

**Issue by abstractspoon** [bardsoftware/ganttproject#1335]
Hi Team

I've previously written an importer from my GP to my app
(https://github.com/abstractspoon/ToDoList_Dev/tree/master/GPExport) and have now been asked to support 'milestones'.

Looking at the .gan file format and the code it seems like checking for the 'meeting' attribute is one way to achieve this but the association with 'isLegacyMilestone' suggests that there may be a better way...

I also noticed that the latest release of GP exports the 'meeting' attribute if the 'milestone' checkbox is ticked which leaves me a little confused.

Any guidance would be greatly appreciated.

.dan.g.

**Comment by dbarashev** [comment]
Hi,
in the file `meeting` attribute with `true` value indicates that task is a milestone. In the code `Task.isMilestone()` method is the right one. Method `isLegacyMilestone` is a deprecated implementation of `isMilestone`. It was renamed when zero-duration milestones were added but usages have not been updated yet.

**Comment by abstractspoon** [comment]
Many thanks for your quick response. That works well for me.
