### ISSUE TITLE
GanttProject won't display window

### ISSUE THREAD

**Issue by ianginn** [bardsoftware/ganttproject#1338]
When I first installed GanttProject it opened with a project window, and when I opened files from our project coordinator I saw the filled project window. Now it starts and then nothing. If I start a new project and add a task I still so no window - but when I want to quit it asks if I want to save the project.

I've attached two logs from today.

[ganttproject.txt](https://github.com/bardsoftware/ganttproject/files/745434/ganttproject.txt)

**Comment by ianginn** [comment]
[ganttproject.log.1.txt](https://github.com/bardsoftware/ganttproject/files/745437/ganttproject.log.1.txt)

**Comment by dbarashev** [comment]
The window seems to be small and probably positioned outside of the visible area. This may happen if you work with multiple displays. Please refer to issue #1302 for the workaround.

**Comment by dbarashev** [comment]
Duplicates #1302 #1304

**Comment by ianginn** [comment]
Thank you. Resetting solved the issue. Yes I had worked with dual monitors... but surely it's a pretty standard functionality for software to check what monitor is available and draw its window on the that...? something that users could expect to happen during start-up...

**Comment by dbarashev** [comment]
As you can see, issue #1304 is open and is marked as bug.
