### ISSUE TITLE
Mainwindow freezes on Windows 10 if previous state was full-screen

### ISSUE THREAD

**Issue by joede** [bardsoftware/ganttproject#1340]
Version: 2.8.1-r2024
System: Windows 10
JDK: Java 8 121 (32-bit)

My regular system is running Debian 8 and here GanttProject work without this bug. Now I had one of these rare situations where I have to do some work on a Windows 10 system.

After starting the application, I have to switch to full-screen. Than, after some work I close the (fill-screen) app (button in the title bar). If i try starting the application again, the main window comes up with a size nearly of the screen. But now menu or any other action is possible. If a file must be loaded at startup time, this file is not fully displayed. In my case the *list view* on the left has less entries than the *gantt view* on the right. Interaction with this views in not possible.

To "revive" the GUI, I simply must switch to full-screen again. As soon as the window fits the full screen, the views are repainted correctly and all the interactions are possible again.

**Comment by dbarashev** [comment]
Hi,
can you try the fix  described in issue #1301 (this comment: https://github.com/bardsoftware/ganttproject/issues/1301#issuecomment-243848439 )

If it doesn't help then please share the contents of the log (Help->View log and a screenshot how it looks like after this:
>this file is not fully displayed. In my case the list view on the left has less entries than the gantt view on the right. Interaction with this views in not possible.

**Comment by joede** [comment]
OK, here is the log. IMO the screen repaint problems I mentioned above are not a (direct) bug. They are the result of the actual problem. The log below shows the start of GanttProject without opening a file. This screen isn't damaged. I still can't use it. All menus are dead. After resizing it to full-screen, the menu (and all other actions) works again. This is why I think issue #1301 doesn't match here.

````
C:\Users\mh\ganttproject.log

GanttProject 2.8.1 Pilsen (build 2024)
Settings file:
    location: C:\Users\mh\.ganttproject
    size:4027
    is readable: true
java.class.path: eclipsito.jar;.
java.home: C:\Program Files\Java\jre1.8.0_121
java.ext.dirs: C:\Program Files\Java\jre1.8.0_121\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\mh\AppData\Local\Temp\
java.runtime.version: 1.8.0_121-b13
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) Client VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.121-b13
os.arch: x86
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true
user.country: DE
user.dir: C:\Program Files\GanttProject-2.8
user.home: C:\Users\mh
user.language: de
user.timezone: Europe/Berlin

Feb 10, 2017 8:29:27 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:C:\Users\mh\.ganttproject
Feb 10, 2017 8:29:28 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Feb 10, 2017 8:29:28 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Feb 10, 2017 8:29:29 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1066]
8. finalizing...
Main frame created
Feb 10, 2017 8:29:29 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=-8,y=-8,width=1932,height=1066]
Feb 10, 2017 8:29:29 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Starting RSS check...
Splash closed
Resizing window...
Feb 10, 2017 8:29:30 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=-8,y=-8,width=1932,height=1066]
Feb 10, 2017 8:29:30 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Setting bounds from options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1066]
Feb 10, 2017 8:29:33 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: RSS check finished
Feb 10, 2017 8:29:37 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Feb 10, 2017 8:29:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:\Program Files\Java\jre1.8.0_121/lib/fonts
Feb 10, 2017 8:29:37 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
````

**Comment by dbarashev** [comment]
> This is why I think issue #1301 doesn't match here.

Please _do try_ the solution described in issue #1301, so that we just knew that Direct3D/hardware issues is not the case.

**Comment by joede** [comment]
I've tried it and.... *it works*. Sorry for the unnecessary delay.

**Comment by dbarashev** [comment]
Thanks! The fix will be published and built into native Windows launcher in the upcoming GanttProject 2.8.2
