### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by SarahShih** [bardsoftware/ganttproject#1342]
After installing ganttproject, the default language is English. In setting option, transferring English to  'Chinese-Taiwan', it cannot show normal tranditional Chinese, but shows '口', and cannot type the normal Chinese-Taiwan (Traditional Chinese) as well. Is there anyone have had this issue?
# The version of ganttproject is  2.8.1 for Windows.

Thank you.

**Comment by dbarashev** [comment]
Please make sure that you're using fonts with Chinese glyphs. You can change fonts on the same Application UI page in the settings dialog where you change language.

**Comment by SarahShih** [comment]
Yes, I chose 'Chinese' one, please refer the attachment. Thank you for the help.

![img_0446 1](https://cloud.githubusercontent.com/assets/20009638/23015621/7d5a88f4-f46e-11e6-955b-b9efb1b11e3c.JPG)
![img_0447 1](https://cloud.githubusercontent.com/assets/20009638/23015622/7d60a70c-f46e-11e6-83b4-672c08568b90.JPG)

**Comment by dbarashev** [comment]
Please listen to me. You need to choose **Application font** with Chinese glyphs. Currently at your screenshot no font is chosen. Please do choose one with Chinese symbols.

**Comment by SarahShih** [comment]
I chose the application font, but it still show abnormal. Please kindly refer to the attachment, thank you a lot.

![fullsizerender](https://cloud.githubusercontent.com/assets/20009638/23056120/b02c356e-f524-11e6-8cc2-74597b16532a.jpg)

**Comment by dbarashev** [comment]
Please choose **Application font with Chinese glyphs**. If you don't have such font on your system, you need to install one. Sometimes such fonts have "CJK" in their names. Here is a screenshot with Noto Sans and WenQuanYI Micro Hei fonts

![screenshot at 2017-02-17 13-42-56](https://cloud.githubusercontent.com/assets/2028330/23062588/67b027f8-f517-11e6-9c42-7a6eabddefc0.png)

**Comment by SarahShih** [comment]
Yes, you're right. I don't have Application font with Chinese glyphs. 
I don't install one and chose 'DFKai-SB' and it's workable as well.
It shows the normal Chinese. Thank you very much.

**Comment by fong0124** [comment]
原来要选择 “地区”和“软件显示语言”，解决了！
谢谢 ♥
