### ISSUE TITLE
Rows in the Resource table remain too narrow when app font is changed to large

### ISSUE THREAD

**Issue by jonazap** [bardsoftware/ganttproject#1344]
Thanks for update 2.8.2 which resolved the hi res problems with displaying the text properly on the Gant screen. Unfortunately the Resource screen still has the old problem of clipping the top and bottom off the text even when changing font sizes.  
![image](https://cloud.githubusercontent.com/assets/25931674/23171156/9f6a8474-f849-11e6-88a3-6ea3b2c8450f.png)

**Comment by dbarashev** [comment]
yes

**Comment by jonazap** [comment]
Hi Sorry – tried to load a screenshot but it locked up.

 

Raised fault #1344

**Comment by jonazap** [comment]
Why has this been closed? Still an outstanding issue.

**Comment by dbarashev** [comment]
It was closed because at the moment of closing I saw only one word "Resolution" in the summary and nothing else. Perhaps Github was a little bit slow to show the updates. Reopening now. Thanks for reporting!

**Comment by jonazap** [comment]
OK thanks Dmitry. Would really appreciate this to be fixed. By the way the rest of the text on the Gant and Resource graphics are still very small for the 4K screens despite the increase in font sizes put in.

Thanks

Jonathn

**Comment by dbarashev** [comment]
Did you make Base chart font larger?

**Comment by jonazap** [comment]
Hi

Yes I set both fonts to larger.
