### ISSUE TITLE
Misaligned rows in task table and gantt chart

### ISSUE THREAD

**Issue by TheBusinessButlers** [bardsoftware/ganttproject#1345]
With the latest update, my projects are no longer aligning either on the screen view in the software or via an export.  This is creating no small problem.  I am not a programmer/coder.....just a user......

![image](https://cloud.githubusercontent.com/assets/25933897/23174863/9328a894-f812-11e6-8604-bb51a717fc39.png)

**Comment by dbarashev** [comment]
Can you open settings dialog and just hit Ok?

**Comment by TheBusinessButlers** [comment]
That fixed it.  Thank you!  Gotta say, as an admin person teaching myself your software, you guys have a really good tool.  Thank you for your efforts!  And yes.....I did contribute.  :)

**Comment by dbarashev** [comment]
Thanks for testing (and for contribution as well). It is a bug of course, will be fixed in the next update.

**Comment by TheBusinessButlers** [comment]
Thank you again.....would love to be able to control number of lines on the page at some point in the future.
