### ISSUE TITLE
Default custom field values are skipped in CSV export

### ISSUE THREAD

**Issue by KrissFREss** [bardsoftware/ganttproject#1349]
Hello,

Actual version : GanttProject 2.8.2 Pilsen (build 2069).
Issue : Ressources CSV export is not complete (some fields information are missing) and the order of the column headers is not the same of the order of the values.

Please notice that it was the same with previous version.

Regards,
Kriss

**Comment by dbarashev** [comment]
> the order of the column headers is not the same of the order of the values.

Can you elaborate on this? Any reproducible scenario?

**Comment by KrissFREss** [comment]
Hello,

Here is my situation that can certainly be reproduced :
- several ressources with several properties
- some properties have default value others not
- csv export files preferences : ID and cost in preferences

Result :
the new property (added yesterday) with a default value is the last header column in export file but the 4th in value columns when the value has been modified or is missing when default value has been keeped.

Here is the capture of Gantt project :
![image](https://cloud.githubusercontent.com/assets/26067587/23399314/15acfeae-fda0-11e6-8e18-8facd0a409cf.png)

Here is the capture of the export file :
![image](https://cloud.githubusercontent.com/assets/26067587/23399378/4cd0ee0e-fda0-11e6-9656-21cbd4e0c68a.png)

I hope that it will help.
Regards,
Kriss

**Comment by dbarashev** [comment]
Thanks for the details. So, the issue is that the value of custom field is completely skipped in the CSV export if it is not specified (that is, default is used). However, its name appears in the heading. When you have more than 1 custom field this effectively means that the subsequent values shift into adjacent columns.

Thanks for reporting, we'll fix it in the next update.

**Comment by KrissFREss** [comment]
Happy to help :)
Do you know when the next update will be available ?

**Comment by dbarashev** [comment]
This week, hopefully.

**Comment by KrissFREss** [comment]
ok, thanks.
