### ISSUE TITLE
DEB package won't install

### ISSUE THREAD

**Issue by joseccuellar** [bardsoftware/ganttproject#1352]
I get the following error message when trying to install v2.8.2 on Linux Mint 17.3:

(Reading database ... 236058 files and directories currently installed.)
Preparing to unpack .../ganttproject_2.8.2-r2069-1_all.deb ...
Unpacking ganttproject (2.8.2-1) ...
dpkg: error processing archive /home/jose/Downloads/ganttproject_2.8.2-r2069-1_all.deb (--install):
 unable to create `/usr/share/doc/ganttproject/AUTHORS.dpkg-new' (while processing `./usr/share/doc/ganttproject/AUTHORS'): No such file or directory
Errors were encountered while processing:
 /home/jose/Downloads/ganttproject_2.8.2-r2069-1_all.deb

**Comment by dbarashev** [comment]
Hi, thanks for reporting.
Can you look at the path to `/usr/share/doc/ganttproject/AUTHORS` and tell the shortest missing prefix? I think you have `/usr/share`, but do you have `/usr/share/doc/` ?

**Comment by dbarashev** [comment]
Also, do you have enough permissions for changing these directories?

**Comment by joseccuellar** [comment]
Hi.
I've got /usr/share/doc. I'm logged as an standard user, but the Mint Package Installer asks me for my root password, just like any other installation I've done before.
When I open the .deb file, the Package Installer starts by default. Is there any other way of installing the package?
Thanks.

**Comment by dbarashev** [comment]
Okay, I will look whathappens when `/usr/share/doc/ganttproject` is missing.
You can just use ZIP distro. Provided that you can run `java` from the command line, you need to unzip the file and run `ganttproject` script from the unzipped package.

**Comment by dbarashev** [comment]
Yes, it seems that debian package won't create `/usr/share/doc/ganttproject` automatically and fails. Will be fixed in GP 2.8.3
