### ISSUE TITLE
Why project marked as modified on loading?

### ISSUE THREAD

**Issue by crystalfp** [bardsoftware/ganttproject#1359]
When I load a .gan file it is immediately marked as modified. If I save it the only difference in the file from the original one is:

```
    <view zooming-state="default:11" id="gantt-chart">
        <field id="tpd3" name="Name" width="228" order="0"/> width was 237
        <field id="tpd4" name="Begin date" width="94" order="1"/> width was 97
        <field id="tpd5" name="End date" width="81" order="2"/> width was 84
        <field id="tpd6" name="Duration" width="80" order="3"/> width was 82
```

You see, the difference is few pixels and it is not caused by any action from my side. Seems it is result of some rounding of the column widths. But it is really annoying.
Thanks for looking!
mario

2.8.3 on windows 7 64 bits, java 1.8.0_121

**Comment by dbarashev** [comment]
Duplicates #1310 

By the way, what happens if you really save the project and open it again? Will it be modified?

**Comment by crystalfp** [comment]
Yes, it is modified. Every time.

**Comment by dbarashev** [comment]
#1310 is closed now, closing this as well.

**Comment by dbarashev** [comment]
#1310 is closed now, closing this as well.
