### ISSUE TITLE
Scrolling up the Gantt labels go in front of the year/month strip

### ISSUE THREAD

**Issue by crystalfp** [bardsoftware/ganttproject#1360]
Scrolling up the Gantt chart makes the graphical elements pass below the calendar strip (I don't know if there is a better name), but the labels pass on top of it creating a not readable blob. See an example:

![labels](https://cloud.githubusercontent.com/assets/865866/23795326/569b90d6-0595-11e7-9540-61184aa141db.png)

I think also the labels should move as the graphical elements.

2.8.3 on Win7 64bits java 1.8.0_121

**Comment by dbarashev** [comment]
Thanks for reporting!
