### ISSUE TITLE
webdav locking

### ISSUE THREAD

**Issue by andyp05** [bardsoftware/ganttproject#1369]
Using GP 2.8.3 and a project file stored in opendrive cloud storage. I was testing multi-user features and noticed that no locks are being placed.

In GP, I am using the "Open from a server" option and URL of https://webdav.opendrive.com

If I run two computers side by side, I can edit the same file and the same task, but the last person that saves the file overwrites the others changes. No warning or lock messages appear. Am I missing some setting?

Thanks

**Comment by dbarashev** [comment]
Is locking supported by OpenDrive? By far not every cloud WebDAV supports locking. If locking is supported then you need to click "Lock" icon in the "Open from server" dialog to lock the selected file.

**Comment by andyp05** [comment]
Can you suggest a cloud provider known to support locking so I can try it. Any provider with a US presence would be great.

Thanks for the quick reply.

**Comment by dbarashev** [comment]
No first-hand experience, but quick googling returns this: https://www.drivehq.com/mapdrive/

**Comment by andyp05** [comment]
Ok, Thanks. Ill take a look. If I use WebDAV, does GP lock the entire file so a second user can't open it, or does the second user get read-only access? Is there any document/blog discussing this feature?

**Comment by dbarashev** [comment]
GP takes write lock. Concurrent users can open, and can even change the file, they will only not be able to write to the server.

**Comment by dbarashev** [comment]
Closing the issue now. Please consider using https://help.ganttproject.biz for such discussions. GitHub is okay as well, but when there are too many issues which are not bugs or enhancements it becomes cluttered.
