### ISSUE TITLE
Error when clicking Delete in the empty resources table

### ISSUE THREAD

**Issue by nchvidt** [bardsoftware/ganttproject#1372]
There is an error - whenever I want to add resources (persons) to a task, there is an error: 

I cannot write the name and if I press "delete" I get an error message. 

I send you the Error Log and screenshot of what it looks like when I try to establish a resource.

I use MacOS Sierra on an iMac Retina.

Regards, 

Niels Christian Hvidt  

[Error Log GanttChart.docx](https://github.com/bardsoftware/ganttproject/files/861181/Error.Log.GanttChart.docx)
<img width="1096" alt="screen shot 2017-03-22 at 09 43 18" src="https://cloud.githubusercontent.com/assets/26597613/24194944/306ff1e2-0ef8-11e7-830f-690e36ed5506.png">

**Comment by dbarashev** [comment]
Hi,
you don't need to type resource names in the Resources tab, you can choose them in the dropdown list. In fact, typing when dropdown is expanded works fine as well in my tests, but it may be different on Mac OSX. 

The reported error shows if you hit "Delete" when there is just one [empty] tow in the table. We'll fix it of course, but it is not directly related to assigning resources.

**Comment by dbarashev** [comment]
I've changed the issue title appropriately.

**Comment by dbarashev** [comment]
Just've realized that the issue was probably that you were trying to create _new_ resource in the task properties? This is not supported [yet], sorry. You need to create a resource (_Resources->New Resource_) and once it is created, it will be available in the _Resources_ tab of _Task Properties_ dialog.

**Comment by nchvidt** [comment]
Dear Dmitry,

You are right, This was the problem.

Would be nice if one could add resources directly from new tasks, but good there was a solution.
Best,

Niels Christian


On 22 Mar 2017, at 12.51, Dmitry Barashev <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
you don't need to type resource names in the Resources tab, you can choose them in the dropdown list. In fact, typing when dropdown is expanded works fine as well in my tests, but it may be different on Mac OSX.

The reported error shows if you hit "Delete" when there is just one [empty] tow in the table. We'll fix it of course, but it is not directly related to assigning resources.
