### ISSUE TITLE
Missing icons for task movement

### ISSUE THREAD

**Issue by crystalfp** [bardsoftware/ganttproject#1376]
Installed 2.8.4 on top of 2.8.3
Now the context menu is missing icons for move up/down and indent/unindent.
I'm on windows 7 64bits

![bug-icons](https://cloud.githubusercontent.com/assets/865866/24437621/69d039de-1442-11e7-8f7c-145ca3a019e4.png)

**Comment by BrieucSEF** [comment]
Same here on W10.

**Comment by dbarashev** [comment]
Ooops. Thanks for reporting! Will be fixed in the next update.
