### ISSUE TITLE
Missing milestone in the calendar bar

### ISSUE THREAD

**Issue by BrieucSEF** [bardsoftware/ganttproject#1377]
The milestone indication is not present anymore in the calendar top bar.
v2.8.4 installed on top of 2.8.1, windows 10

![image](https://cloud.githubusercontent.com/assets/26762097/24444995/bc4e6a02-1468-11e7-85f9-005228ce8821.png)

**Comment by dbarashev** [comment]
Thanks for reporting! Will be fixed in the next update.
