### ISSUE TITLE
add task color column to export as CSV

### ISSUE THREAD

**Issue by tomasmez** [bardsoftware/ganttproject#1382]
When i export the data for statistical analysis, one of the things i miss is the color of the task, i use different colors for different tasks and it would be nice to be able to use this info in statistics.

**Comment by jcharlet** [comment]
Hi,
could this commit be imported in the main repository? Can I do anything to help with that?
Thanks,
Jeremie

**Comment by dbarashev** [comment]
The author created a pull request and received some review comments. The comments need to be addressed before merging.
