### ISSUE TITLE
possibility to add a custom column to a project for tasks

### ISSUE THREAD

**Issue by tomasmez** [bardsoftware/ganttproject#1383]
in every task i get to add:
 start date
end date
resources
. but i have a special data i need (which is an internal work number) i would like to have in all tasks.

Is it possible to have this possibility (define custom form fields for tasks in a project?)

**Comment by dbarashev** [comment]
Did you try "Custom Columns" tab in the task properties dialog?

**Comment by tomasmez** [comment]
nope. i did not. Thanks!.

**Comment by dbarashev** [comment]
Just some more information: right-click in the table header shows a context menu where you can show/hide columns, as well as add new ones.

**Comment by dbarashev** [comment]
Please consider using support forum for such sort of questions: http://help.ganttproject.biz
Issue tracker is more development-oriented and too many support tickets -- not bug reports and not enhancement requests -- make the tracker cluttered.
