### ISSUE TITLE
MS Project exporting error

### ISSUE THREAD

**Issue by markcwalton** [bardsoftware/ganttproject#1390]
Not sure if this is the same issue as previous poster.

Scenario: Schedule was originally created using MS Project 2016. I can Import the MPP into GanntProject without issue and modify it. I need to export to MPX format for import into Primavera SureTrak (for a client)

When I try to Export to MPX, I get the error:

--
Something went wrong 
Export failure. Failed subtask: Export project
--

I'm attaching the Log file.

I also tried using MS Project 2016 to save the project to XML instead, but I can't Import it into GanntProject (myriad errors).

Thanks,

- Mark

[ganttprojectlog.txt](https://github.com/bardsoftware/ganttproject/files/894130/ganttprojectlog.txt)

**Comment by dbarashev** [comment]
Yes, it is the same issue and will be fixed in the next update. The workaround is to remove all useless custom columns named like "Number1", "Flag3", etc. Use context menu in the table header, "Manage Columns..."

**Comment by markcwalton** [comment]
OK, I was hopeful but it did not work. I deleted every column except the first 14 (which you can't delete) and got the same error. Not sure if anything changed, but I'm attaching the pertinent log file.

I appreciate your help and quick response!
[ganttproject.txt](https://github.com/bardsoftware/ganttproject/files/894275/ganttproject.txt)

**Comment by dbarashev** [comment]
Can you try doing the same with resources?

Do not close this ticker please :)

**Comment by markcwalton** [comment]
That did it! 👍 Did not think of that.

Thanks so much!

**Comment by jlruivo** [comment]
I created an issue similar to this one. The work around also worked for me. 
Thanks.
