### ISSUE TITLE
PERT chart unreadable with high DPI settings

### ISSUE THREAD

**Issue by parras** [bardsoftware/ganttproject#1397]
It seems that the fonts in the PERT chart are not correctly scaled with the DPI setting, resulting in illegible text as shown on the following screen-shot:
![gantt_pert_unlegible](https://cloud.githubusercontent.com/assets/3695507/24964172/cf525f26-1fa0-11e7-8c46-4a45a0157970.png)

Here are my settings:
- OS: Linux
- display: 3840x2160
- DPI: 192
- Appearance: Plastic
- Font sizes: big (2)
Using GanttProject 2.8.4 Pilsen (build 2134).

The rest of the UI is rendered correctly.

**Comment by dbarashev** [comment]
Yup, thanks for reporting.
