### ISSUE TITLE
multiple task not apply to same day if added predesoor to them

### ISSUE THREAD

**Issue by audumbard** [bardsoftware/ganttproject#1401]
If creating a task 3 with 30% time to same day & Apply the Predessor to them the task goes to next day.

**Comment by dbarashev** [comment]
Uhh.... what? Can you please give a little bit more clear description? Scenario like this could be also helpful:
1. Create task starting on day X
1. Do this
1. Do that

Expected: .... Actual: ....

**Comment by audumbard** [comment]
Hello,
         I am using a version 2.8.4 of gannt project. I am trying to
creating the below scenario. The steps are
1. I had create a task 1 for date 3/4/17 with 25% of day time usage.
2. Then  I had create task 2 for same date with 50% of day time usage. Here
I added predecessor task 1.
3. But when save the task settings the task two shifted to next day. It
must be allocate to same day because I am allocating below 100% of usage
time.
4. If am allocating 25% day usage task 1 for 3/4/17 & task two 50 % of next
day & added predecessor of task 1 then it must be save as it is. It's
working fine.

If you want more clarification . Please may I know.
Thanks,
Audumbar


On 16-Apr-2017 6:04 AM, "Dmitry Barashev" <notifications@github.com> wrote:

Uhh.... what? Can you please give a little bit more clear description?
Scenario like this could be also helpful:

   1. Create task starting on day X
   2. Do this
   3. Do that

Expected: .... Actual: ....

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bardsoftware/ganttproject/issues/1401#issuecomment-294325943>,
or mute the thread

**Comment by dbarashev** [comment]
I don't know how do you assign those percents, but anyway, the minimum task duration in GanttProject is 1 day. If you make task1 a  predecessor of task  2, the latter shifts so that  its start date is >= task 1 end date.

It works as designed.
