### ISSUE TITLE
Resource load on a task is not preserved during export/import

### ISSUE THREAD

**Issue by okusha** [bardsoftware/ganttproject#1402]
Scenario to reproduce:
- Create new project
- Create new task task1
- Create new resource res1
- Assign res1 to the task1 It will have 100% load default
- Export to CSV
- Delete task1/res1 or create new project
- Import CSV back

Expected: res1 has 100% load on task1
Actual: res1 has 0% load on task1

**Comment by dbarashev** [comment]
Duplicates #274
