### ISSUE TITLE
Unable to change basic settings

### ISSUE THREAD

**Issue by arena94** [bardsoftware/ganttproject#1403]
I was trying to use your software for a two days event 48h during a week end

Unable to change the default calendar

Unable to have the tasks start, end, duration set to the minute

Unable to zoom the line at the hour half hour level

...

keep up the good work, the UI is good !

**Comment by dbarashev** [comment]
Not sure what did you mean to say in this issue. 

Minimal task duration in GanttProject is 1 day, this is explicitly written in the FAQ. You can change the calendar in Project->Properties->Calendar.
