### ISSUE TITLE
emty lines in pulldown menu

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1404]
after pressing the right mouse button on a task the opening pulldown menu shows for some entries an empty line. 
using GanttProject 2.8.4 Pilsen (build 2134), 
os: w10 pro-veersion 1607

![pulldown](https://cloud.githubusercontent.com/assets/13802775/25314403/7b1e6656-2843-11e7-8dc7-e709568a884b.jpg)

**Comment by dbarashev** [comment]
Duplicates #1376
