### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by hjacquemin** [bardsoftware/ganttproject#1407]
Hello,

I can't start ganttproject on my pc, it generate a crash dump at each reboot but see the resume below:

```
Writing log to /home/herve/.ganttproject.d/.ganttproject-20170505134545.log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f08a0fc5009, pid=19976, tid=20007
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
[crash dump.zip](https://github.com/bardsoftware/ganttproject/files/978890/crash.dump.zip)
```

Actualy I try to run the app on my ubuntu 16.04.

Thanks for your help.

Hervé Jacquemin

**Comment by dbarashev** [comment]
Please consider using the supported Java Runtime. Java 9 is not yet
released and we do not plan to work with it's internal builds which are 1
year old. GanttProject runs on Java 7 and Java 8

**Comment by hjacquemin** [comment]
I unistall all openjdk-9-* packets and install all openjdk-8-* remove ganttproject, and re-install it after package were installed.

Still the same, or do you I have to manually set a value in a config file to use Java 8 ?

**Comment by alessio31183** [comment]
Same issue....it doesn't start....

Reinstalled java 8 with no changing

**Comment by dbarashev** [comment]
When you say "still the same", do you mean "exactly the same", that is, you
see openjdk 9 in the log or do you mean anything else?

**Comment by alessio31183** [comment]
still the same means that simply it doesn't start.
Condition around are jdk8 installed with no jdk9

I don't know which is th issue with java that stuck the software starting

Best

**Comment by dbarashev** [comment]
@alessio31183 the question was addressed to @hjacquemin who submitted the issue.

Your issue is not the same, it is different. It seems that you're using invalid logo file. Remove file .ganttproject from your home folder to restore the original settings.
