### ISSUE TITLE
ganttproject export in MS Project formats does not work

### ISSUE THREAD

**Issue by jlruivo** [bardsoftware/ganttproject#1408]
Can't export a ganttproject file in MS Project format (mpx or mspdi).
The files I am trying to export were previously imported from MS Project.
I need to be able to import MS Project files, work on the files and reexport them to MS Project. 
This test was done without any modification to the imported file. It was imported, saved and attempted an export of the resulting file.
Thanks,
Jose

[Ganttproject export error log.txt](https://github.com/bardsoftware/ganttproject/files/981090/Ganttproject.export.error.log.txt)

**Comment by dbarashev** [comment]
Duplicates #1390
