### ISSUE TITLE
Incorrect display of the tasks after project loading

### ISSUE THREAD

**Issue by sprevot** [bardsoftware/ganttproject#1409]
After loading a project, the list of tasks on the left is not correctly displayed and refreshed (see screenshot).
Also an error occurs, you will find the trace attached.
I tried to close and open the project several times but the same error occurs.
Thanks in advance for your help.

![2017-05-10 09_36_57-ganttproject planning_transporeon gan](https://cloud.githubusercontent.com/assets/28589240/25887930/660cec6e-3564-11e7-9c24-cc1e0d0bd030.png)

[ganttproject.txt](https://github.com/bardsoftware/ganttproject/files/989007/ganttproject.txt)

**Comment by dbarashev** [comment]
It seems that one of the resources in your project has no name. Can you share the project file?

**Comment by sprevot** [comment]
Hello,
Here is the project file.
(https://github.com/bardsoftware/ganttproject/files/1003581/Planning_Transporeon.zip)
This is correct, one name of the resources was missing and generating troubles in the display.
After setting a name to the resource, there are no errors now.
Thanks a lot.
