### ISSUE TITLE
bug in display

### ISSUE THREAD

**Issue by bartelstx** [bardsoftware/ganttproject#1410]
create a project
create subtasks within the project and save
edit   / settings  / application UI / change base chart font and  application font, change to a larger size
>> in the GANTT window, the right pane (calendar) now shifts UP by one row, such that the task name (left pane) is no longer correctly represented by the task display.

![ganttcapture](https://cloud.githubusercontent.com/assets/28656153/26007524/79c592f8-3706-11e7-9f43-59a5141a1e8e.PNG)

**Comment by dbarashev** [comment]
Sorry, what is wrong on the screenshot? There are as many tasks in the table as bars on the chart. Summary task bars on the chart do correspond to expanded nodes in the table. Everything looks just fine.
