### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by Greig1960** [bardsoftware/ganttproject#1415]
Good day
There is an alignment problem between the text field and the Gantt chart as shown below. Not sure if it is perculiar to my PC.
![image](https://cloud.githubusercontent.com/assets/29031545/26536324/8b1dc382-443e-11e7-9815-854a0e77d1e0.png)

**Comment by dbarashev** [comment]
According to the screenshot, you're using one of the older versions of GanttProject. Please upgrade to the latest one and check if the issue is still reproducible. Thanks.

**Comment by Greig1960** [comment]
Hello Dmitry
Thanks very much for the assistance. I purchased the latest version of GanttProject, downloaded and installed it - now appears all okay.
Regards
Greig
