### ISSUE TITLE
Adding a second cost field for tasks

### ISSUE THREAD

**Issue by bosmanoglu** [bardsoftware/ganttproject#1418]
Hi,

This is not a real issue per-se. I pulled the source code today and attempted to add a second cost field for each task and a corresponding standard rate for a resource. I am calling the new cost-field "Cost2". 

I am using "gradle runApp" to test it now, and it seems to work OK. I tested auto-calculation of Cost, saving and loading etc. 

However, I can't figure out how to display Cost2 column in the Gantt Task Tree. Any ideas how to get it in the "Custom Fields Manager" dialog so I can click "Show Selected"? 

All the best, 
batu.

**Comment by dbarashev** [comment]
Do you mean that you changed the code and added Cost2 programmatically? Can you show the changes?

**Comment by bosmanoglu** [comment]
Yes, I did. It is on my local computer now, but I will push the code to github so you can take a look. If you are only interested in a diff, I can try to do that as well. There were quite a few files I touched though.

**Comment by dbarashev** [comment]
Push to github and create pull request, just to be able to see diffs side by side and comment on them

**Comment by bosmanoglu** [comment]
OK, done.
