### ISSUE TITLE
Can't build windows version of project

### ISSUE THREAD

**Issue by LokiGrants** [bardsoftware/ganttproject#1427]
I tried using distWin but it gives me an error everytime.

> Caused by: net.rubygrapefruit.platform.NativeException: Could not start './gen-nsis'
> 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
> 	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
> 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
> 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
> 	... 2 more
> Caused by: java.io.IOException: Cannot run program "./gen-nsis" (in directory "C:\ganttproject\ganttproject-builder"): CreateProcess error=193, %1 is not a valid Win32 application
> 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
> 	... 5 more
> Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
> 	... 6 more

Then, if I try to copy the data from gen-nsis directly to the code, it gives me the following:

> Caused by: java.io.IOException: Cannot run program "#!/bin/bash
> rm ganttproject.nsi
> echo '!define VERSION "'"$1"'"' > ganttproject.nsi
> echo '!define VERSION_BUILD "'"$2"'"' >> ganttproject.nsi
> cat ganttproject.nsi.tpl >> ganttproject.nsi" (in directory "C:\ganttproject\ganttproject-builder"): CreateProcess error=2, The system can't find the specified file
> 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
> 	... 5 more
> Caused by: java.io.IOException: CreateProcess error=2, The system can't find the specified file
> 	... 6 more

And if I try to jump it altogether, I get:

> Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/opt/launch4j/launch4j'
> 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
> 	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
> 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
> 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
> 	... 2 more
> Caused by: java.io.IOException: Cannot run program "/opt/launch4j/launch4j" (in directory "C:\ganttproject\ganttproject-builder"): CreateProcess error=2, The system can't find the specified file
> 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
> 	... 5 more
> Caused by: java.io.IOException: CreateProcess error=2, The system can't find the specified file
> 	... 6 more

Funny part? Tried using IntelliJ and Power Shell.

Any clues?

**Comment by dbarashev** [comment]
Do you really need it? For most development purposes `distBin` or `distZip` is enough. `distWin` just adds an installer.

**Comment by LokiGrants** [comment]
the distBin is not initiating by itself, nor distZip is creating a win version, just macOS one.

**Comment by dbarashev** [comment]
> the distBin is not initiating by itself,

Sorry? It builds full distro in `ganttproject-builder/dist-bin` directory.

Try doing one of the following:
- copy `ganttproject-eclipsito-config.xml` from `ganttproject-builder` into the unzipped distro
- run `ganttproject.bat -plugins-dir plugins-2.8.5 -app net.sourceforge.ganttproject.GanttProject`

**Comment by LokiGrants** [comment]
It was just the xml that was really missing... It seems it is not taking it to the final dist-bin, at least in the latest master.
