### ISSUE TITLE
Can't open dmg on macOS Sierra 10.12.5

### ISSUE THREAD

**Issue by ryanthara** [bardsoftware/ganttproject#1428]
Hi everybody

Is there anybody out there who can't open the downloaded dmg file of the pilsen version. I downloaded the current release early this morning and could not open the dmg file on my mac.

Any idea about this?

**Comment by dbarashev** [comment]
Hi, it opens fine. MD5 sum of the dmg file is a76493eeaa839e667f102fb3418ac3e5

**Comment by ryanthara** [comment]
Now it works, but still some bugs are alive. I'll create a few reports.
