### ISSUE TITLE
csv file importer does not recognize four-digit date

### ISSUE THREAD

**Issue by a2brute** [bardsoftware/ganttproject#1430]
I imported a csv, then exported the project as csv from ganttProject, then re-imported the newer save.  The import process did not accept its own four-digit year date format.  I changed the default format successfully, which will then not accept a two-digit date format.

Also, this webform does not accept your .log extention

C:\Users\a2brute\ganttproject.log

[ganttproject.txt](https://github.com/bardsoftware/ganttproject/files/1092084/ganttproject.txt)

GanttProject 2.8.5 Pilsen (build 2179)
Settings file:
	size:4671
	is readable: true
[ganttproject.txt](https://github.com/bardsoftware/ganttproject/files/1092088/ganttproject.txt)

java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-2.8
java.home: C:\Program Files\Java\jdk1.8.0_60\jre
java.ext.dirs: C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext;C:\Windows\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\a2brute\AppData\Local\Temp\
java.runtime.version: 1.8.0_60-b27
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.60-b23
os.arch: amd64
os.name: Windows 7
os.version: 6.1
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true
user.country: US
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\a2brute
user.language: en
user.timezone: America/Los_Angeles

Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
8. finalizing...
Main frame created
Splash closed
Resizing window...
Bounds stored in the  options: java.awt.Rectangle[x=-8,y=32,width=1936,height=1056]
Jun 21, 2017 8:39:17 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after setVisible: java.awt.Rectangle[x=-8,y=32,width=1936,height=1056]
Jun 21, 2017 8:39:18 AM net.sourceforge.ganttproject.GPLogger log

[snip]

Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor calculateLatestDates
FINE: latest start date=Mon Feb 05 00:00:00 UTC 2018
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>7/27/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/6/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/6/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/6/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/6/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/29/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/6/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/6/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/7/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/8/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/9/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/10/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/10/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/13/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/14/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>3/15/2017</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/15/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/15/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/16/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/16/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog
Jun 21, 2017 8:39:58 AM net.sourceforge.ganttproject.importer.ImporterBase reportErrors
WARNING: Failed to parse date <i>8/17/2016</i>. Date is expected to have format <i>M/d/yy</i> (e.g. today is <i>6/21/17</i>). You can change date format in the settings dialog

**Comment by dbarashev** [comment]
Both CSV import and CSV export recognize the format which is set in the settings. If you exported file when your date format in the settings was M/d/yyyy then dates in CSV will be written as M/d/yyyy and you should import it back with the same M/d/yyyy in the settings.

This form is hosted on the GitHub which is a third-party service and is not under our control. The list of supported attachments is [given in their docs](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)
