### ISSUE TITLE
Tasks do not summarice children tasks correctly

### ISSUE THREAD

**Issue by allan-xomit** [bardsoftware/ganttproject#1431]
Tasks (grandparents) with children (parents) that again have children do not summarize the costs of the parents. The parent however summarize the cost of the children correctly.

Seen in GanttProject 2.8.5 Pilsen (build 2179) on macOS Sierra Version 10.12.15. Danish as language in both GanttProject and OS.

Please also see attached screenshot.

Regards,
Allan Schmidt

Last column are the costs (expense). Second-last column is duration. The cost of all ressources is set to 1 so that I can assess the actual work needed in days. Please notice, that the first line (the grandparent) do not summarize the cost of the parents, even though the parents summarice the cost of their children correctly.

![image](https://user-images.githubusercontent.com/17924145/27679295-93111872-5cb8-11e7-98c8-d0d47164ff6c.png)

**Comment by dbarashev** [comment]
It does work fine. You can find our sample project in the attachment with Michelangelo payment rate set to 1. "Architectural design" task summarizes everything.

You may want to make sure that  task cost in your summary tasks is set to "Calculated", not to "Set explicitly"
[Issue1431.zip](https://github.com/bardsoftware/ganttproject/files/1111852/Issue1431.zip)
