### ISSUE TITLE
A bug when input chinese in text control of resource form happened

### ISSUE THREAD

**Issue by xxsni** [bardsoftware/ganttproject#1432]
When i input chinese in text control of resource form， The temp Character is displayed， like xu徐， what i want is 徐。

**Comment by dbarashev** [comment]
I have no idea what is temp Character and how do you type it, but anyway, you may want to choose good Application font with all chinese glyphs in the applications settings (Edit->Settings->Application UI)  and/or appropriate input method (the latter depends on your operating system).

**Comment by xxsni** [comment]
I stored a picture in the following website which showed the situation. There is two space or xu character in the text control, when I was typing.
http://osk62oblq.bkt.clouddn.com/example.png
http://osk62oblq.bkt.clouddn.com/example2.jpg

**Comment by dbarashev** [comment]
What if you choose Chinese language in the application settings?

**Comment by xxsni** [comment]
I tried chinese-china and english. All had same problem.
