### ISSUE TITLE
Virustotal scan indicates that Gantt project contains malware / adware

### ISSUE THREAD

**Issue by joejoseph00** [bardsoftware/ganttproject#1435]
My colleagues refuse to use this software because it contains malware / adware.

https://virustotal.com/en/file/5c1e7c316ec5bbb74472f813b7e527473fc7b0b7d0e16f6bbed12201bfc485e6/analysis/
Bkav 	W32.eHeur.Malware09 20170703 

Rising 	Malware.Heuristic!ET#82% (rdm+) 	20170703

**Comment by joejoseph00** [comment]
https://www.fixyourbrowser.com/removal-instructions/remove-malware-heuristicet-rdm-virus/

**Comment by joejoseph00** [comment]
ganttproject-2.8.5-r2179.exe is the culprit build

**Comment by dbarashev** [comment]
Everything about these false positive reports is written in the [release notes](https://github.com/bardsoftware/ganttproject/releases/tag/ganttproject-2.8.5)

**Comment by apiconnectplus** [comment]
Avira detect 
![imagen](https://github.com/user-attachments/assets/c27dc898-37ee-4e8f-a787-a000704fff67)
