### ISSUE TITLE
Save action starts editing task name in the task table

### ISSUE THREAD

**Issue by ryanthara** [bardsoftware/ganttproject#1439]
This is how GanttProject looks like after hitting the cmd+s command for saving.

<img width="220" alt="bildschirmfoto 2017-07-05 um 05 36 20" src="https://user-images.githubusercontent.com/7117072/27848252-0384e770-6144-11e7-8117-c715c3c6ca01.png">

**Comment by maiknowack** [comment]
Same Issue on Windows 10.
