### ISSUE TITLE
Child windows not formed and crashes constantly under OS X El Capitan 10.11.6

### ISSUE THREAD

**Issue by DomWork** [bardsoftware/ganttproject#1441]
I used GanttProject a couple of years ago briefly under windows and it was simply great.
Needing to create a gantt again, I have come back to it. However under Mac it has been a nightmare. 
GanttProject 2.8.5 Pilsen (build 2179)
Pulling menu items down or opening dialogue boxes almost always either causes the program to crash instantly or when you do the next operation after a malformed dialogue box has been closed.
Even clicking "About Gantt Project" crashed it 2 of the 3 times I tried.
I have sent several of the crash reports to Apple. Attached is the latest on on clicking "About Gantt Project"
[GanttProjectCrashOnClickingAboutGanttProject.docx](https://github.com/bardsoftware/ganttproject/files/1142063/GanttProjectCrashOnClickingAboutGanttProject.docx)

**Comment by dbarashev** [comment]
Quick googling indicates that it is an issue of Yosemite and apps which stick to using discrete graphics (applies to Java Runtime). I have found a couple of hacks on StackOverflow: https://stackoverflow.com/questions/21170644/is-it-currently-possible-to-enable-the-macs-integrated-graphics-chip-in-a-java

Can you try workarounds written there? In particular, try removing this from Info.plist

```
<key>NSHighResolutionCapable</key>
<true/>
```

Info.plist should be in `/Applications/GanttProject.app/Contents/Info.plist`
