### ISSUE TITLE
Cost value for a task with an intent level of 6 and above is not added to the total cost of the parent

### ISSUE THREAD

**Issue by epgoose** [bardsoftware/ganttproject#1444]
when assigning a value for the Cost parameter for tasks that are 6 (and above) level intended the parent task and each of his parent task up until the first task is not accumulating the value to the total value.

version 2.8.5 build 2179

**Comment by dbarashev** [comment]
It is unlikely to be true, because there are no restrictions on the task level in the algorithm which calculates costs. Most likely one of the tasks upper in the hierarchy has manual set cost. Please check it. If you believe that there is really a bug, please share the project file.
