### ISSUE TITLE
Ganttproject looses preferences

### ISSUE THREAD

**Issue by praesoll** [bardsoftware/ganttproject#1445]
Standard-date-format and path to the logo-file (although shown correctly in the path-field) are lost when closing ganttproject and haveto be set new at each start.

**Comment by dbarashev** [comment]
No, it doesn't, at least in my tests. Besides, there is no "standard-date-format" option. There is an option to use default date format according to chosen language and option to set custom short date format where one can specify a pattern. Both work fine and logo file too. Please provide more details if it doesn't work  for you.

**Comment by praesoll** [comment]
hmm - true it's the default date - in the german translation it is "Standard"
I have to do the changes in the preferences every time I restart GanttProject.
Thx!

**Comment by dbarashev** [comment]
What changes do you have to  do? "Standard" is a radio  button, if you select "Standard", the date format is set according to the chosen language. The only alternative of "Standard" is  "Benutzerdefiniert". Do you mean that the next time you start GanttProject "Benutzerdefiniert" is chosen?

**Comment by praesoll** [comment]
correct. for me it should keep default/standard.
Interesting: also when opening projects it changes from default/standard to benutzerdefiniert at the next start

**Comment by dbarashev** [comment]
Submitted new issue #1449
