### ISSUE TITLE
Open last project

### ISSUE THREAD

**Issue by praesoll** [bardsoftware/ganttproject#1446]
"Open last project" causes an error message 
cannot open document....path not found....

althought the path is correct.

opening via "open file" works fine.

BTW: great software, I like it!

**Comment by dbarashev** [comment]
Please provide more details: operating system and how the path looks like.

For the record, there is no "last" project, there is a list of recent projects

**Comment by praesoll** [comment]
Win 10 Pro, Build 15063
GanttProject 2.8.5 Pilsen (build 2179)
Java 8 Update 144

The path is a subfolder of my c:\USERS\....\Eigene Dokumente\...... with a jpg as logo-file

- as I reinstalled GanttProject there is just one last project in the list of recent projects

Thank you!

**Comment by dbarashev** [comment]
I mean, can you show the full path? What error message do you get? What is in the log (Help->View log)

**Comment by praesoll** [comment]
**Path:**
C:\Users\Rainer Präsoll\Documents\PROJEKTE\Der Standard\Redaktion FLOW\Ganttproject\FLOW.gan

**error message:**
Irgendetwas ist schiefgegangen 

Can't open document net.sourceforge.ganttproject.document.ProxyDocument@170b5dd Die Datei kann nicht geöffnet werden.: C:\Users\Rainer Präsoll\Documents\PROJEKTE\Der Standard\Redaktion FLOW\Ganttproject\FLOW.gan (Das System kann den angegebenen Pfad nicht finden) C:\Users\Rainer Präsoll\Documents\PROJEKTE\Der Standard\Redaktion FLOW\Ganttproject\FLOW.gan (Das System kann den angegebenen Pfad nicht finden) 

****Logfile attached**
[log.txt](https://github.com/bardsoftware/ganttproject/files/1197368/log.txt)

**Comment by dbarashev** [comment]
Thanks for the log.
These lines 
```
WARNUNG: C:\Users\Rainer Präsoll\.ganttproject (Zugriff verweigert)
java.io.FileNotFoundException: C:\Users\Rainer Präsoll\.ganttproject (Zugriff verweigert)
```

explain why options are not saved: you don't have permission to write the options file, for whatever reason. 

With respect to the file reopening, I believe the file is really missing. Can you type this command in the command prompt and paste the output here?
```
dir /B C:\Users\Rainer Präsoll\Documents\PROJEKTE\Der Standard\Redaktion FLOW\Ganttproject\FLOW.gan
```

**Comment by praesoll** [comment]
Hi Dimitry, thank you for your answers.

 

Your first finding and hint solved the problem:

 
WARNUNG: C:\Users\Rainer Präsoll\.ganttproject (Zugriff verweigert)
java.io.FileNotFoundException: C:\Users\Rainer Präsoll\.ganttproject (Zugriff verweigert)

 

I do have full admin-rights for the user folder, BUT it was “hidden” (what is default in Windows 10) and it was marked “read-only” (for whatever reason). I changed both.

 

Now everything (date format, recent projects, logo) is working.

 

Thank you a lot – have a great weekend!

 

Regards

Rainer

 

PS: donation follows!

 

 

 

 

Von: Dmitry Barashev [mailto:notifications@github.com] 
Gesendet: Samstag, 5. August 2017 02:00
An: bardsoftware/ganttproject <ganttproject@noreply.github.com>
Cc: praesoll <rainer.praesoll@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [bardsoftware/ganttproject] Open last project (#1446)

 

Thanks for the log.
These lines

WARNUNG: C:\Users\Rainer Präsoll\.ganttproject (Zugriff verweigert)
java.io.FileNotFoundException: C:\Users\Rainer Präsoll\.ganttproject (Zugriff verweigert)

explain why options are not saved: you don't have permission to write the options file, for whatever reason.

With respect to the file reopening, I believe the file is really missing. Can you type this command in the command prompt and paste the output here?

dir /B C:\Users\Rainer Präsoll\Documents\PROJEKTE\Der Standard\Redaktion FLOW\Ganttproject\FLOW.gan

**Comment by dbarashev** [comment]
I submitted a new issue about checkign write permissions: #1449 
Closing this one.
