### ISSUE TITLE
ganttproject-eclipsito-config.xml not copied to dist-bin

### ISSUE THREAD

**Issue by silvanheller** [bardsoftware/ganttproject#1451]
OS: Ubuntu 16.04 LTS
Gradle Version: Latest (4.1)

`gradle distBin` does not copy ganttproject-eclipsito-config.xml to the dist-bin folder. `gradle runApp` works perfectly, and after copying ganttproject-eclipsito-config.xml to the dist-bin folder, i can launch ganttproject correctly with the bash-script.

Steps to reproduce (on a clean repo)
`cd ganttproject-builder`
`gradle updateLibs`
`gradle distBin`
`./ganttproject`
will log:

org.bardsoftware.eclipsito.Boot main
INFO: No options passed to Eclipsito. Searching for config in ganttproject-eclipsito-config.xml
Aug 15, 2017 4:24:17 PM org.bardsoftware.eclipsito.Boot main
SEVERE: Eclipsito configuration file=ganttproject-eclipsito-config.xml has not been found!
java.lang.RuntimeException: Eclipsito configuration file=ganttproject-eclipsito-config.xml has not been found!
	at org.bardsoftware.eclipsito.Boot.main(Boot.java:101)

**Comment by dbarashev** [comment]
If I read this correctly

```
gradle distBin
./ganttproject
``` 

you need to replace `./ganttproject` with `cd dist-bin && ./ganttproject`

**Comment by dbarashev** [comment]
Ah, I see it doesn't work with `cd dist-bin` either

**Comment by Champal** [comment]
I confirm that `gradle DistBin` doesn't copy `ganttproject-eclipsito-config.xml`
Same problem as #1427 

```
C:\ganttproject\ganttproject-builder\dist-bin>ganttproject.bat
avr. 06, 2018 11:29:01 AM org.bardsoftware.eclipsito.Boot main
INFOS: No options passed to Eclipsito. Searching for config in ganttproject-eclipsito-config.xml
avr. 06, 2018 11:29:01 AM org.bardsoftware.eclipsito.Boot main
GRAVE: Eclipsito configuration file=ganttproject-eclipsito-config.xml has not been found!
java.lang.RuntimeException: Eclipsito configuration file=ganttproject-eclipsito-config.xml has not been found!
        at org.bardsoftware.eclipsito.Boot.main(Boot.java:101)

C:\ganttproject\ganttproject-builder\dist-bin>cp ..\ganttproject-eclipsito-config.xml .

C:\ganttproject\ganttproject-builder\dist-bin>ganttproject.bat
=> run fine
```
