### ISSUE TITLE
Cannot update Resources on task

### ISSUE THREAD

**Issue by sprevot** [bardsoftware/ganttproject#1457]
On the "Resources" tab of a task I have 2 resources already assigned.
I click on the Resource Name line 2, click Delete, click Ok : the task is not saved (2 resources are still appearing).
Try with project attached, task 168.
[Planning_Recette_Transporeon 20170906.zip](https://github.com/bardsoftware/ganttproject/files/1281705/Planning_Recette_Transporeon.20170906.zip)

I'm using GanttProject 2.8.5 Pilsen (build 2179) on Windows.

**Comment by dbarashev** [comment]
Hi,
it seems to be reproducible if resource dropdown was expanded in the table cell prior to deleting. Can you try selecting the second line by clicking e.g. cell in "id" column?

**Comment by sprevot** [comment]
Yes by clicking the "ID" column then doing Delete and Ok the Resources column is updated correctly.

**Comment by dbarashev** [comment]
Duplicates #612
