### ISSUE TITLE
GanttProject 2.8.5 is not loading

### ISSUE THREAD

**Issue by sprevot** [bardsoftware/ganttproject#1458]
I've installed GanttProject 2.8.5 (build 2179) yesterday on a Windows 7 32 bits PC.
Today the program is not loading: the process ganttproject.exe loads 2 seconds then closes.
After a reboot of the PC, I'm still unable to launch the program.
Is there any way to fix this problem?

**Comment by dbarashev** [comment]
Can you try [running ZIP distro](https://github.com/bardsoftware/ganttproject/wiki/Installing-from-ZIP) and see what is printed to console and to the log file when you run `ganttproject.bat`?

**Comment by sprevot** [comment]
I've launched ganttproject.bat and the program load correctly.
Attached is the log file.
[ganttproject.log.zip](https://github.com/bardsoftware/ganttproject/files/1285319/ganttproject.log.zip)

**Comment by dbarashev** [comment]
Log produced by successful run doesn't provide too much useful information :) It would be nice to see the log produced when it doesn't work.

**Comment by sprevot** [comment]
Sure, but I thought it could help :)
This morning I noticed the exe file from the ZIP distro is loading correctly contrary to the one in the Program Files\GanttProject-2.8\ folder.
