### ISSUE TITLE
Chinese glyphs do not show on the chart images in PDF export

### ISSUE THREAD

**Issue by qiweihu** [bardsoftware/ganttproject#1460]
I have the latest version of GanttProject.  As you can see in picture 1, I created a simple project flow in Chinese, and everything seems to work fine. However, wheni tried to export the file to PDF (even choosing a Chinese font),  the PDF does not display the text correctly. 

![g1](https://user-images.githubusercontent.com/31975886/30462707-fb96853e-99f9-11e7-92f1-33953a763cf7.PNG)

![g2](https://user-images.githubusercontent.com/31975886/30462720-0ed85564-99fa-11e7-9e56-b1cbdd781d99.PNG)

**Comment by dbarashev** [comment]
Did you choose Chinese font as a replacement for Arial in the PDF export settings (see screenshot)?

![image](https://user-images.githubusercontent.com/2028330/30463319-8e7341a2-99d3-11e7-9a4e-e3e55704f20a.png)

**Comment by qiweihu** [comment]
Yes. " (even choosing a Chinese font)". I chose the replacement font, then page 2 "task report(page 1 and 2)" display correctly, but not the gantt chart(page 3 and 4).
![g3](https://user-images.githubusercontent.com/31975886/30463748-2d1dfd98-9a00-11e7-899e-5377baca902c.PNG)

**Comment by kenmjlee** [comment]
I also met this issue for a long time. 
My colleagues and I run ganttproject on Windows and Mac (A Chinese ver. of MacOS and an English one). 

That the ganttproject runs on Windows or Chinese macOS works well as @qiweihu said. 
![image](https://user-images.githubusercontent.com/1215035/33366296-c7f356aa-d525-11e7-8077-2a116a767616.png)
![image](https://user-images.githubusercontent.com/1215035/33366303-cf4a636c-d525-11e7-80ab-83af6d9193fa.png)


On the English macOS, pages of tasks and gantt cannot display the Chinese in PDF. Another issue on English macOS is that I cannot choose Chinese Font in the substitution list, so I cannot test further.

**Comment by zhuang2k2** [comment]
I just used GanttProject 2.8.9 to check this bug.
This bug still exists in version 2.8.9.
My test environment:
OS: Windows 10
Software: GanttProject 2.8.9
Export to PDF and used replaced font which can show chinese
Problem: Chinese glyphs do not show on the chart images in PDF export

**Comment by dbarashev** [comment]
Can you please show the screenshots of your GanttProject window, Application UI page of the settings dialog and the settings page of PDF Export tool? And the result of exporting (PDF file)? Thanks!

**Comment by zhuang2k2** [comment]
1.  Application UI 
![ui](https://user-images.githubusercontent.com/42781804/44799972-da1e1600-abe7-11e8-8051-38fb455e2379.png)

2.  settings page of PDF Export tool
![pdf_1](https://user-images.githubusercontent.com/42781804/44800013-f1f59a00-abe7-11e8-8880-8e2c8f6a29d0.png)
![pdf_2](https://user-images.githubusercontent.com/42781804/44800021-f5892100-abe7-11e8-8012-8d589a31eb8a.png)

3. Export to PDF result
[document.pdf](https://github.com/bardsoftware/ganttproject/files/2332845/document.pdf)

4. Export to HTML
![export_html](https://user-images.githubusercontent.com/42781804/44800191-629cb680-abe8-11e8-9249-5c67151bc875.png)

5. Export to image can show Chinese correctly as HTML.

6. Gantt Project for this test
[Chinese_Test.zip](https://github.com/bardsoftware/ganttproject/files/2332860/Chinese_Test.zip)
Inside the zip file is the Chinese_test.gan which is saved by GanttProject 2.8.9.

Thanks for your help.

**Comment by dbarashev** [comment]
Can you please set Application font (and maybe Base Chart font as well) in the Application UI settings to font with Chinese glyphs (e.g.  WengQuanYi Micro Hei) ?

**Comment by zhuang2k2** [comment]
Test Report.
I download set application font  "WengQuanYi Micro Hei" from internet to test.
This time I can successfully export PDF with Chinese

Below two settings are must.
1. Application font = WengQuanYi Micro Hei
![ui](https://user-images.githubusercontent.com/42781804/44826051-e6ce5880-ac3f-11e8-83a5-22846282f0c2.png)

2. PDF export font = WengQuanYi Micro Hei
![pdf_2](https://user-images.githubusercontent.com/42781804/44826184-71af5300-ac40-11e8-8d7a-8a02c4a22ca2.png)

Selecting other Chinese fonts cannot export the correct result.

**Comment by dbarashev** [comment]
The story with fonts is more complex. It is not that "PDF export font = WengQuanYi Micro Hei, [all] other Chinese fonts cannot export the correct result".

First, in PDF export we can only use TrueType/OpenType fonts which are accessible as font files in one of the predefined folders (for Windows, it is C:/windows/fonts) . Second, font needs to embeddable, and not all fonts are. However, there are definitely fonts which can be used in PDF export other than WengQuanYi Micro Hei.
