### ISSUE TITLE
can't delete a resource from a task!

### ISSUE THREAD

**Issue by srwhitman** [bardsoftware/ganttproject#1464]
When I go into a task assign a resource and save the task and later delete that resource, it still shows up on the timeline and later when I go into the task itself its still there!

**Comment by dbarashev** [comment]
When you say "delete that resource", do you mean that you really delete the resource itself, or that you remove resource from the resources assigned to the task?

**Comment by srwhitman** [comment]
The latter - I tried to delete a resource from the task. I;'ve got version 2.8.5.  

    On Wednesday, October 11, 2017 9:11 AM, Dmitry Barashev <notifications@github.com> wrote:
 

 When you say "delete that resource", do you mean that you really delete the resource itself, or that you remove resource from the resources assigned to the task?—

**Comment by dbarashev** [comment]
So, this seems to be a duplicate of #612 
Workaround: don't click dropdown with the resouce name if you need to delete resource assignment.
