### ISSUE TITLE
Small error in Swedish translation

### ISSUE THREAD

**Issue by SvenTaveby** [bardsoftware/ganttproject#1470]
In "Custom Fields Manager" (="Bestäm Valfria Fält" (perhaps)) the text is "Show markerade" and "Hide markerade".
Suggested translation "Visa markerade" and "Göm markerade".
![show_hide](https://user-images.githubusercontent.com/33726582/32899536-893006be-caeb-11e7-8c0f-334653a79ee3.JPG)

**Comment by dbarashev** [comment]
I changed translations in Crowdin. They should become available in the next updates.
