### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by derarnold** [bardsoftware/ganttproject#1471]
Hi.

On HiDPI screens, your fine software is not usable. It is to small. Unfortunately, setting -DDsun.java2d.uiScale=2 in the start script does not work.

Can you please help?
Thanks

Using ubuntu with openjdk version "1.8.0_151"

**Comment by dbarashev** [comment]
http://ganttproject.blogspot.com/2017/03/ganttproject-284-scalable-ui-on-high.html

**Comment by derarnold** [comment]
Cool!!! Nice project and thank you for the quick response!
