### ISSUE TITLE
When deleting a predecessor, the date stays the same

### ISSUE THREAD

**Issue by derarnold** [bardsoftware/ganttproject#1474]
Hi.

I am not sure if this is a bug, but it makes my life hard:

- i have a task (A) starting today
- I link that task (A) to another task (B), so task (A) is shifted two weeks in the future
-> When I delete the link between the tasks, I would expect, that task (A) falls beck to the earliest possible date. Right now, it stays on that date.

Since we can set an earliest start date for a task, the above mentioned behavior seems wrong.

In practical use, this behavior forces me to go through all tasks manually and see, if they start the earliest date possible.

Oliver

**Comment by derarnold** [comment]
NICE! Exactly what I needed. I did not understand that you need the set the date. I thought it was counter productive. Thanks!

BTW. Do you have an estimate about the next release date? I want to contribute the german holidays for 2018 and 2019

**Comment by dbarashev** [comment]
We'll certainly need to publish update with new calendars somewhere aroung the New Year, so you're welcome. No any planned date though.
