### ISSUE TITLE
Custom Date Format

### ISSUE THREAD

**Issue by gituncar** [bardsoftware/ganttproject#1477]
Hi, if possible add on print like this format

tue, 31mar2018

ddd, dd/mm/yyyy

![image 1](https://user-images.githubusercontent.com/7705197/33433826-238746e0-d5ab-11e7-81f7-a0fc7095a1a0.png)

**Comment by dbarashev** [comment]
I can't say that I celarly understand the question, but if you meant that you want dates to be formatted like "Thu 30Nov2018" (today's date) then use EEE ddMMMyyyy
