### ISSUE TITLE
INFO Se ha cambiado la fecha de inicio de algunas tareas (72 de 77)

### ISSUE THREAD

**Issue by gerardochi** [bardsoftware/ganttproject#1479]
Severity | Message
-- | --
INFO | Se ha cambiado la fecha de inicio de algunas tareas (72 de 77). Mira            los detalles a continuación.¿Qué            significa esto?
WARNING | La tarea Identificar período para pruebas en D18: era 17/11/17            0:00, ahora es 22/11/17 0:00
WARNING | La tarea Realizar pruebas integrales SD: era 5/12/17 0:00,            ahora es 7/12/17 0:00
WARNING | La tarea Solicitar fechas para implementación: era 27/11/17            0:00, ahora es 30/11/17 0:00
WARNING | La tarea Preparativos: era 19/01/18 0:00, ahora es 29/01/18            0:00
WARNING | La tarea Ejecutar procesos de archivado y borrado de datos: CO:            era 27/12/17 0:00, ahora es 2/01/18 0:00
WARNING | La tarea Reorganización y Estrategia P18: era 2/02/18            0:00, ahora es 12/02/18 0:00
WARNING | La tarea Reunión de seguimiento: era 11/12/17 0:00,            ahora es 13/12/17 0:00
WARNING | La tarea Implementación y puesta en marcha (P18): era 12/12/17            0:00, ahora es 15/12/17 0:00
WARNING | La tarea Diseñar y crear estructuras de información:            era 21/11/17 0:00, ahora es 23/11/17 0:00
WARNING | La tarea Generar segunda lista de tablas candidatas a            reorganización: era 8/12/17 0:00, ahora es 12/12/17            0:00
WARNING | La tarea Consolidar documentos de proyecto: era 18/01/18            0:00, ahora es 25/01/18 0:00
WARNING | La tarea Entregable: Informe Final: era 18/01/18 0:00,            ahora es 29/01/18 0:00
WARNING | La tarea Realizar pruebas integrales CO: era 6/12/17 0:00,            ahora es 8/12/17 0:00
WARNING | La tarea Ejecutar procesos de archivado y borrado de datos: BC:            era 15/12/17 0:00, ahora es 21/12/17 0:00
WARNING | La tarea …: era 9/03/18 0:00, ahora es 19/03/18            0:00
WARNING | La tarea Entregar Actas de acuerdo de archivado: era 12/12/17            0:00, ahora es 19/12/17 0:00
WARNING | La tarea Entregable: Resultado de ejecuciones: era 11/01/18            0:00, ahora es 19/01/18 0:00
WARNING | La tarea …: era 2/02/18 0:00, ahora es 12/02/18            0:00
WARNING | La tarea …: era 19/01/18 0:00, ahora es 29/01/18            0:00
WARNING | La tarea Diseñar y crear variantes para Archiving: era 16/11/17            0:00, ahora es 21/11/17 0:00
WARNING | La tarea Reorganización y Estrategia Q18 (Pruebas integrales):            era 26/01/18 0:00, ahora es 5/02/18 0:00
WARNING | La tarea Implementación de Avoidance: era 27/11/17            0:00, ahora es 30/11/17 0:00
WARNING | La tarea Documentar fase de proyecto: era 27/11/17 0:00,            ahora es 29/11/17 0:00
WARNING | La tarea Convocar reunión de seguimiento: era 12/12/17            0:00, ahora es 19/12/17 0:00
WARNING | La tarea Reunión de seguimiento: era 11/01/18 0:00,            ahora es 18/01/18 0:00
WARNING | La tarea Generar tercera lista de tablas candidatas a            reorganización: era 10/01/18 0:00, ahora es 16/01/18            0:00
WARNING | La tarea Importar órdenes a P18: era 12/12/17 0:00,            ahora es 19/12/17 0:00
WARNING | La tarea Implementar Avoidance en P18: era 12/12/17 0:00,            ahora es 18/12/17 0:00
WARNING | La tarea Documentación y soporte: era 12/01/18 0:00,            ahora es 19/01/18 0:00
WARNING | La tarea Entregable: Resultado de pruebas integrales: era 11/12/17            0:00, ahora es 15/12/17 0:00
WARNING | La tarea Implementar Avoidance en Q18: era 29/11/17 0:00,            ahora es 1/12/17 0:00
WARNING | La tarea Entregable: Informe Inicial: era 10/11/17 0:00,            ahora es 16/11/17 0:00
WARNING | La tarea Diseño y configuración de la solución (D18):            era 13/11/17 0:00, ahora es 16/11/17 0:00
WARNING | La tarea Realizar entrevistas/pláticas con key users:            era 10/11/17 0:00, ahora es 14/11/17 0:00
WARNING | La tarea Realizar checklist y validar respaldo de D18: era 13/11/17            0:00, ahora es 16/11/17 0:00
WARNING | La tarea Documentar fase de proyecto: era 11/01/18 0:00,            ahora es 17/01/18 0:00
WARNING | La tarea Reorganización: era 19/01/18 0:00, ahora            es 29/01/18 0:00
WARNING | La tarea Validar requerimientos: era 12/12/17 0:00,            ahora es 18/12/17 0:00
WARNING | La tarea Ejecutar procesos de archivado y borrado de datos: SD:            era 20/12/17 0:00, ahora es 26/12/17 0:00
WARNING | La tarea Validar e implementar actualizaciones a programas de            archiving: era 14/11/17 0:00, ahora es 17/11/17 0:00
WARNING | La tarea Obtener datos estadísticos de ejecuciones: era 10/01/18            0:00, ahora es 15/01/18 0:00
WARNING | La tarea Distribuir datos por período y objeto: era 8/11/17            0:00, ahora es 9/11/17 0:00
WARNING | La tarea Ejecutar procesos de archivado y borrado de datos: FI:            era 4/01/18 0:00, ahora es 9/01/18 0:00
WARNING | La tarea Analizar base de datos, tablas y objetos en P18: era 7/11/17            0:00, ahora es 8/11/17 0:00
WARNING | La tarea Validar configuración y liberar órdenes de transporte:            era 24/11/17 0:00, ahora es 28/11/17 0:00
WARNING | La tarea Implementar solución de archiving en Q18: era 29/11/17            0:00, ahora es 1/12/17 0:00
WARNING | La tarea Diseñar y crear variantes para Archiving: era 14/12/17            0:00, ahora es 20/12/17 0:00
WARNING | La tarea Pruebas y preparación final (Q18): era 27/11/17            0:00, ahora es 30/11/17 0:00
WARNING | La tarea Realizar checklist y validar respaldo de P18: era 12/12/17            0:00, ahora es 15/12/17 0:00
WARNING | La tarea Ejecutar procesos de archivado y borrado de datos: MM:            era 19/12/17 0:00, ahora es 25/12/17 0:00
WARNING | La tarea Documentar fase de proyecto: era 11/12/17 0:00,            ahora es 14/12/17 0:00
WARNING | La tarea Workshop: era 18/01/18 0:00, ahora es 26/01/18            0:00
WARNING | La tarea Iniciar configuración técnica de objetos de archiving:            era 15/11/17 0:00, ahora es 20/11/17 0:00
WARNING | La tarea Realizar checklist y validar respaldo de Q18: era 28/11/17            0:00, ahora es 30/11/17 0:00
WARNING | La tarea Generar primera lista de tablas candidatas a            reorganización: era 23/11/17 0:00, ahora es 27/11/17            0:00
WARNING | La tarea Dar mantenimiento o concluir con procesos pendientes:            era 12/01/18 0:00, ahora es 19/01/18 0:00
WARNING | La tarea Convocar reunión de seguimiento: era 27/11/17            0:00, ahora es 30/11/17 0:00
WARNING | La tarea Documentar fase de proyecto: era 12/12/17 0:00,            ahora es 19/12/17 0:00
WARNING | La tarea Obtener estadísticas iniciales: era 13/12/17            0:00, ahora es 19/12/17 0:00
WARNING | La tarea Entregable: Diseño de la Solución: era 27/11/17            0:00, ahora es 30/11/17 0:00
WARNING | La tarea …: era 26/01/18 0:00, ahora es 5/02/18            0:00
WARNING | La tarea Implementar Avoidance en D18: era 28/11/17 0:00,            ahora es 30/11/17 0:00
WARNING | La tarea Realizar checklist de landscape: era 9/11/17 0:00,            ahora es 13/11/17 0:00
WARNING | La tarea Probar y validar ejecuciones de archiving (Pruebas            unitarias): era 1/12/17 0:00, ahora es 5/12/17 0:00
WARNING | La tarea Realizar pruebas integrales BC y MM: era 4/12/17            0:00, ahora es 6/12/17 0:00
WARNING | La tarea Realizar pruebas unitarias de archiving (D18): era 22/11/17            0:00, ahora es 24/11/17 0:00
WARNING | La tarea Validar programas de archiving: era 9/11/17 0:00,            ahora es 10/11/17 0:00
WARNING | La tarea Validar y preparar casos para pruebas integrales:            era 30/11/17 0:00, ahora es 4/12/17 0:00
WARNING | La tarea Realizar pruebas integrales FI: era 7/12/17 0:00,            ahora es 11/12/17 0:00
WARNING | La tarea Obtener estadísticas preliminares de P18: era 6/11/17            0:00, ahora es 7/11/17 0:00
WARNING | La tarea Documentar fase de proyecto: era 10/11/17 0:00,            ahora es 15/11/17 0:00
WARNING | La tarea Entrenamiento y entrega de políticas: era 9/03/18            0:00, ahora es 19/03/18 0:00

**Comment by dbarashev** [comment]
So what we're supposed to do with this?

**Comment by gerardochi** [comment]
Aammm, fix the problema maybe???


De: Dmitry Barashev [mailto:notifications@github.com]
Enviado el: martes, 2 de enero de 2018 03:51 p. m.
Para: bardsoftware/ganttproject <ganttproject@noreply.github.com>
CC: Gerardo Chi Laguna <gerardo.chi@easconsulting.com.mx>; Author <author@noreply.github.com>
Asunto: Re: [bardsoftware/ganttproject] INFO Se ha cambiado la fecha de inicio de algunas tareas (72 de 77) (#1479)


So what we're supposed to do with this?

**Comment by dbarashev** [comment]
Can you explain what is the problem in your opinion?
These messages are all marked as "warning" and their meaning is to let you know that something has changed in your project. It is normal that import from other formats, in particular from MS Project, changes task dates. You may find the detailed explanation here: http://ganttproject.blogspot.ru/2017/03/troubleshooting-ms-project-import.html

Use your own judgement to decide if the changes which you see are reasonable. If you do believe that none of the cases in the linked blog post is your case then please send us the original MS Project file, as warning message suggests (I hope it did).
