### ISSUE TITLE
Does it work with Java 9 ?

### ISSUE THREAD

**Issue by JeremyBouchard** [bardsoftware/ganttproject#1480]
I'm trying to launch GanttPrject but it keep saying that I need Java7 or higher... I have java 9 fresh installed on my PC and it work for other java apps... Windows Path environement variable seem ok and "Launching as administrator" doesn't change anything.

ps : sorry not native english

**Comment by dbarashev** [comment]
It might be possible that launcher application was not aware of Java 9 existence at the moment of last GanttProject release. I'll check it in a few days. Meanwhile you can try [using ZIP distro](https://github.com/bardsoftware/ganttproject/wiki/Installing-from-ZIP)

**Comment by PMudra** [comment]
I can confirm that I have the same issue.
```
>java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

After installing the latest JRE 8 it works for me.

**Comment by dbarashev** [comment]
Hello folks,
may I ask you to test the release candidate build of GanttProject 2.8.6 with Java 9? 
You can download Windows installer from Dropbox: https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0

This build should be stable and is nearly a release -- we plan to update translations only in the release build. However, should you find any show stoppers, please let me know.

**Comment by PMudra** [comment]
I was able to install and run the the application. Unfortunately I have no time for further testing right now 😞
