### ISSUE TITLE
Import from CSV file does not recognize international characters

### ISSUE THREAD

**Issue by jsmota55** [bardsoftware/ganttproject#1481]
Importing from CSV file does not recognize international characters, only ASCII ones.
GanttProject 2.8.5 Pilsen (build 2179) running in Windows 10
You can check the attached files.
Thanks.
[test.zip](https://github.com/bardsoftware/ganttproject/files/1627043/test.zip)
![gantt](https://user-images.githubusercontent.com/35379366/34889048-89b8b134-f7c4-11e7-9743-54a0c20807a8.png)

**Comment by dbarashev** [comment]
In this file 8-bit Windows-1252 encoding is used. GanttProject reads and writes files in Unicode (UTF-8) encoding. You can convert file to UTF-8 e.g. by opening it in Notepad and using its "Save As" menu action.
