### ISSUE TITLE
End Dates Calculated Incorrectly

### ISSUE THREAD

**Issue by paulmccarthy** [bardsoftware/ganttproject#1482]
Create a new Task. Select 2018-01-16 as the start date. Set a duration of 40 days. End date is 2018-03-71

Running:
OS X Yosemite 10.10.5 (14F2511)
GanttProject 2.8.5 Pilsen (build 2179)
Java 8 Update 102

![gantt](https://user-images.githubusercontent.com/9063336/34983549-dc8a3408-faa5-11e7-8838-d9121660e3bf.png)

**Comment by dbarashev** [comment]
You need to lowercase "D" in your custom date format. "D" stands for "day of the year". What you want is "yyyy-MM-dd"
