### ISSUE TITLE
Moving tasks in android application

### ISSUE THREAD

**Issue by Mrjames85** [bardsoftware/ganttproject#1484]
I am unable to move tasks in the android app.  When long pressing on the task then selecting the "move" button the arrow buttons don't move anything, and selecting the check mark within the same menu also does nothing.  

I am running android 7.1.1. 
On a Note 8 (SM- N950U)

**Comment by dbarashev** [comment]
We do not have any official Android app, sorry. If you're using a thord-party Android app which can read GanttProject files, please file this issue to their issue tracker and/or contact their developers.
