### ISSUE TITLE
Debian dependencies issue

### ISSUE THREAD

**Issue by vasyugan** [bardsoftware/ganttproject#1485]
Through java-package I have installed oracle-java8-jdk 

However, the ganttproject deb won't install as it declares a dependency on:

openjdk-7-jre | openjdk-8-jre | oracle-java7-jre | oracle-java8-jre | oracle-java8-installer

but not on the full jdks as an alternative.

**Comment by dbarashev** [comment]
Hello,
may I ask you to test the release candidate build of GanttProject 2.8.6 with Java 9?
You can download deb package from Dropbox: https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0

This build should be stable and is nearly a release -- we plan to update translations only in the release build. However, should you find any show stoppers, please let me know.
