### ISSUE TITLE
GanttProject Source Code

### ISSUE THREAD

**Issue by emckelle** [bardsoftware/ganttproject#1492]
Hi. I'm new to GanttProject. I created a schedule and I want to export it to excel. But everytime I exported it as .csv file and open it to excel, it only shows the left side. The graphical chart is gone. I would like to see the graphical chart on the right side. Can you please tell me how to do it. I have source code of GanttProject, I can modify it if that's possible, but I don't know what file I am going to modify. It's a JAVA language. Big thanks for the help!

**Comment by emckelle** [comment]
But is there a way to modify its source code? for the gan file to import properly to excel, with its graphical chart on the right side

**Comment by dbarashev** [comment]
As I wrote above, if you want to hack GanttProject, please follow the development guide to set up things. However, you're going to tackle a pretty challenging problem. If I were you, I would start learning Java from something more simple.

**Comment by emckelle** [comment]
Ok big thanks. One more thing, do you have any suggestion of software that can create gantt schedule and can import to excel together with the chart.
