### ISSUE TITLE
Adjustments to Search

### ISSUE THREAD

**Issue by dkelly-sighter** [bardsoftware/ganttproject#1496]
@dbarashev what were your thoughts on other search functionality? I'm kind of newish to java swing so this seemed like a perfect place to start getting my hands a bit dirty. I'm more than willing to try and implement some of those features that you want.

**Comment by dbarashev** [comment]
Hi, I have sent you an invitation to join ganttproject-team.slack.com if you don't mind :) It is easier to chat there than using Github issues.
