### ISSUE TITLE
Incorrect start - end date when when PDF report

### ISSUE THREAD

**Issue by alexey-baranov** [bardsoftware/ganttproject#1499]
Hello !
Today 24 feb 2018 . My project started on 22 feb 2018 and will finished on 27 feb 2019

Look at from - to date into screenshot please
http://imgur.com/yQQsL0Gl.png

It is very uncomfortable to change dates every time when export to pdf. Thnaks

**Comment by dbarashev** [comment]
These date are not incorrect. The range in the export corresponds to the date range of the currently visible portion of the Gantt chart and gives a sort of "what you see is what you get" guarantee.

There is an existing ticket #410 which requests ability to choose the project range with a single click. Perhaps that's what you really want.
