### ISSUE TITLE
Japanese Translation Suggestion

### ISSUE THREAD

**Issue by rikaojisan** [bardsoftware/ganttproject#1502]
in
ganttproject/ganttproject/data/resources/language/i18n_ja_JP.properties

fron
customPropertyDialog.showSelected = $Show \u3092\u9078\u629E

to
customPropertyDialog.showSelected = \u9078\u629E\u3092\u8868\u793A

**Comment by dbarashev** [comment]
May I ask you to introduce these changes into [Japanese translation on Crowdin](https://crowdin.com/translate/ganttproject/27683/en-ja)? We export these files from Crowdin, and introducing direct changes into properties files is a little bit troublesome.

See also: [translation guidelines](https://github.com/bardsoftware/ganttproject/blob/wiki/TranslationGuidelines.md)
