### ISSUE TITLE
"Import Resources" option dissapeared in version 2.8.6 (build 2231)

### ISSUE THREAD

**Issue by alex-bia** [bardsoftware/ganttproject#1506]
Trying to import a list of resources in version 2.8.6 we discovered that the option Resources / Import Resources no longer appears in the menu. Why...?!?!
We could not find an alternative option to do the same in other menus so we got back to 2.8.5.
Was it moved to somewhere else?

**Comment by dbarashev** [comment]
Import Resources didn't work properly and duplicated functionality of `.gan` files import. Besides, there is cross-project clipboard which also works for resources.

So, you can use Copy+Paste or `Import > GanttProject files`

**Comment by alex-bia** [comment]
Understood. Thanks!
