### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by procura7** [bardsoftware/ganttproject#1507]
Hello,
Thank you for providing useful products.
I also wanted to help, I made a Japanese translation.　Please check it.

[ja_JP.zip](https://github.com/bardsoftware/ganttproject/files/1846201/ja_JP.zip)

**Comment by dbarashev** [comment]
Hello,
thanks for this, but we use special service called Crowdin for crowdsourcing translations. We export properties files from that service, and the reverse process (apply changes made outside of Crowdin) is pretty time-consuming and error-prone. May I kindly ask you to do these changes in Crowdin? You can find the instructons here: https://github.com/bardsoftware/ganttproject/blob/wiki/TranslationGuidelines.md

**Comment by procura7** [comment]
Hello, dbarashev-san.
Thank you for your reply.
Can I edit directly without confirmation to other (Japanese) users?

**Comment by dbarashev** [comment]
Sorry for the late answer, I hope you already settled down the things in Crowdin. 
If you have no doubts that your translation is better, go ahead and edit directly. But in case of doubts it is makes sense to discuss the changes.
