### ISSUE TITLE
Milestone date display -- two dates, should be one

### ISSUE THREAD

**Issue by cepheid666** [bardsoftware/ganttproject#1515]
When including inline date labels on the chart, milestones are displayed with both start and end dates.  Since these are zero-duration events, this looks awkward (and is redundant).  Ideally, milestones should have single dates displayed rather than a hyphenated range.

Could this be implemented?

**Comment by dbarashev** [comment]
Nice :) Thanks for reporting!

**Comment by cepheid666** [comment]
Thanks for fixing this! One request: could you add back the brackets around the date?  Or make it optional to include them?  I actually preferred the brackets even for a single date.  Thanks!
