### ISSUE TITLE
Error in Norwegian Language translation

### ISSUE THREAD

**Issue by PatrickGjo** [bardsoftware/ganttproject#1518]
Hi, in the PERT diagram the norwegian word "Start" (same as in english)has been wrongly translated with the polish word "Poczatek".
<img width="137" alt="skjermbilde 2018-04-07 kl 16 14 34" src="https://user-images.githubusercontent.com/38160075/38455932-e2b1db6a-3a7e-11e8-8f1e-e74efcc42d24.png">

**Comment by dbarashev** [comment]
Thanks for reporting! I have fixed it in the [corresponding Crowdin entry](https://crowdin.com/translate/ganttproject/27683/en-no#q=start) and it should appear in GanttProject repository after the next export (before next bugfix update).

**Comment by PatrickGjo** [comment]
Thanks, sorry for not responding.
BR Patrick

Sendt fra min mobiltelefon

9. apr. 2018 kl. 01:24 skrev Dmitry Barashev <notifications@github.com<mailto:notifications@github.com>>:


Thanks for reporting! I have fixed it in the corresponding Crowdin entry<https://crowdin.com/translate/ganttproject/27683/en-no#q=start> and it should appear in GanttProject repository after the next export (before next bugfix update).
