### ISSUE TITLE
FTP description string is missing in the English translation but exists in Japanese

### ISSUE THREAD

**Issue by procura7** [bardsoftware/ganttproject#1524]
Hello,
"optionPage.impex.ftp.description" keyword is empty in the English version, but the Japanese version has translation data.
So, the width of the setting screen of the Japanese version is very wide.
But, because crowdin does not have the keyword, we can not change Japanese translation.

English version
![image](https://user-images.githubusercontent.com/37786552/38973253-c8f44a7c-43df-11e8-8e82-a28ba1369144.png)

![image](https://user-images.githubusercontent.com/37786552/38973278-f3153442-43df-11e8-9b77-b477dfc8aad4.png)

Japanese Version
![image](https://user-images.githubusercontent.com/37786552/38973256-cf43218c-43df-11e8-9e89-25714f31622d.png)

![image](https://user-images.githubusercontent.com/37786552/38973249-c30fe030-43df-11e8-9451-2ec89dd72b9e.png)

**Comment by dbarashev** [comment]
Thanks for reporting. I don't think that this description is needed in any language, so I will just remove the usage in the code.
