### ISSUE TITLE
Double click in task name cell clears task name

### ISSUE THREAD

**Issue by DecorteT** [bardsoftware/ganttproject#1525]
GanttProject 2.8.7 Pilsen (build 2256) 
Double clicking the task to modify the description should not delete the description right away.

**Comment by DecorteT** [comment]
Seems to be solved after restart

**Comment by DecorteT** [comment]
But keeps coming back all the time

**Comment by dbarashev** [comment]
Did you mean "double click in the task name cell clears task name"? Because it doesn't delete a task (or I don't understand how to reproduce it).

**Comment by dbarashev** [comment]
Thanks for clarification and reporting! This doesn't seem to be a regression comparing to 2.8.6 so we won't do anything urgent, but it is rather annoying so we'll make the double click in particular and editing start with mouse in general better in the next update.
Meanwhile, F2 key must be a good way to start editing without clearing the value.

**Comment by DecorteT** [comment]
Great, thank you.

**Comment by dbarashev** [comment]
We had to compiel a new build of 2.8.7 because of other usabiity issue, and fix of this one went into the this new build as well. Double click now opens task properties, single quick in a selected cell (or two slow consecutive clicks on a cell) start editing without clearing the value.
