### ISSUE TITLE
Selecting a task on mouse-click

### ISSUE THREAD

**Issue by DecorteT** [bardsoftware/ganttproject#1528]
GanttProject 2.8.7 Pilsen (build 2262) (related to bug fix #1525)
Selecting a task immediately enters the description line.
As a result it is not straightforward to select a task with, for example, the intention to delete it. 
A workaround is selecting the tasks with the help of the arrow keys, but on mouse click would make more sense.

**Comment by DecorteT** [comment]
Another workaround is right-click - which is closer to expected use

**Comment by figonacci** [comment]
Same here, very annoying.

My working workaround is to enlarge enddate column, and to click in the "empty space".

**Comment by dbarashev** [comment]
In fact, you can click any column which is not the same as previously seelected one. Sorry about this issue, we'll publish GP 2.8.8 with this and a few other fixes soon.

**Comment by marklinmao** [comment]
OK, is it possible to download previous version somewhere? The official website only provide the latest one which is buggy now.

**Comment by dbarashev** [comment]
All binaries are available here on GitHub: https://github.com/bardsoftware/ganttproject/releases

**Comment by dbarashev** [comment]
Hi everyone,
if you are eager to get it fixed now (I guess you are) you can try installing [intermediate build of GanttProject 2.8.8](https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0). 
It also fixes [a few other issues](https://github.com/bardsoftware/ganttproject/issues?q=is%3Aissue+is%3Aopen+label%3A%22Fix+committed+to+the+repository%22).

Windows, DEB and ZIP distros are available.

**Comment by DecorteT** [comment]
Hi, I tried the ganttproject-2.8.8-r2278.exe but it installs again GanttProject 2.8.7 Pilsen (build 2262), leaving me with the same issues.

**Comment by dbarashev** [comment]
Right, I forgot to increment a version number in the config, sorry. It installs 2.8.8, it just uses the older version if it is available in the installation folder. You can rename your existing "plugins-2.8.7" to "backup" in your GanttProject installation folder and  "plugins-2.8.8" to "plugins-2.8.7" to fix it right now.

**Comment by DecorteT** [comment]
Great, it works now, thank you very much.

**Comment by dbarashev** [comment]
Update: build 2298 is available from https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0

Added tooltips showing cell values and fixed clipboard operations.
