### ISSUE TITLE
Whitespace in Notes

### ISSUE THREAD

**Issue by lennartvdd** [bardsoftware/ganttproject#1531]
When writing task notes, a lot of whitespaces appears before and after the written text, after closing and reopening the project. No special editing/copy/pasting, etc. just write a note in the note field via the keyboard.
A newline and some spaces seem to be added after each edit, save, close and re-open of the project.

Happens in version 2.8.6, running on Windows 10, Java 10 (SE Runtime 18.3 build 10+46)
Also happens in version 2.8.7 (build 2262)

Perhaps related to #942

**Comment by dbarashev** [comment]
Thanks for reporting! Seems to be Windows-specific issue.

**Comment by lennartvdd** [comment]
Thanks for fixing!
