### ISSUE TITLE
Build BRANCH_2_8_X on Ubuntu 18.04 does not work

### ISSUE THREAD

**Issue by derarnold** [bardsoftware/ganttproject#1539]
Build on ubuntu 18.04 does not work.

Followed the steps on a fresh installed 18.04:
https://docs.ganttproject.biz/development/build/
on BRANCH_2_8_X

grade updateLibs throws error:

gradle updateLibs
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-3.4.1.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'updateLibs' not found in root project 'BRANCH_2_8_X'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.943 secs

**Comment by derarnold** [comment]
Sorry wrong directory. In the directory ganttproject-builde it shows:


/BRANCH_2_8_X/ganttproject-builder$ gradle updateLibs
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-3.4.1.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

FAILURE: Build failed with an exception.

* Where:
Build file '/home/oliver/BRANCH_2_8_X/ganttproject/build.gradle' line: 11

* What went wrong:
Error resolving plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.1.2']
> Could not GET 'https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/org.jetbrains.kotlin.jvm/1.1.2'.
   > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.544 secs

**Comment by dbarashev** [comment]
1. If you build `BRANCH_2_8_X` you don't need to run `updateLibs` task. 
1. It seems that you're building `master` because for `BRANCH_2_8_X` you don't need Kotlin, except for the tests. Did you checkout the sources from Git repository or downloaded from the release page?
1. Finally, the reported error seems to be related to the configuration of your JDK and OS. I don' know what are the reasons. Perhaps this link can help you: https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty
