### ISSUE TITLE
notice about openjdk-8-jre on download page

### ISSUE THREAD

**Issue by marekhattas** [bardsoftware/ganttproject#1544]
Hi, 
please add notice about version number of jre, which is required for running ganttproject on download page
http://www.ganttproject.biz/download/free

becouse in Ubuntu 16.04, openjdk-9-jre isn't working
ty

**Comment by dbarashev** [comment]
GanttProject requires Java 7+, it is written explicitly in the [release notes](https://www.ganttproject.biz/pilsen). DEB package depends on a choice of packages which provide Java Runtime:
```
Depends: openjdk-7-jre | openjdk-8-jre | openjdk-9-jre | openjdk-7-jdk | openjdk-8-jdk | openjdk-9-jdk | oracle-java7-jre | oracle-java8-jre | oracle-java9-jre | oracle-java7-jdk | oracle-java8-jdk | oracle-java9-jdk | oracle-java7-installer | oracle-java8-installer 
```
Any of them must be fine.
