### ISSUE TITLE
New Task Default Date is future Date

### ISSUE THREAD

**Issue by Sloriya** [bardsoftware/ganttproject#1545]
Hi  -- I am facing an issue in creating new task, the defaukt date is coming up as future date
In attached pic you can see the highlighted one.. 
(1) I have selected the option to current date in Project schedule option and this is selected to Automatically
(2) Also when i put predecessor task date doe not change

I am clueless and need to get this sorted out, any help will be much appreciated

![msp](https://user-images.githubusercontent.com/39232647/39964633-db6956a8-5699-11e8-9064-d8082b997051.JPG)
.  

![msp](https://user-images.githubusercontent.com/39232647/39964626-8c440ce4-5699-11e8-85cf-bf3da00ff2cc.JPG)

**Comment by dbarashev** [comment]
Did you really mean to post this issue to GanttProject issue tracker, not to some other product? We do not have such UI as shown on the image. We do not have any current date option with value "Automatically" in Project schedule, whatever it is.
