### ISSUE TITLE
Stucked task selection

### ISSUE THREAD

**Issue by Larquitec** [bardsoftware/ganttproject#1550]
Sometimes it's not easy to select a task an double click on it to edit its properties, it gets stucked on another task, not the one you would like to edit.
<img width="2048" alt="captura de pantalla 2018-05-18 a la s 10 57 16" src="https://user-images.githubusercontent.com/39413562/40244999-f74ba756-5a89-11e8-9554-63ea4587591f.png">

**Comment by dbarashev** [comment]
See issue #1528
