### ISSUE TITLE
Task name becomes partially visible after editing

### ISSUE THREAD

**Issue by DecorteT** [bardsoftware/ganttproject#1551]
GanttProject 2.8.8 Pilsen (build 2308)

Tooltips works fine now, that's great. But this does not completely solve the issue of incomplete task descriptions. After editing the description of a new task it is always cut off and only showing the first 7 or 8 digits. Even if there is enough space to show the complete line in the column. It would make sense to make use of the complete column right away. The description usually becomes visible after pushing indent/unindent buttons.

**Comment by DecorteT** [comment]
For your information: I noticed that moving the task up/down makes the description visible as well. This is usually less disturbing the planning than using indent/unindent. Annoying bug though.

**Comment by dwdfr** [comment]
+1
I confirm, this is an annoying bug
(I run the default look and feel under Windows 10, latest JRE)

**Comment by inor** [comment]
For me Ctrl+T (add new task) and Ctrl+Z (Undo) is an workaround :+1:

**Comment by Elypson** [comment]
I can confirm that this is still an issue. Downloaded project today on MacOS
