### ISSUE TITLE
BOM of CSV

### ISSUE THREAD

**Issue by wdongw** [bardsoftware/ganttproject#1554]
Hello, 

Could you add BOM message of CSV file when exporting?
Because MS Excel open csv in local language encoding instead of UTF-8 by default, it is really inconvenient. 

Thanks,

**Comment by dbarashev** [comment]
Thanks. The next major update will export directly to Excel files, but perhaps this can be published earlier.

Some background links: https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8
https://donatstudios.com/CSV-An-Encoding-Nightmare

**Comment by wdongw** [comment]
Yes I agree that the problem is on Excel side. But anyway it's a most popular tool so far. 
It's very nice to hear the export to excel feature is on the way outing. 

Thanks,

**Comment by dbarashev** [comment]
Please don't close the ticket. I did't say that it should not be addresses.

**Comment by dbarashev** [comment]
I added an option which, when switched on, will add BOM bytes to the exported CSV. To switch the option on one has to open the options file in any text editor and insert a line
```
<option id="write-bom" value="true"/>
``` 
somewhere between tags
```
 <view id="csv-export">
</view>
```

e.g. like this:

```
<view id="csv-export">

        <option id="write-bom" value="true"/>
    </view>
```
