### ISSUE TITLE
Right click on column header triggers column sorting

### ISSUE THREAD

**Issue by wdongw** [bardsoftware/ganttproject#1555]
Hello, 

When I right click on column names, I was really intent to show/hide some columns. 
But if I right clicked on one of some columns, the sort order of tasks is changed. 
So it will make the task list in a mess if just imported. 

Will this be able to fixed?

Thanks,

**Comment by dbarashev** [comment]
I don't get what is the issue, sorry. Can you elaborate on this?

**Comment by wdongw** [comment]
That means even if I right-click on column name(header of the task list), for example start date, the sorting will be triggered as well.

**Comment by dbarashev** [comment]
It works fine in my test. What operating system do you use?

**Comment by wdongw** [comment]
I'm using Mac OSX 10.13.4. 

Please watch the screen recording. 

[unwanted_sorting.mov.zip](https://github.com/bardsoftware/ganttproject/files/2082865/unwanted_sorting.mov.zip)

**Comment by wdongw** [comment]
[unwanted_sorting_1024.mp4.zip](https://github.com/bardsoftware/ganttproject/files/2082893/unwanted_sorting_1024.mp4.zip)

**Comment by dbarashev** [comment]
Yes, it seems to be reproducible under Mac OSX. Thanks for reporting!
