### ISSUE TITLE
Empty duration field in CSV is treated as 1 day duration

### ISSUE THREAD

**Issue by wdongw** [bardsoftware/ganttproject#1556]
Hello, 

When importing, if the start/end is present and the duration column is exist but all in blank, all task duration will be set to 1 day. 
This may confuse people when importing. 

Not a big issue but will be sweety if can be fixed. 

Thanks,

**Comment by dbarashev** [comment]
Is it about CSV?

**Comment by wdongw** [comment]
Yes, means importing from CSV.

**Comment by wdongw** [comment]
OK just confirmed that this issue only happens when language is set to Chinese Simplified. Under English, it's no problem. 
I don't test under other languages. 
So maybe a encoding problem. 

Here I re-describe the issue:

When import from CSV, if the header is "Name, Start, End, Duration", so the duration of tasks will be incorrect in Ganttproject. All tasks task's duration will be set to 1 regardless the data in column of "End". 
Here I ignore all other columns because this issue is no business with them. 
And just confirmed, this issue exists under Simplified Chinese Language. If the language set to English, it works well without any issue.

**Comment by dbarashev** [comment]
Can you share a sample file?

**Comment by wdongw** [comment]
OK I was wrong. even in English, the problem is still existing. 

But I cannot upload attachments probably because of my Geo location. 
If you can write to me by email at w_dong_w@163.com, I will reply you with attachments and screen recordings.
