### ISSUE TITLE
Locking projects on Web Server

### ISSUE THREAD

**Issue by Adamprro** [bardsoftware/ganttproject#1560]
Hi, 

Reading and saving projects, saved on the server is working properly.
Locking does not work. This is definitely not a server problem because blocking files can be done by another WebDAV client.
In this case, GanttProject correctly shows padlocks and can remove them but he can not create them himself.
After clicking on the padlock symbol, the function appears to work for a while, then the windows refresh and the padlock does not appear.
There is no error information in the application log.
We use Apache Web Server version 2.4 and the latest version of GanttProject.

I hope my explanation is appropriate.
Best regards 
Adam

**Comment by dbarashev** [comment]
Do you ue exteremely short locking timeout by any chance? How long is "for a while"?

**Comment by Adamprro** [comment]
Hi,
Ganttproject does this for about 2.5s - with no result, BitKinex about 2.8s - with a success.
Regards
Adam

**Comment by dbarashev** [comment]
Do you have access to server logs? What's there when you try to lock with GanttProject?

**Comment by rbarzic** [comment]
I confirm having the same issue using Synology WeBDav server. Using cadaver, I can see that GanttProject does not set a lock when opening the file (or cliking on the lock icon)
GanttProject (GanttProject 2.8.10 Pilsen (build 2364))

**Comment by dbarashev** [comment]
This issue, as written by the submitter, is about 

> After clicking on the padlock symbol, the function appears to work for a while, then the windows refresh and the padlock does not appear. 

Which does not seem to be  the same as 

> I can see that GanttProject does not set a lock when opening the file
