### ISSUE TITLE
Copy & Paste of Tasks

### ISSUE THREAD

**Issue by rgeren** [bardsoftware/ganttproject#1563]
I'm experimenting with GanttProject to see if it will be suitable for my use.

I work on multiple projects at one time, so in order to manage each project, I decided to work within one file.

I've created a standard schedule that is typical of all my projects with a main (parent) task for each project and subtasks (child tasks) under each main task to address specific project deliverables. 

When I copy the the project main task and paste it into the same file, it pastes the project task and all subtasks, which is exactly what I want it to do; however, the pasting operation appends "Copy_" to every single subtask name, which requires me to go into each subtask and delete the "Copy_" text. 

Why must all subtasks include the "Copy_" text? Can't it be limited to only the parent task name?

Thanks!

**Comment by dbarashev** [comment]
You can change the copies name pattern, please see https://help.ganttproject.biz/t/copy-paste-tasks-in-the-same-project/427/3 
Pattern applies to all tasks, sorry.

**Comment by rgeren** [comment]
That is what I needed. Thanks! 

Any chance of providing GanttProject for iOS in the future? Having the schedules available in a meeting when I'm using my iPad would be very beneficial. If you did that, I would definitely use this application and provide financial support.

**Comment by dbarashev** [comment]
Glad that it helped.
We do not give any promises, sorry. We are not aware of anyone working on GanttProject for iOS, but we can't be sure that such brave guy will never appear.
