### ISSUE TITLE
The GanttProject application icon looks blurry in Windows 10

### ISSUE THREAD

**Issue by jnsebgosselin** [bardsoftware/ganttproject#1564]
System: Windows 10
GanttProject: GanttProject 2.8.8 Pilsen (build 2308)

The icon used for the desktop shortcut on Windows is a one layer ico file of 32px. This makes the icon looks blurry in Windows 10 and it doesn't look very professional (see figure below).

According to [Microsoft UX icon guideline](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485.aspx):
> Application icons and Control Panel items: The full set includes 16x16, 32x32, 48x48, and 256x256 (code scales between 32 and 256). The .ico file format is required. For Classic Mode, the full set is 16x16, 24x24, 32x32, 48x48 and 64x64.

So following the above recommendation, I solved the problem on my system using Gimp and Inkscape with the following step:
1. From the svg, I exported the ganttproject icon to png with sizes of 256px, 64px, 48px, 32px, 24px, and 16px with Inkscape
2. I opened the 256px png file in Gimp
3. I opened the remaining png files in Gimp with `Open as Layers...`
4. I exported the results as an ico file

It is also said in the guideline that :

> Icon files require 8-bit and 4-bit palette versions as well, to support the default setting in a remote desktop.

> Only a 32-bit copy of the 256x256 pixel image should be included, and only the 256x256 pixel image should be compressed to keep the file size down. 

So one may want to add more layers to cover the 8 and 4-bit palette version in order to be more bulletproof.

![image](https://user-images.githubusercontent.com/10170372/41388218-ed76aada-6f58-11e8-939c-0e1d7125a6cd.png)

**Comment by dbarashev** [comment]
Can you share the result file?

**Comment by jnsebgosselin** [comment]
Sure. All the layers are in 32-bit though, so this doesn't cover the requirements for the 8-bit and 4-bit cases because I only did it to solve the problem on my own system. But I'll take a look on how to add these and share the results back later.

[ganttproject _icon.zip](https://github.com/bardsoftware/ganttproject/files/2102662/ganttproject._icon.zip)
