### ISSUE TITLE
Task name will not be displayed - "Cel..." instead "Cell ID (UI)"

### ISSUE THREAD

**Issue by netperformance** [bardsoftware/ganttproject#1567]
I would like the whole name "Cell ID (UI)" instead "Cel...". I'm using the latest version 2.8.8.

![ganttprojectbug](https://user-images.githubusercontent.com/26298447/41532698-51487172-72f8-11e8-90b0-e16d6b6e8896.PNG)

**Comment by dbarashev** [comment]
Duplicates #1551
