### ISSUE TITLE
Bug: macOS: Cmd-H hides, then unhides and brings up resource window

### ISSUE THREAD

**Issue by cepheid666** [bardsoftware/ganttproject#1578]
On Mac (OS X El Capitan in my case), the cmd-H shortcut to hide the application appears to conflict with something else internally.  In particular, it causes the app to momentarily hide, then it immediately unhides and brings up the Resources window.

I couldn't find cmd-H as a shortcut for a New Resource in the menu, so not entirely sure why this is conflicting (unless cmd-H is the shortcut, but simply undocumented).

Cmd-H is an OS-standard shortcut for hiding the app, so it would be preferable if it did not conflict with other shortcuts.  Some apps (like Adobe CS) do remap cmd-H for other things, but they also provide the option of changing it back to the OS-standard way.

Thanks!

**Comment by dbarashev** [comment]
Yes, it is mapped to New Resource. Thanks for reporting, we'll change this shortcut in Mac OSX bundle.
