### ISSUE TITLE
Export PDF of gantt chart as vector not raster

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#158]
```
Such large things are difficult to distribute without using the native program. 
Perhaps the Gantt to PDF export could save the Gantt image as a vector and not 
a raster. This would allow users of the PDF export to zoom in on the details 
and still be able to read everything.
```

Original issue reported on code.google.com by `matthewj...@gmail.com` on 27 Oct 2010 at 1:04

**Comment by gmandil** [comment]
I have the same issue, a vector image would be easier to share and iText PDF export is including a raster (not vectorial) image inside which is not possible to edit with inkscape for instance.

**Comment by dbarashev** [comment]
There is only one PDF export in GanttProject 2.8.10, it is based on iText and it does produce a vector image, except for the logo and probably bullet icons in the tree.
