### ISSUE TITLE
Ctrl+Z clears everything! So dangerous!

### ISSUE THREAD

**Issue by marklinmao** [bardsoftware/ganttproject#1589]
Simply pressing Ctrl+Z will clears everything in the chart. Then if you press Ctrl+S, you loss all data... which is so dangerous!

Version: 2.8.8  build 2308

**Comment by dbarashev** [comment]
simply pressing Ctrl+Z will undo the last undoable action. Yes, unfortunately "open project" action _in some particular cases_ is undoable. This issue is addressed in #1066
