### ISSUE TITLE
Task bars are not pushed to the left when disconnected

### ISSUE THREAD

**Issue by PrimozFrelih** [bardsoftware/ganttproject#1591]
Example: task B starts on October 2nd because it has a predecessor (task A) that finishes on October 1st (e.g. Wednesday, imagine all working days here). If I disconnect task B from task A it would not jump to the left, but it remains to start on October 2nd - while it could not start a lot earlier.

**Comment by dbarashev** [comment]
Duplicates #1247 
TL;DR: it works pretty much as intended, provided that we keep the model simple. You may use "earliest begin" date to set the date where task should always approach to. 
See also [this blog post about Earliest Begin constraint](http://ganttproject.blogspot.com/2016/07/announcing-ganttproject-28-pilsen.html).
