### ISSUE TITLE
2 menu entries for the same About info

### ISSUE THREAD

**Issue by l0f4r0** [bardsoftware/ganttproject#1592]
Hi,

Is it normal to have 2 identical menu entries regarding the About details?
For example, my French GanttProject 2.8.9 on my Apple 10.13.6, offers:
- GanttProject --> About GanttProject
- Aide --> A propos...
both leading to the same info.

Thanks & best regards.

**Comment by dbarashev** [comment]
Menu "Help" is the same on all platforms, while application menu "GanttProject" is added automatically by macOS and we can hardly control its contents. It contains "About" items, and the best we can do is to show the same dialog as in our cross-platform Help > About.

There are also two menu items for preferences. And for Quit.
