### ISSUE TITLE
HTML Export - Resource section showing incorrect dates

### ISSUE THREAD

**Issue by WedHumpDay** [bardsoftware/ganttproject#1593]
Version 2.8.9

When exporting to HTML, there are three files, Chart, Tasks, Resources. The Resource chart display a week behind the current date and only displays a single week. From what I can gather the PNG export is fixed but incorrect on the dates..

Be great to display the current week and up to 4 weeks out.

![image](https://user-images.githubusercontent.com/36989651/44725914-86ef7a80-aaa4-11e8-961a-438e4a5fdbbe.png)

**Comment by dbarashev** [comment]
Both Gantt chart and resource chart in all kinds of export by default will start with the date which is the current viewport start date in the Gantt chart in the application, and will use the same zooming level. If you need the resource chart in the export to start with the current date, scroll your (Gantt)  chart in the application to the current date.

**Comment by WedHumpDay** [comment]
Perfect. That did the trick.. Thank you.
