### ISSUE TITLE
Add the ability to lock milestones/tasks dates

### ISSUE THREAD

**Issue by LoneAtom** [bardsoftware/ganttproject#1594]
Hi,

It would be nice to be able to lock the dates of milestones or tasks, such that adding dependencies don't move them.
Very useful when doing planning backward, with known milestone/release/ship dates.

Thanks!

**Comment by dbarashev** [comment]
The purpose of [Finish-Start] dependency is to indicate that successor must start after predecessor ends. If it can be violated then why do you need it at all?
Backward planning is a separate story which is tracked in ticket #468. You may find a dirty hack in the comments to that ticket which emulates backward scheduling.
