### ISSUE TITLE
ganttproject won't start on kubuntu 18.04

### ISSUE THREAD

**Issue by blake5634** [bardsoftware/ganttproject#1599]
$ ganttproject 
Error: Could not find or load main class org.bardsoftware.eclipsito.Boot

This module exists in your github but apparently does not install.

**Comment by dbarashev** [comment]
How did you install GanttProject?

**Comment by blake5634** [comment]
Thanks ---    
   Two ways,  one apt install and two taking the latest build from github and running its install script. 
Blake

**Comment by dbarashev** [comment]
If you mean `install-linux.sh` then it is pretty outdated and should not be used, sorry. If you're curious about building from sources, please [refer to the docs](https://docs.ganttproject.biz/development/build-pilsen/index.html)

Chances are that the second command spoiled your apt package. Please remove `/usr/local/bin/ganttproject` and `/usr/local/share/ganttproject` and re-install debian package.

**Comment by blake5634** [comment]
Thanks for quick response!!   Those dirs were already empty.   First I ran apt purge ganttproject.  Then I ran sudo dpkg -i ganttproject_2.8.8-r2308-1_all.deb.      This completed successfully.    trying it:
\>  ganttproject 
Error: Could not find or load main class org.bardsoftware.eclipsito.Boot

**Comment by dbarashev** [comment]
What `which ganttproject` says?

**Comment by blake5634** [comment]
\> which ganttproject 
/home/blake/bin/ganttproject

**Comment by blake5634** [comment]
A friend got ganttproject_2.8.9-r2335-1_all.deb working on 18.04, but when I installed it this too failed with same message.

**Comment by dbarashev** [comment]
So remove it: `rm /home/blake/bin/ganttproject`

**Comment by blake5634** [comment]
OK - works now -- many thanks!!
BH
