### ISSUE TITLE
link task finish-finish

### ISSUE THREAD

**Issue by xilmen** [bardsoftware/ganttproject#1619]
Hello,

I have two tasks linked by the end, If task A or B is late. this influences the start date.
Is it possible to set a fixe date that will not change if another task is delayed ?

Same "probem" on linux or windows.
(build GanttProject 2.8.9 (build 2335))
Thank you

![ganttissue](https://user-images.githubusercontent.com/14809093/49876900-919c0880-fe24-11e8-8f12-fe768d2b4a67.gif)

**Comment by dbarashev** [comment]
Dependencies never change task durations, sorry.

**Comment by xilmen** [comment]
This is a feature for an upcoming release? or am I the only one to have this type of request?

**Comment by dbarashev** [comment]
No, we have no such requests at all, let's alone upcoming releases.

**Comment by xilmen** [comment]
thank you for your quick return :)
