### ISSUE TITLE
add days off for a group of ressources

### ISSUE THREAD

**Issue by PhilLAL** [bardsoftware/ganttproject#1621]
Hi,
I wonder if it would be possible to add days off period for a group a ressources.
For example, if all my company is closed during Christmas vacations decembrer 24th to january 1st, then I would like to add days off for all employees at the same time instead of adding days off for the same period for each employee.
Do you think this would be easily possible?

**Comment by dbarashev** [comment]
Group editing of any object properties, including days offs, is not supported, sorry. In this particular case you may try adding holidays to the project calendar though, unless you plan to have tasks in the vacations period.

**Comment by PhilLAL** [comment]
Oh, I did not notice holidays can be added to project calendar, I'll try, thank you for the tip. :)

**Comment by dbarashev** [comment]
I didn't say that (resource) vacations affect the schedule in any way. Even the opposite, we know that days off are no more than just colored boxes on the chart (see #18). Holidays in project calendar do have impact on the schedule: tasks can't be scheduled on holidays. That's exactly what I said: 

> try adding holidays to the project calendar though, unless you plan to have tasks in the vacations period.

**Comment by PhilLAL** [comment]
Ok, so I misunderstood, but I understand now that a task planned before the beginning of holidays will continue during the holidays, but a task planned with a beginning during holidays will be moved to the first day after the end of holidays.
Did I understand well?
