### ISSUE TITLE
display of ressources in conflict 

### ISSUE THREAD

**Issue by PhilLAL** [bardsoftware/ganttproject#1622]
Hi,
if two or more ressources are in conflict, it would be much more usable if display of ressources view displays in the same color every task in conflict for the same ressource in the same period.
Would it be possible to add this functionnality?

**Comment by dbarashev** [comment]
How do you define a conflict between resources?

**Comment by PhilLAL** [comment]
I mean ressources needed at the same time and which sum makes more than 100%.
For example, A is at 100% on task 1 during this week and is at 20% on task 2 during this same week. Sum of activity for A is 120% so A is in overactivity and appears in red in ressource view for this week.
It would be interesting if task 1 and task 2 are colored in the same color during this week to identify the overactivity.
If task 3 and 4 are in the same situation for another ressource, the color should be different.
Hope this is more clear. :)

**Comment by dbarashev** [comment]
Tasks in resource view appear grouped under resources and are colored with blue/red/green color depending on the share of resource time
![image](https://user-images.githubusercontent.com/2028330/50014241-75d76480-ffd4-11e8-8c69-382f5094ebc1.png)

**Comment by PhilLAL** [comment]
So what I suggest is that since task_2 and task_1 are in conflict for the same ressource, it would be useful to display them both in {some color} for week from 14th to 17th.

In case there is a lot of tasks during different period, it would be easier to identify them (in addition to period of each task) since each task does not stand in the same period. 
In this case, only the duration in conflict should be colored in {some color}.

**Comment by dbarashev** [comment]
>  it would be useful to display them both in {some color} for week from 14th to 17th.

But why? This will make the difference between them (resource allocation) indicated only by pretty small digits. Now you clearly see that `qwe` i is underallocated in `task_1` (because it is green). If they were of the same color you would have to strain your eyes to find out which one is underallocated.

**Comment by PhilLAL** [comment]
Oh, perhaps I don't use the ressources chart the good way.
I look at this view once the tasks attributed to each ressource  to check when some ressources are overcharged and solve this. In my use, all ressource are not always interchangeable so when I notice that a ressource is  overcharged, I can either:
- begin the task later
- attribute it to a lower occupation (for example task_2 can be attributed to qwe for a 70% full time equivalent) 
- attribute the task to someone else.

So I need to identify every task which participate to the overcharge of a ressource to choose which one could or should be modified. I suggest displaying the tasks in conflict for some period in the same color, but perhaps some other way could be used, or perhaps even some oether way already exists. 
My misunderstanding was just due to the fact I did not understood that blue/grey tasks are affected 100% to some ressource. 
With your answer in #1624, it is more clear now and I think I can now identify what task should be modified to avoid overload ressources.
