### ISSUE TITLE
how to manage frequent tasks

### ISSUE THREAD

**Issue by PhilLAL** [bardsoftware/ganttproject#1623]
Hi,
I have frequent tasks, for example weekly meeting, and it would be interesting to add a task with a defined frequency, for instance every monday, 10% meaning 1 hour meeting.
However, I am not sure this is compatible with the philosophy with the gantt since this is not really a task.
Someone has any idea or suggestion?
Regards.

**Comment by dbarashev** [comment]
Duplicates #277
