### ISSUE TITLE
distinguish tasks in chart window

### ISSUE THREAD

**Issue by PhilLAL** [bardsoftware/ganttproject#1628]
Hi,
I have some issues to distinguish different tasks on a big screen.
For instance, in the attached snapshot, I can't identify to which task is assigned the element circled in red downside right ![snapshot](https://owncloud.lal.in2p3.fr/index.php/s/0somQ69tsygk3De/download)
Is there a way to clarify this?

If not, a simple solution would be to use the bicolor white/brown background used in (left) task panel for the main chart window. This would allow to easily identify to which task is linked each element.

Regards and happy new year.

**Comment by dbarashev** [comment]
Duplicates #571
