### ISSUE TITLE
GanttProject not opening (OSX)

### ISSUE THREAD

**Issue by CarToony** [bardsoftware/ganttproject#1633]
Hi,
I am running the latest version of GanttProject, the latest version of Java, and OSX 10.11.8 (El Capitan).  

When I go to open GanttProject, everything appears to be loading up and at the top of the screen (i.e. the OSX grey menu bar or whatever it's called) all the menu options appear for a split second... but then they disappear and all I see is the GanttProject dropdown menu.  This gives me very few options and I cannot do anything.

I also noticed there are problems with the GanttProject biz site, hence me posting the problem on this forum.

Is there anything I can do?

Thanks
CT

**Comment by dbarashev** [comment]
>  all I see is the GanttProject dropdown menu
Sorry? Do you mean that you get only the application menu in the top-left corner of the screen?

Is there anything in the log file after launching? The log file is called `ganttproject.log` and it sits in your user home folder.

**Comment by CarToony** [comment]
Yes that's correct.  I'll get the log file now.

**Comment by CarToony** [comment]
GanttProject 2.8.9 Pilsen (build 2335)
Settings file:
	location: /Users/Miranda/.ganttproject
	size:4889
	is readable: true
java.class.path: /Applications/GanttProject.app/Contents/Java/Classes:/Applications/GanttProject.app/Contents/Java/eclipsito.jar
java.home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
java.ext.dirs: /Users/Miranda/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.io.tmpdir: /var/folders/xn/z95h86m152v5k8v8jcb701jr0000gn/T/
java.runtime.version: 1.8.0_201-b09
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.201-b09
os.arch: x86_64
os.name: Mac OS X
os.version: 10.11.6
sun.java.command: org.bardsoftware.eclipsito.Boot -app net.sourceforge.ganttproject.GanttProject -plugins-dir /Applications/GanttProject.app/Contents/Java/plugins-2.8.9 -log true
user.country: US
user.dir: /Users/Miranda
user.home: /Users/Miranda
user.language: en
user.timezone: Australia/Adelaide

Jan 17, 2019 10:38:41 AM net.sourceforge.ganttproject.GPLogger log
INFO: Options file:/Users/Miranda/.ganttproject
Jan 17, 2019 10:38:42 AM net.sourceforge.ganttproject.GPLogger log
INFO: Waiting until main window closes
Jan 17, 2019 10:38:42 AM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Jan 17, 2019 10:38:45 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds stored in the  options: java.awt.Rectangle[x=38,y=1004,width=80,height=23]
8. finalizing...
Main frame created
Jan 17, 2019 10:38:45 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after setVisible: java.awt.Rectangle[x=50,y=1004,width=80,height=23]
Splash closed
Resizing window...
Jan 17, 2019 10:38:45 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after opening: java.awt.Rectangle[x=50,y=1004,width=80,height=23]
Jan 17, 2019 10:38:45 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds stored in the  options: java.awt.Rectangle[x=38,y=1004,width=80,height=23]
Jan 17, 2019 10:38:51 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories...
Jan 17, 2019 10:38:51 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Jan 17, 2019 10:38:51 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:/windows/fonts
Jan 17, 2019 10:38:51 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory C:/windows/fonts is not readable
Jan 17, 2019 10:38:51 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/usr/share/fonts/truetype
Jan 17, 2019 10:38:51 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /usr/share/fonts/truetype is not readable
Jan 17, 2019 10:38:51 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/System/Library/Fonts
Jan 17, 2019 10:38:55 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/Applications/GanttProject.app/Contents/Java/plugins-2.8.9/org.ganttproject.impex.htmlpdf/resource/fonts
Jan 17, 2019 10:38:55 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories completed

**Comment by dbarashev** [comment]
Does it by any chance sit somewhere in the bottom-left corner, minimized so that only window title and window buttons are visible?

**Comment by CarToony** [comment]
Ah.. there it is!! Thanks
It was very well hidden, obscured by a folder on the desktop
Thanks so much for your help.

**Comment by CarToony** [comment]
Actually I do have another couple of questions, if this is the correct forum to post them.
Within GanttChart, I'm setting up my resources but it doesn't give many options for resource roles (i.e. default role dropdown) and I don't see where I can add any other role descriptions.  
Also on previous versions of GanttChart, also within the Resource setup, I could select the resource allocation in terms of availability (e.g. 0.5 FTE).  This doesn't appear to be here any more.  Is this still selectable somewhere?

**Comment by dbarashev** [comment]
Glad that it helped. Such issues happen sometimes on Mac OS and are not always reproducible, that's why we can't reliably fix them, although we added a number of measures to prevent them. From the log I can say that such small window size was set in the options. Hope it will work fine form now on, after maximizing window back.

**Comment by CarToony** [comment]
Yes, thanks again for this!
Is this the right place for me to post the above questions regarding Resources?

**Comment by dbarashev** [comment]
>  I don't see where I can add any other role descriptions

Project > Properties > Resource roles.
Or if you're happy with "Software development" roles, you can add them when you create a project on the second page of the project wizard.

Resource allocation unit still sits in the resource tab of task properties dialog. You need to assign resource to a task to change its allocation.

**Comment by CarToony** [comment]
Oh - I see now the new the new role option.  Thanks!

With regard to maximum allocation of hours for each resource (e.g. if Person A is only allocated 0.3FTE to this project), is this still setable?  It used to be that I could see when Person A is approaching maximum allocation (or exceeded etc).  Now I think I only get an option to allocate a cost and days off.

**Comment by CarToony** [comment]
Ahhh - ok thanks (it has been a while since I used this).  Sorry, all is coming back to me now.
Thanks again for your help!

**Comment by gekess** [comment]
Hello,

My issue is slightly different: the Gantt-app works fine in my macOS Sierra environment with all my projects but one. With this one project, the program starts, the main screen opens, the planer report pops up and then the entire program freezes. Apple's program manager defines the program as not reacting.
I can open any other project directly before or afterwards, but not as long as the program is frozen. If I lost the data it would be a hard hit. Is there any help I could get?

Cheers,
G.

**Comment by dbarashev** [comment]
Please create a new issue and share your project file, unless it is confidential. If it is confidential, please send it to us by email. 
Please avoid using old closed issues for commenting. I don't think that OP (who is likely to receive email notifications) finds this information relevant.
