### ISSUE TITLE
Italian language fix

### ISSUE THREAD

**Issue by kkaput** [bardsoftware/ganttproject#1639]
Converted "Stato dell'arte" (State of the art), to "Baseline"
"Punto di verifica" (Checkpoint), to "Milestone"
as there are no effective translations, and it is used as it is
[i18n_it.zip](https://github.com/bardsoftware/ganttproject/files/2827738/i18n_it.zip)

**Comment by dbarashev** [comment]
Hello, we keep our translations in Crowdin service. May I ask you to update these strings at Crowdin? 
This is the translation of "milestone": https://crowdin.com/translate/ganttproject/27683/en-it#6401165

With respect to "baselines", there are many strings with this word. You can find them e.g. by searching "stato": https://crowdin.com/translate/ganttproject/27683/en-it#q=stato

**Comment by dbarashev** [comment]
As far as I can see, changes were applied to Crowdin. Thanks!
