### ISSUE TITLE
incorrect application of VAT to paymentI

### ISSUE THREAD

**Issue by TRAXN** [bardsoftware/ganttproject#1640]
If payments for ganttproject are indeed donations, VAT should not be applied to the payment as donations are non-VATable. VAT is automatically added by PayPal, which would imply you are stealing money from whichever government on whose behalf you are collecting the tax - if you don't hand it over.  And if you do hand it over, you are doing so unnecessarily if the payment is a donation.  If the payment is not a donation, you should not claim that it is on your website - that would be misleading the customers, making them think this is a charitable gift when in fact it is a payment. I strongly suggest you fix this before the VAT-man or Charity Commissioner gets hold of you!

**Comment by dbarashev** [comment]
Hello,
from accounting perspective they are not donations. You buy a software package at the price which you set. I thought we removed all mentions of "donation" from the web site. Can you please point us to the place where it still remains?

For the record, VAT is added by Gumroad which is our reseller and they claim that they do [return VAT themselves](https://help.gumroad.com/11164-payments/dealing-with-vat).

**Comment by TRAXN** [comment]
Apologies I meant to go back and see where the word appeared but got snowed
under. Appreciate you checking.

All the best,

Ken

Ken Dueck
Managing Director

*Tractioneers Ltd : **Business Strategy & Development*
Tel: 07785 977527 - Email: ken.dueck@tractioneers.co.uk


*Tractioneers Ltd. is registered in England & Wales, No. 07735509. *
*Registered Office: 8 Newbridge Close, Shanklin, Isle of Wight, PO37 7AY,
United Kingdom.*
