### ISSUE TITLE
Gantt project application closes when I remove laptop from docking station.

### ISSUE THREAD

**Issue by tecdec** [bardsoftware/ganttproject#1641]
Almost every time I remove my laptop from the docking station. The Ganttproject application closes and I lose unsaved updates. I can possibly use recover, but, it is annoying having to do so.

This does not happen with any other application.
Ganttproject version 2.8.9.  Going to upgrade to 2.8.10 within a week or two.
laptop model details are:-
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	IE-00000953
System Manufacturer	HP
System Model	HP EliteBook 840 G5
System Type	x64-based PC
System SKU	3WP99EC#ABU
Processor	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	HP Q78 Ver. 01.04.00, 12-Sep-18
SMBIOS Version	3.1
Embedded Controller Version	4.83
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	Ireland
Hardware Abstraction Layer	Version = "10.0.16299.371"
User Name	ERICSSON\EEIDLE
Time Zone	GMT Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	17.1 GB
Total Virtual Memory	36.6 GB
Available Virtual Memory	16.3 GB
Page File Space	4.75 GB
Page File	C:\pagefile.sys
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by dbarashev** [comment]
Can you please try workarounds described in this Knowledge Base article? https://github.com/bardsoftware/ganttproject/issues/1346

**Comment by dbarashev** [comment]
Duplicates #1346

**Comment by tecdec** [comment]
Thanks  @dbarashev 
Just to confirm, workaround below has worked for me.

If GanttProject was installed with Windows Installer and you run it using menu items then open file ganttproject.l4j.ini from the GanttProject installation directory (you may need to be Administrator) and remove the line -Dsun.java2d.d3d=false. Save the file.
