### ISSUE TITLE
en français please

### ISSUE THREAD

**Issue by jpv-1** [bardsoftware/ganttproject#1647]
Bonjour,
ça fait un bout de temps que je n'étais pas revenu ici. J'avais travaillé il y a quelques années avec mes élèves (college). Je croyais que c'était simple et je me retrouve avec un site en anglais sans trace d'une page en français. Donc, peut être serait il souhaitable de mettre un bouton pour permettre d'afficher une page d'accueil en français pour ne pas les effaroucher.
Merci pour ce travail.
Cordialement.
JP VERON
PS : obligé de creer un compte github juste pour poster un message : désolé, je n'ai pas trouver le bouton "contact"

**Comment by dbarashev** [comment]
Dear friend,
this is English-speaking project with English-speaking community. You and your students can always use translation function which is available in many modern browsers (e.g. is built directly into Chrome and this is how I managed to translate your post).

**Comment by jpv-1** [comment]
Thanks Dimitri.
At the beginning, i thought it was a french project at Université de Marne la Vallée (near Eurodisney)and theyr was a page of the site which was in french
deshalb habe ich diese Irtum gemacht 

thanks for that job
JP

      De : Dmitry Barashev <notifications@github.com>
 À : bardsoftware/ganttproject <ganttproject@noreply.github.com> 
Cc : jpv-1 <jeanveron-1@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 19 février 2019 19h32
 Objet : Re: [bardsoftware/ganttproject] en français please (#1647)
   
Dear friend,
this is English-speaking project with English-speaking community. You and your students can always use translation function which is available in many modern browsers (e.g. is built directly into Chrome and this is how I managed to translate your post).—
