### ISSUE TITLE
Add option to display generic quarters/months/weeks from start of project in timeline

### ISSUE THREAD

**Issue by cfdguru** [bardsoftware/ganttproject#1654]
When initially planning a project or creating a project proposal, it is often useful/required to submit a Gantt chart with the timeline dates expressed in generic calendar quarters/months/weeks/etc from the start of the project instead of using actual calendar months and dates. Having an option to switch between a generic timeline and a calendar timeline would make GanttProject much more useful. Currently, I have to resort to making simplified manual Gantt charts in something like Excel for planning and proposal purposes and then recreate them in Gantt chart when it is time to execute the projects.

**Comment by dbarashev** [comment]
Duplicates #85

As a workaround, you can start your project from Jan 01, any year (e.g. 2001) and move the start date once you have one. Project > Calendar > Move start date

**Comment by cfdguru** [comment]
Dmitry,

Thanks for your prompt reply. While your suggestion works for informal planning, I am required to publish the Gantt charts to others in the form of a formal proposal, often to be reviewed by external entities for funding. These published Gantt charts must have timeline labels such as [Q1,Q2,Q3,Q4] or numerically labeled periods such as months in the form of [1,2,3,4,…]. Actual month names such as [Jan, Feb, Mar, etc]  are not considered acceptable for these charts. There are arbitrary delays between proposal submission and contract award, thus requiring the generic timeline labels.  I’m often asked what I used to produce my project status update schedules and I gladly tell them I use GanttProject. However, this one issue is a major road block for expanded use of GanttProject for proposal driven businesses such as ours.

Thanks,

Chris Talley
256-508-1013
ctalley69@mac.com
