### ISSUE TITLE
Have time as well as date for tasks [enhancement]

### ISSUE THREAD

**Issue by tanj** [bardsoftware/ganttproject#1655]
We were looking to do a gantt chart for a three day event and show the various tasks in 30 minute intervals. Is it possible to change the date field to be a datetime field?

**Comment by dbarashev** [comment]
Day is the minimum duration, sorry.
https://help.ganttproject.biz/t/read-me-first-faq-and-search/8

**Comment by dbarashev** [comment]
Duplicates #225
