### ISSUE TITLE
"Print to File" fails: sends job to printer

### ISSUE THREAD

**Issue by RichardBonomo** [bardsoftware/ganttproject#1657]
I am using / learning to use GanttProject 2.8.10 Pilsen (build 2363).

I am running this on an an Apple Intel Tower running OS 10.11.6 (El Capitan).

When I go to print a Gantt chart, it bypasses the system printing screen completely.   When I select the "print to file" option (a check box), it brings up a "save file" dialog, and allows me to change the name of the file to something else from "out.ps".  However, when I click on the "save file" button, it just sends the job to a printer.

**Comment by dbarashev** [comment]
The best and recommended way to print is to export project to PDF or PNG and print the result using your favorite system printing tools. Java platform is not the best friend with printing, sorry.

**Comment by RichardBonomo** [comment]
Dear Dimtry,

Thank you for getting back to me.   I was not aware of that work-around.

Richard B.

--------------------------------------
Richard Bonomo
University of Wisconsin
Fusion Technology Institute
bonomo@engr.wisc.edu
richard.bonomo@wisc.edu
ph: (608) 265-3098
