### ISSUE TITLE
Task duration in fractions or multiples of a day

### ISSUE THREAD

**Issue by sickdoc** [bardsoftware/ganttproject#1658]
Hello, thank you for providing this nicely made piece of software. However, to include Gantt Project into my workflow it would be absolutely necessary to measure durations in subunits of a day. For many users it would be a more than sufficient solution to just change the data type of the duration from INT to FLOAT and allow the input field for the duration to accept floating point numbers. Thus, anyone could input an hour as 1/24th of a day and it should appear with a proper visual representation in the calendar view.
I did donate to this project, earlier, and I am willing to donate more if only this feature could be added. Be sure to announce this major improvement in a highly visible manner as soon as an operational version is available. Thank you and with best regards

**Comment by dbarashev** [comment]
Duplicates #225
