### ISSUE TITLE
Visibility is really really bad when using grey on grey

### ISSUE THREAD

**Issue by ilreberli** [bardsoftware/ganttproject#1662]
It's not a bug, but the visibility in the header lines is really bad when using grey letters on grey background. The date in the last header line is completely unreadable. I hope you change this some time in a future version. Preferable with some additional settings (e.g. selectable background header color and selectable letter color).
I am using Gantproject on MacOS Mojave in dark mode.

![2019-04-19_13-25-06](https://user-images.githubusercontent.com/37041620/56424235-49479800-62a7-11e9-8818-a4195421b068.jpg)

**Comment by dbarashev** [comment]
Some information is more important, some is less important. It is a common practice when less important information is less visible. Sorry if it appears excessively bad to you. However, it is arguably the first request about these particular colors in the last few years, so I hope it is not that bad.

The color of the lowest line in the timeline is actually configurable in the configuration files. You need a file `plugins-2.8.10/ganttproject/data/resources/chart.properties` in GanttProject installation folder. On macOS you can find it with action "Show contents" in the context menu on GanttProject application and then navigating to `Contents/Java/plugins-2.8.10/ganttproject/data/resources/`

This line in `chart.properties` controls the color:
`timeline.bottom.minor_label.color = #888888` (only hexadecimal representations of RGB colro are accepted)
