### ISSUE TITLE
Error importing mpp file

### ISSUE THREAD

**Issue by jlgarnier** [bardsoftware/ganttproject#1676]
Hi Team,

Just got an error importing an mpp file but cannot help understanding why. I provide the related files in case this can improve the application.

Thanks for any help!
[Logtrace-BCA.zip](https://github.com/bardsoftware/ganttproject/files/3391350/Logtrace-BCA.zip)

**Comment by dbarashev** [comment]
Provided that I see the same as you, it is a warning, not an error:
```
The following problems were detected during import. 
Please note that some of them may be harmless

Severity | Message
--   | --
INFO | Task with id=7 is blank task. Skipped
INFO | Task with id=9 is blank task. Skipped
INFO | Task with id=11 is blank task. Skipped
INFO | Task with id=13 is blank task. Skipped
INFO | Task with id=15 is blank task. Skipped
INFO | Task with id=17 is blank task. Skipped
INFO | Task with id=19 is blank task. Skipped
INFO | Task with id=21 is blank task. Skipped
INFO | Task with id=23 is blank task. Skipped
INFO | Task with id=24 is blank task. Skipped

```

As the message suggests, these problems are really harmless. Blank tasks are not supported in GanttProject (sorry) so they are skipped during the import.

**Comment by dbarashev** [comment]
Existing ticket about blank tasks: #1010 
If and when blank tasks appear in GanttProject, they will be integrated into import/export.

**Comment by jlgarnier** [comment]
Many thanks Dmitry for your quick answer! I'll then ignore these warnings...
