### ISSUE TITLE
Weird behavior of drag'n'drop in the task table

### ISSUE THREAD

**Issue by levventodd** [bardsoftware/ganttproject#1679]
You can't drag tasks to a parent task without the program renaming other tasks or failing to create the sub-task altogether.

System: Lenovo laptop running Windows 10. Program is running on the 2nd monitor, if that makes a difference.

To reproduce: 

1. Create some tasks:

Planning
Requirements Document
Architecture Design

Goal: Make "Requirements Document" a sub-task of "Planning":

Planning
    Requirements Document
Architecture Design

Method 1: 

Click on "Requirements Document" to select it.  Click and hold and drag on top of "Planning". While dragging, the task changes to a text box you can write in. 

Release the dragged task over the task you want to be the parent task. Result: The task that was underneath the moved task was renamed to be the same as the dragged task. That is, you now have:

Planning
    Requirements Document
Requirements Document

Method 2:
Click drag an unselected task onto a task that shall be the parent, then release.

Result:
Item doesn't move at all.

**Comment by dbarashev** [comment]
Thanks for reporting. Weird behavior indeed.

Hint: hitting Tab is the best way to indent a selected task under a task above it.

**Comment by levventodd** [comment]
Thanks!

Hmm -- tab doesn't indent the last task in the list. Seems to work for the others, though - cheers.

**Comment by dbarashev** [comment]
Tab works fine in my tests. There are many reasons why task can't become a subtask, e.g. because there is finish-start dependency.
