### ISSUE TITLE
Importing wrong ressources from MS Project files [Ganttproject 2.8.10]

### ISSUE THREAD

**Issue by Thomas-44** [bardsoftware/ganttproject#1681]
Hello,
Importing projects from MS Project files lead to several issues on dates and especially ressources : 
- Ressources assigned to tasks in GanttProject are different from those assigned to the sames tasks in MS Project.
- Concerning dates, it might be the "automatic scheduler" or "manual scheduler" option that make this difference ?
Thanks for your help
Best regards

**Comment by dbarashev** [comment]
Please share the ms project file which reproduces this issue. 
I am on vacation and will not be able to dive into this issue until August 10, sorry.

**Comment by dbarashev** [comment]
No response, closing
