### ISSUE TITLE
None of the Windows and Mac editions of Gantt can import XML.

### ISSUE THREAD

**Issue by Atom-ManhattanProject** [bardsoftware/ganttproject#1683]
Hi!
It appears manifestly that none of the importations from XML to Gan are functional.

I went to find the required informations from your GitHub guidelines, and have pretty many files; #1/3) I only cannot find your ganttproject.command on MacOS.

#2/3) 
On Mac (not on Windows, this time), your importation settings hide the Browsing, until we click on these settings, then the browsing is possible.

#3/3) 
On Mac, neither of the Import and Open features respectively to Xml are functional, (they do not operate), on Mac as well as on Windows (same computer, 1 big third of the Flash memory available in both case, and 1 sole partition on Windows, to avoid technical problems).

I tried to go to ressources, and then back to tasks, in order to hope a refresh, but the absence of Save colour shows that no change was applied, effectively.

-On Windows, this is about to be the same, at the exception that when I create a one-task project (so without arrow dependency) with Gan, I can OPEN it with Microsoft Project (but 2 parameters change: the simplicity of my last project, on Windows, and the fact - surely more influent - that I created my Gan Project on this platform (still same computer)).

N. B.: Whole SDK 8 in 64 bits in both of the case: 
On Mac, I omitted that JRE was not only the internet browser plugin, so I installed the whole JDK (which contains all Oracle Java components) after the GanttProject installation, but that should not be negatively relevant, since GanttProject.app seems to be (a portable application) from its decompression.
-On Windows, where the installation of GanttProject is more complex, I took before the precaution to install JDK first.

-Normally, the main of the informations are reproductible from the windows and screen shots, which I have numbered in the logical order, et whose (as the general absence of GanttProject bugs) the fidelity in the files titles, is respected for the whole.
[GanttProject_ImportXmlDenied.zip](https://github.com/bardsoftware/ganttproject/files/3587589/GanttProject_ImportXmlDenied.zip)

**Comment by dbarashev** [comment]
Sorry, I really can't grasp what issues do you have.

As far as I understand from the title and partially from the text, you're having issues with importing MS Project files.
You can import MS Project files using Project > Import menu. If you're having import issues with some particular project, please share the project file.

**Comment by juananpe** [comment]
I can confirm that the .xml projects provided in the zip file can be imported without problems under macOS in GP 2.8.10 (using the option Project > Import > from MS Project)

![image](https://user-images.githubusercontent.com/1078305/64856952-8aa85d80-d623-11e9-8ab0-f3fe577dc62f.png)
