### ISSUE TITLE
GanttProject 2.8.10 Pilsen is clipped and unmovable

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [bardsoftware/ganttproject#1685]
I just purchased Gantt for $20 (wanted to help support your cause). I downloaded and received version 2.8.10. The previous version I had was 2.7.1 (and it worked fine). This version 2.8.10 comes up clipped on the left of the screen. I am unable to grab the window and move it to the right. 

So it is currently unusable. I am using the Windows version. My laptop is Windows 10
Here is a picture of how it appears on my screen.
![image](https://user-images.githubusercontent.com/17237544/65820969-bf541180-e1ec-11e9-9f5e-73096dbbe3fc.png)

**Comment by dbarashev** [comment]
You can move window when title bar goes off screen:
https://www.thewindowsclub.com/how-to-move-a-window-when-its-title-bar-goes-off-screen

Alternatively, you can remove `.ganttproject` file from your home folder. This will reset saved window position, _as well as all other settings_.

**Comment by KarenGhavam-lunarG** [comment]
Removing the .ganttproject file did not change anything. The window was still offscreen. Not sure how GanttProject got setup this way in that this was a brand new laptop and brand new installation of the software. However following the instructions on how to move a window when the title bar is offscreen allowed me to maximize the app and get ahold of things. Then subsequent starts of the program was not placing the window offscreen.

Closing. Thank you for your help.
