### ISSUE TITLE
New purchase does not run on Mac

### ISSUE THREAD

**Issue by melbappdev** [bardsoftware/ganttproject#1686]
Hi guys
I have just purchased GanttProject but it crashes as soon as I try and run it. Details:

Me: rod@melbappdev.com
MacOS 10.14.6
Java: Version 8 Update 221 

Once I run the app it appears in Activity Monitor for about a second then disappears (which suggests a crash). 
I can't find any logs in /var/logs, ~Library/Logs or ~Library/ApplicationSupport. In fact, I can't find any files or folders with the name "GanttProject" on my hard drive.
Where are the logs kept?

Thanks
Rod

**Comment by dbarashev** [comment]
Hello, the log file sits in your home directory and is called `ganttproject.log`
You may want to read [this knowledge base article](https://github.com/bardsoftware/ganttproject/issues/1637)

**Comment by melbappdev** [comment]
Hi dbarashev
thank you for your prompt response.

I tried the various things and what works is running the "fallback distro for Mojave". Interesting thing was that there was no granttproject.log in my home directory - maybe logging doesn't start until Java is running and ganttproject couldn't execute under Java for some reason.

Anyway ... I'm up and running. Thanks.
Rod
