### ISSUE TITLE
Error when setting all week days as weekend (non-working) days

### ISSUE THREAD

**Issue by alex-bia** [bardsoftware/ganttproject#1700]
In menu: "Project" / "Properties" / "Calendar" / "Choose weekend", a student of mine has set all week days as weekend days (I know it makes no sense). He then saved the project as a .gan file which can no longer be opened. The internal XML contains: <default-week id="1" name="default" sun="1" mon="1" tue="1" wed="1" thu="1" fri="1" sat="1"/>

I modified the XML file setting only sat and sun as weekend days and the problem got fixed (the file can be opened again): <default-week id="1" name="default" sun="1" mon="0" tue="0" wed="0" thu="0" fri="0" sat="1"/>

However, the program should not hang and should handle the situation differently. Remember Murphy's Law.  :-)

**Comment by dbarashev** [comment]
Duplicates #1609

**Comment by alex-bia** [comment]
Ok. Perfect. Did not know it was a duplicate.
BTW: Great software! I've been using it for years to teach Project Management.
