### ISSUE TITLE
Java 11: Launching application failed

### ISSUE THREAD

**Issue by clifflinmao** [bardsoftware/ganttproject#1703]
GanttProject cannot be launched successfully with Java 11 on MacOS.

**Comment by dbarashev** [comment]
Any details? GanttProject runs fine under Java 11.

**Comment by clifflinmao** [comment]
Hi

‘GanttProject.app’ inside ganttproject-2.8.10-r2363.dmg quit automatically one second after launching, no log, no information. ganttproject-2.8.10-r2364.zip can be launched successfully through command-line.

Best regards,
Mao LIN

**Comment by dbarashev** [comment]
So it does run fine under Java 11 when launched from the command line?

**Comment by clifflinmao** [comment]
Yes, when I launch it through command line (jdk 11), it's OK. But if I
install the *.dmg file and launch it(either double click or 'open *.app',
it failed.

- Lin

Dmitry Barashev <notifications@github.com> 于2020年1月8日周三 上午12:24写道：

**Comment by dbarashev** [comment]
Thanks. The issue with launching macOS app and possible workarounds are described in issue #1637
