### ISSUE TITLE
GanttProject not detecting Java 11

### ISSUE THREAD

**Issue by icybears** [bardsoftware/ganttproject#1711]
I'm on Windows 10 with jdk 11 installed. GanttProject saying I need java 7 or higher.

![GanttProject Error Image](https://i.imgur.com/N0KsLR5.png)

**Comment by dbarashev** [comment]
You need to set up either registry keys or JAVA_HOME environment variable (the latter is easier). See more details here: https://help.ganttproject.biz/t/using-open-java-instead-of-oracle-version/1513

**Comment by icybears** [comment]
Did you see the screenshot in my first post ? I already echo'd JAVA_HOME.

**Comment by dbarashev** [comment]
Oh, sorry didn't mention an important notice about `JAVA_HOME`. The launcher `ganttproject.exe` was generated by [Launch4J](http://launch4j.sourceforge.net/). Unfortunately it [doesn't support JAVA_HOME](https://sourceforge.net/p/launch4j/bugs/197/#0c5b). However, `ganttproject.bat` (which is totally our own)  is aware of `JAVA_HOME`, so you can use it.

**Comment by icybears** [comment]
Thanks, **using the .bat file works.** 
However, there was a little warning that popped up though it's unrelated.

![Screenshot](https://i.imgur.com/TYjJggH.png)
