### ISSUE TITLE
Table columns visibiility setting is broken

### ISSUE THREAD

**Issue by DecorteT** [bardsoftware/ganttproject#1734]
I just tried GanttProject 2.8.11 Pilsen (build 2393).
Before I had GanttProject-2.8.9-r2335.
I use to hide begin and end date on the Gantt tab and also the default role on the Recources tab.
I can still do that, but every time I reopen the file the columns are there again.
Is there still a way to hide them all the time?
Thanks

**Comment by DecorteT** [comment]
The columns also seem to come back when hitting the undo button.

**Comment by dbarashev** [comment]
Thanks for reporting!

**Comment by dbarashev** [comment]
Fixed. Build 2396 is available from our website and from GitHub releases
