### ISSUE TITLE
GTK+ dark theme not respected throughout

### ISSUE THREAD

**Issue by japhir** [bardsoftware/ganttproject#1738]
Hi! I love the ganttproject! I've been using it to plan my PhD project. Thank you for making it!

I like using a dark GTK theme, but when I set ganttproject to use the GTK+ theme, it works for menus, the toolbar, and the settings view, but not for two main areas:
- the list of tasks is displayed correctly except for the values themselves: they have a background colour that alternates between creme and white, but the font color is set to white because of the dark theme, which makes everything illegible
- the main gantt chart does not appear affected by the gtk theme at all. This is not such a big issue, since here I can at least read everything.

See the attached image to see what I mean. I'm using the new Ubuntu default theme Yaru-dark (on Archlinux with sway as wm. The title bar on the settings comes from that)

![2020-05-10-10:43:43_region](https://user-images.githubusercontent.com/10659193/81494719-48ffad80-92ab-11ea-9f72-a76b96ed09a2.png)

**Comment by dbarashev** [comment]
I don't want to disappoint you, but supporting dark themes in GTK+ appearance on Linux is by far not the top priority thing. Also, we're slowly migrating to JavaFX UI toolkit which uses different approach to application look, and I'm afraid that GTK+ appearance will be sunset (as well as all other native look and feels).

**Comment by japhir** [comment]
No worries, after reading up some more on GTK+ themes and how Adwaita is basically the only fully-functional theme, with no standardisation, I can see how this would probably be a bit of a mess with a lot of work that's probably not worth your wile. Cheers!
