### ISSUE TITLE
Collapse/expand all function

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#174]
```
A collapse-all and expand-all function for the tasklist would be very much 
appreciated.
```

Original issue reported on code.google.com by `Hoffm...@CPPM.In2p3.Fr` on 13 Jan 2011 at 5:50

**Comment by ngm** [comment]
Does this feature exist?
I can't see it in the interface in 2.8.5.

![image](https://user-images.githubusercontent.com/172324/36026834-b4296382-0d90-11e8-8b62-353c87805768.png)
