### ISSUE TITLE
JavaFx dependency  must be at Prerequisites in the development guide

### ISSUE THREAD

**Issue by Anaitz98** [bardsoftware/ganttproject#1749]
As you said in this forum post, https://help.ganttproject.biz/t/unresolved-reference-javafx-embed-when-building-latest-version/1959/4
JavaFX is currently a necessary dependency in the master version, so it should be marked as such in Prerequisites for the build in the developer guide, https://docs.ganttproject.biz/development/build/

**Comment by juananpe** [comment]
Yep, the unmet JDK FX dependency is also yielding an error [in Travis jobs](https://travis-ci.org/github/bardsoftware/ganttproject/jobs/696944786)
![image](https://user-images.githubusercontent.com/1078305/84398515-55578d00-ac00-11ea-8e94-3aeb66fee5df.png)

**Comment by dbarashev** [comment]
I updated the developer guide.
