### ISSUE TITLE
Human resources days-off handling

### ISSUE THREAD

**Issue by przemhb** [bardsoftware/ganttproject#1754]
At present days-off defined for a particular employee result merely in marking the one as being not available (the yellow rectangle at the gantt chart). It does not address a scenario when the work cannot be done by any other employee. 

I suggest adding a feature, which would make tasks assigned for the employee, who has scheduled days-off, paused during his/hers holidays. As the days-off is a hard limit for the human resource I reckon it would be better, and justified, if such a pausing would be default gantt drawing approach. Then someone who is planning would be forced to take the decision on how to assign the resources knowing the employee will be unavailable. 

In my case I was forced to enter global days-off for whole my team despite the fact each person has different days-off planned. I am not happy with it. Tasks being performed by one employee could not been re-asigned to another while being performed.

I hope this helps.

**Comment by dbarashev** [comment]
This basically duplicates #18 
What do you mean when you say "paused"? What exactly is supposed to happen to tasks and to Gantt chart in your scenario when some resource gets vacation days?

**Comment by przemhb** [comment]
Let's assume:
Task 3 is scheduled to start on wk1 and has defined duration of 3 weeks.
The task is assigned to John Smith, who planned his days-off for wk2. Then:
- Task 3 should start on wk1 and end on the end of wk4,
- for the wk2 (let's call it a "pause" week) Task 3 line i Gantt chart should be clearly marked to show no work will be performed  (could be in the same way as it is now),
- the clear marking will provide feedback for the user - he/she will have a choice either to accept the "pause" week and later Task 3 finish or to reassign the task for an other person.

**Comment by dbarashev** [comment]
Okay, thanks. 
So, it duplicates #18 and #83
