### ISSUE TITLE
Feature-Request: Labeling of Processes

### ISSUE THREAD

**Issue by SebStSt** [bardsoftware/ganttproject#1757]
1.
Possibility to cluster more than one label to a process on one side
--> e.g.: On the right hand side of a process i want to show: duration, Name = 3 Tays, Testing

2.
Add Possibility to add a label on the center of a process?

Dont know if this is possible

This ability would for sure be nice to have for every

**Comment by dbarashev** [comment]
Partially duplicates #1576 
With respect to labels inside the task bar, I am not sure if it makes too much sense. With the current chart rendering styles it will create a mess of labels and progress bars. If we add more vertical space for labels, well, our chart just takes more valuable vertical space.
