### ISSUE TITLE
Feature-Request: Duplicate a process / Copy style

### ISSUE THREAD

**Issue by SebStSt** [bardsoftware/ganttproject#1760]
maybe it would be helpful to have the possibility to create a new process by copying a current

Maybe it would be helpful to have the possibility to copy only styles (color) and insert it to a already available process

**Comment by dbarashev** [comment]
Assuming that you mean "task" when you say "process", you can use standard clipboard shortcuts to clone both single tasks and even the whole task groups, even with dependencies.

Ctrl+C Ctrl+V
