### ISSUE TITLE
Online server option

### ISSUE THREAD

**Issue by ValentinGratz** [bardsoftware/ganttproject#1763]
The idea would be to offer an optional server to host your project online.

Finding a web host / server that takes the WebDAV format (where I don't know which one, where the format you request is not easy, and it is not for all budgets.

French translate :

L'idée serait de proposer en option un serveur pour héberger son projet en ligne.

Trouver un hébergeur/serveur qui prend le format WebDAV (où je ne sais plus lequel, où le format que vous demandez n'est pas facile, et ce n'est pas pour tous les budgets.

**Comment by dbarashev** [comment]
Check out https://ganttproject.cloud
