### ISSUE TITLE
GPCsvImportTest not passing tests 

### ISSUE THREAD

**Issue by Anaitz98** [bardsoftware/ganttproject#1766]
When running tests , the biz/ganttproject/impex/csv/GPCsvImportTest.java doesn't pass. Preconditions  are null when building task headers.
![incorrectcsv](https://user-images.githubusercontent.com/37109925/91659473-1256d880-ead0-11ea-909b-9e8a216aa12b.png)

**Comment by dbarashev** [comment]
Hi, GPCsvImportTest runs and passes fine on current `master` both on my Linux and on GitHub (the latest build: https://github.com/bardsoftware/ganttproject/runs/1049126352)
