### ISSUE TITLE
weird font display on software

### ISSUE THREAD

**Issue by drcrescencio** [bardsoftware/ganttproject#1783]
First time user. I got this weird font display. For my surprise, very few windows show correct characters.

![Capturar](https://user-images.githubusercontent.com/23739031/94377024-abd7d100-00f4-11eb-86e1-70b71263ef6e.PNG)
![Capturar2](https://user-images.githubusercontent.com/23739031/94377090-0cffa480-00f5-11eb-8159-f2cb775482ec.PNG)
![Capturar3](https://user-images.githubusercontent.com/23739031/94377093-0e30d180-00f5-11eb-9a54-6704ba9c0d62.PNG)

**Comment by dbarashev** [comment]
Nice :) Can you please check what interface language is chosen in the settings and if it is your language (Portuguese?), or English, then try choosing some other Application Font in the settings? 

A screenshot of the settings window with English interface and correct font:

![image](https://user-images.githubusercontent.com/2028330/94378374-eca20b00-0131-11eb-9dee-6942c132e738.png)

**Comment by drcrescencio** [comment]
Thank you. It works! I provide two new screenshots with 'wrong font' and in different languages.

When I choose apparence from Plastic to Windows, The preference window works:
![apparence_windows](https://user-images.githubusercontent.com/23739031/94462609-2c98da80-0192-11eb-8f38-5340f05ad941.PNG)

It not work with Segoe UI font, and probably others:
![segoe_ui](https://user-images.githubusercontent.com/23739031/94462694-49cda900-0192-11eb-831b-9bfbfabada3b.PNG)

Then, with Appearance Windows and not Segoe UI font, it work in english and portuguese:
![portuguese](https://user-images.githubusercontent.com/23739031/94462853-7ed9fb80-0192-11eb-899f-e5451099d880.PNG)

Thank you
