### ISSUE TITLE
Cannot add a resource to a task in MacOS 10.15.6

### ISSUE THREAD

**Issue by nigelhappy** [bardsoftware/ganttproject#1793]
In the task dialog box, the resource tab is selected. Clicking the Add button has no effect. In Microsoft Windows 10, the same action causes the field to be populated with a drop-down list to choose a resource. GanntProject 2.8.11 Pilsen (build 2396)

**Comment by dbarashev** [comment]
It works in my tests on macOS 10.14.6 and 10.15.7

If this issue is reproducible on you macOS, please record a screencast or video showing the issue and post the contents of the log after reproducing it. (Help > View log)
