### ISSUE TITLE
Building 2.8 fails on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by derUli** [bardsoftware/ganttproject#1796]
I tried to build the 2.8 following this instructions and with the source zip provided at:

https://docs.ganttproject.biz/development/build-pilsen/

I have this JDK and I installed the openjfx package and the sources for it.
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

However the compiler can not find the javafx classes.
Here is the output of the gradle command

`
> Task :..:ganttproject:compileJava FAILED
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/UIUtil.java:34: error: package javafx.embed.swing does not exist
import javafx.embed.swing.JFXPanel;
                         ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:22: error: package javafx.application does not exist
import javafx.application.Platform;
                         ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:23: error: package javafx.beans.value does not exist
import javafx.beans.value.ChangeListener;
                         ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:24: error: package javafx.beans.value does not exist
import javafx.beans.value.ObservableValue;
                         ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:25: error: package javafx.concurrent does not exist
import javafx.concurrent.Worker;
                        ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:26: error: package javafx.embed.swing does not exist
import javafx.embed.swing.JFXPanel;
                         ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:27: error: package javafx.scene does not exist
import javafx.scene.Group;
                   ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:28: error: package javafx.scene does not exist
import javafx.scene.Scene;
                   ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:29: error: package javafx.scene.layout does not exist
import javafx.scene.layout.VBox;
                          ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:30: error: package javafx.scene.web does not exist
import javafx.scene.web.WebEngine;
                       ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:31: error: package javafx.scene.web does not exist
import javafx.scene.web.WebView;
                       ^
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:84: error: cannot find symbol
  private static void setOpenLinksInBrowser(final WebEngine webEngine) {
                                                  ^
  symbol:   class WebEngine
  location: class ProjectOpenDiagnosticUiFx
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/UIUtil.java:638: error: cannot find symbol
          new JFXPanel(); // initializes JavaFX environment
              ^
  symbol: class JFXPanel
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:56: error: cannot find symbol
        final JFXPanel contentPane = new JFXPanel();
              ^
  symbol: class JFXPanel
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:56: error: cannot find symbol
        final JFXPanel contentPane = new JFXPanel();
                                         ^
  symbol: class JFXPanel
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:59: error: cannot find symbol
            VBox root = new VBox();
            ^
  symbol: class VBox
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:59: error: cannot find symbol
            VBox root = new VBox();
                            ^
  symbol: class VBox
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:60: error: cannot find symbol
            WebView browser = new WebView();
            ^
  symbol: class WebView
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:60: error: cannot find symbol
            WebView browser = new WebView();
                                  ^
  symbol: class WebView
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:61: error: cannot find symbol
            WebEngine webEngine = browser.getEngine();
            ^
  symbol: class WebEngine
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:68: error: cannot find symbol
            Scene scene = new Scene(new Group());
            ^
  symbol: class Scene
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:68: error: cannot find symbol
            Scene scene = new Scene(new Group());
                              ^
  symbol: class Scene
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:68: error: cannot find symbol
            Scene scene = new Scene(new Group());
                                        ^
  symbol: class Group
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:57: error: cannot find symbol
        Platform.runLater(new Runnable() {
        ^
  symbol: variable Platform
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:85: error: cannot find symbol
    webEngine.getLoadWorker().stateProperty().addListener(new ChangeListener<Worker.State>() {
                                                              ^
  symbol:   class ChangeListener
  location: class ProjectOpenDiagnosticUiFx
/home/uli/Dokumente/Projekte/ganttproject-ganttproject-2.8.9/ganttproject/src/net/sourceforge/ganttproject/gui/ProjectOpenDiagnosticUiFx.java:85: error: package Worker does not exist
    webEngine.getLoadWorker().stateProperty().addListener(new ChangeListener<Worker.State>() {
`

**Comment by dbarashev** [comment]
You need a working JDK with JavaFX. I don't know the current state of openjfx and OpenJDK friendship. I use sdkman! to manage java runtimes and highly recommend it. There is a choice of JDK+FX from different vendors, e.g. Azul Zulu and BellSoft Liberica

**Comment by derUli** [comment]
I also tried to build the master branch with the "Java 11 Full SDK" from BellSoft which I installed as a *.deb package.
But there was another build error with Kotlin.

Used this instructions:
https://docs.ganttproject.biz/development/build/

**Comment by dbarashev** [comment]
So what was wrong with Kotlin? 
`master` compiles fine on our GitHub CI: https://github.com/bardsoftware/ganttproject/actions/runs/370241459

**Comment by uschmidt-velian** [comment]
Don't know what went wrong last time I tried but now it works with master
