### ISSUE TITLE
Navigation to the project end using the toolbar dropdown is not working properly

### ISSUE THREAD

**Issue by carloscadux** [bardsoftware/ganttproject#1804]
Hi,
I'm using GanttProject v2.99.2913 for Windows.
As shown in this screen-recording (https://bit.ly/38ycEj8), I've found two issues with the "Project End" selection functionality:
 
- selection not working properly, showing before the beginning of the project instead
- the "Project End" button becomes misplaced on the interface after clicking on it a couple of times
 
If you need further information, just let me know.
 
Thanks
Carlos

**Comment by dbarashev** [comment]
Thanks for reporting!
