### ISSUE TITLE
Boolean column type requests clicking 3 times to check or uncheck the box.

### ISSUE THREAD

**Issue by carloscadux** [bardsoftware/ganttproject#1805]
Hi,
I'm using GanttProject v2.99.2913 for Windows.
As shown in this screen-recording (https://bit.ly/3aGJfWD), boolean column type requests clicking 3 times to check or uncheck the box. Would it be a bug? Otherwise, could the number of clicks be decreased?
If you need further information, just let me know.
Thank you,
Carlos

**Comment by dbarashev** [comment]
Thanks for reporting!
