### ISSUE TITLE
Save / open dialog fails to open with French interface language

### ISSUE THREAD

**Issue by TheTrueTom** [bardsoftware/ganttproject#1808]
GANTProject version 3.0.2916

When trying to save as or open a file, the dialog  fails to open when the language is set to something other than English.

The error is (for French) : 
`No enum constant de.jensd.fx.glyphs.fontawesome.FontAwesomeIcon.BUREAU`

This is most probably due to the fact that the last part of the constant is translated (Bureau = Desktop in French) so it can't find the relevant icon.

**Comment by dbarashev** [comment]
Oh wow. Over-translation indeed. The update will be available tonight. Meanwhile, possible workarounds are:
* remove update 2916 from disk. It most likely sits in `.ganttproject.d/updates/update-2916` folder in your home directory. It is okay to just delete the whole directory.
* open file `updates/update-2916/biz.ganttproject.app.localization/translations/i18n_fr_FR.properties` in any text editor and remove all lines with `.icon` substring 

Thanks for reporting!

**Comment by OzOns** [comment]
Hi

The best workaround (for me, on PC windows) go back to English language (Edit/preferences)
Thks to the Dev Team for the great job. gret Appli. Adopted !

**Comment by dbarashev** [comment]
This shall be fixed by update 2917.
