### ISSUE TITLE
Numeric values are written as strings in Excel export

### ISSUE THREAD

**Issue by ulipillepalle** [bardsoftware/ganttproject#1814]
Real-Numbers are with decimal Point, not with comma. I'm coming from Germany and Excel doesn't recognize a dot-number as real-number.
Gantt knows that I'm german.
Gantt knows my correct date-format.
Why didn't he know the real-decimal-sign ?
The same issue is shown when is choosen Format: CSV.

**Comment by dbarashev** [comment]
It is a bug in Excel export. In fact just everything in Excel export in GP is written as string. We'll fix it in the next GP 3.0 update.

With respect to CSV, we want to be able to read CSV file produced by GP regardless of the regional settings in the operating system where the file was written or is read. As long as there were no decimal delimiter option in GP itself, we rely on Excel's ability to use different decimal delimiters.
