### ISSUE TITLE
Search box less clear than before

### ISSUE THREAD

**Issue by DecorteT** [bardsoftware/ganttproject#1816]
Hello,

Thank you for the new release version 3. 
Unfortunately I had to swap back quite quickly to the previous revision because of the search field that became rather unhandy and lost overview. I happen to use that often.
I try to show what I mean in the screenshots below. 

Old:
![Old](https://user-images.githubusercontent.com/38522476/107335815-af269480-6ab8-11eb-9876-95840415bfbf.jpg)

New:
![New](https://user-images.githubusercontent.com/38522476/107335838-b352b200-6ab8-11eb-8537-a23251dfd7d9.jpg)

Thank you for your effort,

Kind regards,

Tom Decorte

**Comment by dbarashev** [comment]
Yup, thanks for reminding. This will be fixed in the nearest updates.
