### ISSUE TITLE
Update to 3.0.3000 broken

### ISSUE THREAD

**Issue by NHenriquezS-0** [bardsoftware/ganttproject#1861]
I updated Gantt Project and it crashed after the installation, even with reinstalling it doesn't work.

**Comment by dbarashev** [comment]
When you say "crashed after installation" and "doesn't work", do you mean to say that you were using GP 2.8.+, then installed GP 3.0 and can't launch it now? Or anything else?

**Comment by NHenriquezS-0** [comment]
No, i was using GP 3.0 allready and i updated it, then i can't launch GP

**Comment by dbarashev** [comment]
So why "update to 3.0.3000"? Did you use any previous version (e.g. 2914)?

**Comment by dbarashev** [comment]
Anyway, you can remove the updates folder from your file system, which will rollback GP to the base version (I hope it is 3.0.3000, if it is not then please download and install the release distro of GP 3.0 from our web site). The updates folder is named `.ganttproject.d` and it sits in your personal home folder on disk.

After removing the updates folder, launch GanttProject and let it update to 3005.

If it won't launch after removing the updates folder, you can try removing the settings file. The settings file is named `.ganttproject` and it also sits in your personal home folder on disk.

**Comment by AJKwind** [comment]
Hello,

I have encountered the same issue. I was using GP 3.0 (don't know the exact version) and after the last update ganttproject just fails to run. It only shows the application icon for a while and then turns off.

Reinstalling the program doesn't work. I have looked for the settings file and the updates folder, but I couldn't find them. Could you clarify what you mean by "personal home folder"? My documents -> GanttProject folder is empty and the installation folder has no such folders/files. Could you also provide extensions of the files that I could try to delete aswell?

**Comment by dbarashev** [comment]
See this topic on the support portal: https://help.ganttproject.biz/t/knowledge-base-if-ganttproject-wont-launch-after-installing-a-new-update/2839

Most likely you skipped on of the updates (probably 3003) and this is the root cause. You need to remove all updates. Perhaps, removing .ganttproject from the home folder may also help.

The home folder on Windows systems is usually C:\Users\<your user name here>

**Comment by NHenriquezS-0** [comment]
Hey that fixed the problem! Remove the updates and let it update all again. Thanks for your help and sorry for my mistake explaining the issue.
