### ISSUE TITLE
Version 3.x for Mac using HomeBrew (Brew)

### ISSUE THREAD

**Issue by davemurphy** [bardsoftware/ganttproject#1867]
hi there,

can the Mac (dmg) version be updated to v3.x please for home-brew to find it correctly.

cheers
rgds Dave

**Comment by dbarashev** [comment]
No idea, sorry. We highly recommend using our distribution package on macOS, unless you really know what you're doing.

**Comment by davemurphy** [comment]
oh, I thought it was an official tie-in with HomeBrew.
You can see there ruby file here for GanttProject:   https://github.com/Homebrew/homebrew-cask/blame/46ea15868d014112b4f7fc6e268e13b0f29d55ca/Casks/ganttproject.rb

**Comment by davemurphy** [comment]
I've updated the Homebrew ruby file for GanttProject, which is working fine now.
Closing this ticket.
