### ISSUE TITLE
Resource Up/Down actions from context menu won't stop name editing

### ISSUE THREAD

**Issue by Hastaroth1** [bardsoftware/ganttproject#1868]
Steps to reproduce:
- In the "Resources Chart" tab, create 2 resources with different names.
- Left click once on the name column of a resource to edit it.
![image](https://user-images.githubusercontent.com/12807348/113899193-69690e00-9781-11eb-9ca5-deda1128a32f.png)
- Right click and press either the "Down" or "Up" option in the context menu.
![image](https://user-images.githubusercontent.com/12807348/113899700-e7c5b000-9781-11eb-8be6-bf2eb5294b71.png)

- The textbox to rename stays up and if you click anywhere else, the name of the item under the textbox will be changed.
![image](https://user-images.githubusercontent.com/12807348/113899276-7dad0b00-9781-11eb-8357-905fb299e29e.png)
![image](https://user-images.githubusercontent.com/12807348/113899312-869ddc80-9781-11eb-85b9-f0609249de1e.png)

Expected result:
The textbox should be closed.

Actual result:
The textbox is not removed and can override the name of the Resource that was moved to that slot.

It seems the only menu options that does remove the textbox is "Resource Properties". This issue isn't present if you replicate the same scenario with Tasks.

**Comment by dbarashev** [comment]
Thanks for reporting!
