### ISSUE TITLE
Version 3 doesn't start on Fedora 33

### ISSUE THREAD

**Issue by woprandi** [bardsoftware/ganttproject#1869]
I downloaded the zip bundle from the official website. Nothing happens when I run the bash script. I have OpenJDK JRE 11 installed, the script seems to correctly detects it

```
Searching for Java in /home/william/Téléchargements/ganttproject-3.0.3000/runtime/bin/java
...missing or not executable
Searching for Java in /usr/bin/java
...found openjdk version "11.0.10" 2021-01-19
JAVA_HOME=
JAVA_COMMAND=/usr/bin/java
GP_HOME=/home/william/Téléchargements/ganttproject-3.0.3000
user.dir=/home/william/Téléchargements/ganttproject-3.0.3000
```

The `$HOME/.ganttproject.d` folder is created but the subfolder logs is empty

**Comment by dbarashev** [comment]
You need Java Runtime with JavaFX libraries, e.g. BellSoft Liberica or Azul Zulu.

**Comment by pzygielo** [comment]
I'm running GP3 on FC 33 with OpenJDK as above with no problem.
But I have installed `openjfx` too.

**Comment by woprandi** [comment]
still not for me despite `openjfx` installed

**Comment by dbarashev** [comment]
Please install Java Runtime from BellSoft or Azul and make sure it is used as the default one.
This is explicitly written in the installation instructions on the web site: https://www.ganttproject.biz/download/gp30#zip

You can use a very convenient tool SDKMAN! for downloading and managing Java Runtimes (this is also mentioned on the web site).

**Comment by pzygielo** [comment]
@woprandi 
> still not for me despite `openjfx` installed

Forgive me - I forgot that I've also applied to `ganttproject` start script this patch to update classpath:
```diff
--- ganttproject	2021-02-01 16:04:20.000000000 +0100
+++ ganttproject	2021-02-28 09:39:28.091620216 +0100
@@ -185,6 +185,8 @@
 log "GP_HOME=$GP_HOME"
 log "user.dir=$(pwd)"
 
+CLASSPATH="$CLASSPATH:/usr/lib/jvm/openjfx/*"
+
 CLASSPATH="$CLASSPATH:$GP_HOME/eclipsito.jar"
 export CLASSPATH
 ECLIPSITO_ARGS="--verbosity 1 --version-dirs $GP_HOME/plugins:~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject"
```
