### ISSUE TITLE
Update to V3, file connectivity

### ISSUE THREAD

**Issue by DecorteT** [bardsoftware/ganttproject#1876]
Thank you for your work on version 3.
I am using "ganttproject-2.8.11-r2396" and installed "ganttproject-3.0.3000".
I can't assign the new version to my files via "Open With...", it keeps opening with previous version.
Removing the previous version doesn't help, then there's no action.
The file only opens if it's selected from within the program.
For the moment I prefer to go back to "ganttproject-2.8.11-r2396", but looking forward to new updates.
Maybe with built-in update check and upgrade?

**Comment by dbarashev** [comment]
Uninstall GP 2.8.11. Install GP 3.0. It works fine in my tests. The installers are nearly the same when it comes to file associations.

You can also change file associations manually. There are many howtos which are easy to google, e.g. this one: https://www.lifewire.com/how-to-change-file-associations-in-windows-2624477

**Comment by DecorteT** [comment]
Apparently I had yet another, older, version installed on my PC as well (2.7).
When I uninstalled this one too, I could assign the version 3 to may files.
Thank you, I'm sorry for the inconvenience.
