### ISSUE TITLE
Double click to open Task Properties very often opens previously selected task

### ISSUE THREAD

**Issue by alinuxexpert** [bardsoftware/ganttproject#1903]
I haven't found a way to reproduce this yet. However, it happens so very, very often (in about 30% of the time), that I'm certain that you will be able to reproduce it. I'm running GanttProject 3.0.3005. I am often creating small schedules with 5-10 tasks at most. In about 30% of the time, when I double click a task to view the Task Properties, I find that GanttProject actually opens the Task Properties of the task that was previously selected. This is quite annoying as I often end up modifying the wrong task.

**Comment by dbarashev** [comment]
Duplicates #1821 
Unfortunately, no, I have never been able to reproduce it. Chances are that it depends on the specific characteristics of the machine/OS where GanttProject is running. Please post the contents of the log file when it happens and try playing with the appearance settings.
