### ISSUE TITLE
JavaVM executable not found on Arch Linux

### ISSUE THREAD

**Issue by rbaj** [bardsoftware/ganttproject#1911]
Version 3.0 cannot find java on arch linux 5.12.3-arch1-1. Version 2.8.11 works fine. I've tried version 3.0 with several different versions of java (including the liberica jre11 with openfx) and get the same result for all. I've also tried setting JAVA_HOME and starting with --java-home as suggested in the error message but neither worked.

Searching for Java in /opt/ganttproject/runtime/bin/java
...missing or not executable
Searching for Java in /usr/bin/java
...this seems to be an old Java Runtime
Searching for Java in /usr/lib/jvm/default/bin/java
...this seems to be an old Java Runtime
Searching for Java in /usr/lib/jvm/default-runtime/bin/java
...this seems to be an old Java Runtime
Searching for Java in /usr/lib/jvm/java-11-openjdk/bin/java
...this seems to be an old Java Runtime
Searching for Java in /usr/lib/jvm/java-11-openjfx/bin/java
...missing or not executable
Searching for Java in /usr/lib/jvm/java-7-openjdk/bin/java
...missing or not executable
Searching for Java in /usr/lib/jvm/java-8-openjdk/bin/java
...missing or not executable
Searching for Java in /usr/lib/jvm/liberica-jdk-11-full/bin/java
...this seems to be an old Java Runtime
Searching for Java in /usr/lib/jvm/liberica-jdk-full/bin/java
...this seems to be an old Java Runtime
Searching for Java in /usr/lib/jvm/liberica-jre-11-full/bin/java
...this seems to be an old Java Runtime
JavaVM executable not found. You may want to set the path to the root of your Java Runtime installation in JAVA_HOME environment variable or pass it to ganttproject in --java-home argument

**Comment by dbarashev** [comment]
What do you get if you run `/usr/lib/jvm/liberica-jdk-11-full/bin/java -version` ?

**Comment by dbarashev** [comment]
Also, how did you install GanttProject? Did you download ZIP from our website or did you use Arch packages?

**Comment by rbaj** [comment]
```
$ /usr/lib/jvm/liberica-jdk-11-full/bin/java -version
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM (build 11.0.11+9-LTS, mixed mode)
```
Same result with an Arch package and the ZIP.

**Comment by dbarashev** [comment]
The problem is that I don't see a log line 
`... found openjdk version "11.0.11" 2021-04-20 LTS` which is [supposed to be there](https://github.com/bardsoftware/ganttproject/blob/BRANCH_3.0.X/ganttproject-builder/ganttproject#L130). Chances are that the previous line, which runs `java -version` is missing too. Are you sure that you're running exactly that `ganttproject` script which comes from the ZIP arhive?

**Comment by rbaj** [comment]
I thought I was but I've just downloaded the ZIP again and version 3.0 works. No idea what changed. Clearly the problem was on my side. Thanks a lot for your help regardless.
