### ISSUE TITLE
Copy paste between seperate projects

### ISSUE THREAD

**Issue by bijannaveh** [bardsoftware/ganttproject#1924]
If we could copy and paste tasks with their notes and all their attributes between two seperate files, this would be great.

**Comment by dbarashev** [comment]
Copy'n'paste between projects works fine in my GanttProject 3.1 on Linux.

**Comment by dbarashev** [comment]
https://user-images.githubusercontent.com/2028330/123627329-8827ef80-d81a-11eb-990a-4c0739901a8f.mp4

**Comment by dbarashev** [comment]
It also works fine on Windows. I did not test on macOS (and opening two instances of GanttProject app on macOS [is a bit tricky](https://help.ganttproject.biz/t/open-several-windows-in-mac/1689/2)) but I am almost sure that it works too.

**Comment by bijannaveh** [comment]
Hi Dimitry,
you're right. It seems that I was doing it in a wrong way before. Thank you for clarification.

**Comment by bijannaveh** [comment]
> It also works fine on Windows. I did not test on macOS (and opening two instances of GanttProject app on macOS [is a bit tricky](https://help.ganttproject.biz/t/open-several-windows-in-mac/1689/2)) but I am almost sure that it works too.

Hi Dimitry,
you're right. It seems that I was doing it in a wrong way before. Thank you for clarification.

**Comment by bijannaveh** [comment]
>  screencast_00004.mp4

Thanks a lot for sharing this.
