### ISSUE TITLE
Cost as of now (task cost x percentage complete)

### ISSUE THREAD

**Issue by bijannaveh** [bardsoftware/ganttproject#1925]
If there was a column showing the value = (task total cost x complete percentage) then we could know how much we can charge our client as of today, it would be very helpful

**Comment by dbarashev** [comment]
I acknowledge that exactly this formula might be sufficient for some projects, however, I expect that many other projects will require more customization which just cannot be appropriately exposed in the UI.
There is an enhancement request about simple formulae custom column which has good chances to be closed rather soon, so I am closing this one in favor of #150

**Comment by bijannaveh** [comment]
> I acknowledge that exactly this formula might be sufficient for some projects, however, I expect that many other projects will require more customization which just cannot be appropriately exposed in the UI.
> There is an enhancement request about simple formulae custom column which has good chances to be closed rather soon, so I am closing this one in favor of #150

being able to add simple formula in custom fields will be awesome. It will take GanttProject to another level while keeping it simple and clean as intended.
