### ISSUE TITLE
GanttProject entry in Windows add/remove programs tool is missing icon, version, size, etc

### ISSUE THREAD

**Issue by Asgatlat** [bardsoftware/ganttproject#1926]
hello,

there is no icon / version / details / size in the add/remove windows menu 
https://ibb.co/XfnFVmT

**Comment by dbarashev** [comment]
When you say "add/remove window", do you mean "add/remove programs tool" ?  Like this? https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98

**Comment by Asgatlat** [comment]
yes, please see my link in my first message, it is a screenshot showing the missing information

**Comment by dbarashev** [comment]
Sorry, my knowledge of French is very limited and it is not possible to translate the image using Google Translate, that's why I am asking to clarify.

**Comment by Asgatlat** [comment]
no problem,
here a english screenshot:
![add remove](https://user-images.githubusercontent.com/86599367/123629830-0c777400-d815-11eb-8ecc-8502048dec93.jpg)
so for ganttproject, there is no size information of the program, no version information, no logo ...
you can see that for others program there is informations
