### ISSUE TITLE
Week Numbers Incorrect in 2021 (ISO8061)

### ISSUE THREAD

**Issue by chrismerck** [bardsoftware/ganttproject#1938]
GanttProject 3.1.3102
MacOS 10.15.7

The work week numbers for 2021 are incorrect. They counted the week containing Friday January 1st 2021 as "Week 1", but this is incorrect according to ISO8061, which defines Week 1 of the year as that week which contains the year's first Thursday.

This ISO 8061 standard is widely accepted and uncontroversial. However, I have found the same bug with another MacOS application (none other than Apple's built-in MacOS Calendar app). So, perhaps this is actually a bug in the underlying MacOS library rather than on the GanttProject side. That depends how the week number is computed.

See: https://en.wikipedia.org/wiki/ISO_8601

<img width="71" alt="Screen Shot 2021-08-09 at 12 35 26" src="https://user-images.githubusercontent.com/628921/128741529-46431dd9-4a63-4f2f-9900-e7d2d44f4f22.png">

**Comment by dbarashev** [comment]
Please read this:
https://help.ganttproject.biz/t/2021-calendary-week-does-not-fit/3107

**Comment by chrismerck** [comment]
Awesome, thank you.

> The first week of the year 2021 starts on 21/12/2020 in US

Do you know what document standardizes this? Every resource I find online re: week numbers in USA concurs with the ISO week numbering.

**Comment by dbarashev** [comment]
As to the best of my knowledge, people in US do not care about the week numbering and just start counting from January 1st. They get partial weeks at the beginning and at the end of year this way. In Java platform with US locale, the week where January 1st belongs to is the first week of the year.

**Comment by dbarashev** [comment]
https://devblogs.microsoft.com/oldnewthing/20160311-00/?p=93144
