### ISSUE TITLE
Expand resources to see tasks related to

### ISSUE THREAD

**Issue by Lupo72azur** [bardsoftware/ganttproject#1968]
in former versions it was possible to expand Resources in the Resources Chart to see, which tasks are related to a certain resource.
In 3.1.3100 this isn't possible any more(?) (see attached pictures)
Used System WIN10 Enterprise (10.0.19042)
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎09.‎09.‎2021
OS build	19042.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

Repro steps:
create to tasks
create two resources
add these two resources to the two tasks
change to Resources Chart
on the left there is no "+" to expand resources and see the related tasks
(although you can see the Assigments for a certain Resource in the details)
![Gantt_Tasks](https://user-images.githubusercontent.com/94462355/142000505-917ad23b-f457-455f-89a2-f833d82ef1c6.png)
![Gantt_Resources](https://user-images.githubusercontent.com/94462355/142000528-d0cdedde-90ce-4b6c-8bbd-6642a5b08a82.png)
![Gantt_Assignments](https://user-images.githubusercontent.com/94462355/142001580-b59de119-9bf2-4d68-84b0-15b379c4c3c5.png)

**Comment by dbarashev** [comment]
This issue was fixed in update 3102. Please update your GanttProject.

**Comment by Lupo72azur** [comment]
Hi dbarashev, many thanks for your reply, highly appreciated!
But there's no chance to update to 3102...
Seems the update mechanism doesn't work, doesn't recognize, that there's an update available, maybe some special configuration in the company's network necessary?
Best regards

**Comment by Lupo72azur** [comment]
Hi dbarashev, just an update:
Ganttproject on private PC is doing updates, on company's laptop it doesn't.
Maybe it needs connection which is not possible to establish from our company's network because of settings/firewall/etc.?
Best regards
