### ISSUE TITLE
PERT chart error in the print preview

### ISSUE THREAD

**Issue by DidierMorandi** [bardsoftware/ganttproject#1974]
Hi,
I have a 110 tasks project, GANTT and Resources preview before print work fine, but PERT yields:

C:\Users\client\ganttproject.log
GanttProject 3.1.3103
Settings file:
	location: C:\Users\client\.ganttproject
	size:5875
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-3.1
java.home: C:\Program Files (x86)\GanttProject-3.1\runtime
java.ext.dirs: null
java.io.tmpdir: C:\Users\client\AppData\Local\Temp\
java.runtime.version: 11.0.11+9-LTS
java.vendor: BellSoft
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: BellSoft
java.vm.version: 11.0.11+9-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs plugins;~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject D:\Documents\- Tournadous - Cusoun de lus\tournadous.gan
user.country: FR
user.dir: C:\Program Files (x86)\GanttProject-3.1
user.home: C:\Users\client
user.language: fr
user.timezone: Europe/Paris

déc. 06, 2021 8:06:19 AM biz.ganttproject.LoggerImpl error
GRAVE: **Can't set awtAppClassName** (needed on Linux to show app name in the top panel)
déc. 06, 2021 8:06:19 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Deleting old auto-save files
déc. 06, 2021 8:06:20 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: Creating main frame...
déc. 06, 2021 8:06:20 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 1. loading look'n'feels
déc. 06, 2021 8:06:20 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 2. loading options
déc. 06, 2021 8:06:21 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 3. creating menus...
déc. 06, 2021 8:06:21 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 4. creating views...
déc. 06, 2021 8:06:21 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 5. calculating size and packing...
déc. 06, 2021 8:06:21 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 6. changing language ...
déc. 06, 2021 8:06:21 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 7. first attempt to restore bounds
déc. 06, 2021 8:06:21 AM biz.ganttproject.LoggerImpl debug
PRÉCIS: 8. finalizing...
déc. 06, 2021 8:06:30 AM net.sourceforge.ganttproject.GPLogger logToLogger
AVERTISSEMENT: null
java.lang.UnsupportedOperationException
	at org.ganttproject.chart.pert.PertChart.getStartDate(PertChart.java:83)
        etc. etc.

I deleted my Temp folder, no changes.
Any clue, anyone, please?
Thanks,

**Comment by dbarashev** [comment]
Please share the full log, what is supposed to be instead of "etc. etc."

**Comment by DidierMorandi** [comment]
here you are.
I add that printing works fine despite the error message at preview time
[ganttproject.log](https://github.com/bardsoftware/ganttproject/files/7673846/ganttproject.log)
e.

**Comment by dbarashev** [comment]
So, the chart itself appears normally, only the print preview is the issue?

**Comment by DidierMorandi** [comment]
Yep.
