### ISSUE TITLE
Need MSI installer for deployment 

### ISSUE THREAD

**Issue by Asgatlat** [bardsoftware/ganttproject#1983]
Hi,

could you compile a MSI file for Windows to easily deploy your program with GPO?
thank you

**Comment by dbarashev** [comment]
I don't know what is GPO. Googling says it is Group Policy (?) but since I don't know the details anyway, let me ask what is wrong with .exe installer and this GPO, whatever it is?

**Comment by Asgatlat** [comment]
Usually msi packages are provided for system administrators who would have the need to deploy the software to several terminals over a network.

**Comment by dbarashev** [comment]
But what is wrong with exe? It can be used in command-line mode without the GUI, if that's the issue.

**Comment by dbarashev** [comment]
Anyway, as far as I can see, there's a choice of EXE to MSI converters, e.g. this one (I didn't try it) https://www.exemsi.com/
