### ISSUE TITLE
Data Display Eerror

### ISSUE THREAD

**Issue by bigbeard2017** [bardsoftware/ganttproject#1984]
OS:ubuntu 20.04
GrantProject Version:3.1.3103
Date errors are displayed as  "2022/02/46", the correct date is 2022/02/15
As long as there is a date column, the table displays the wrong date format.

**Comment by dbarashev** [comment]
You need  to change your custom date format from `yyyy/MM/DD` to `yyyy/MM/dd`. Or just use the default for your locale.
Edit > Settings > Application UI > Date format
