### ISSUE TITLE
"open other project" shows nothing

### ISSUE THREAD

**Issue by nigo81** [bardsoftware/ganttproject#1985]
![image](https://user-images.githubusercontent.com/38601513/148571591-4647d350-94a8-4bb2-89a5-e1a45b408307.png)
when i lanch ganttproject and press "ctrl+o" to open a file, the ui shows nothing.
I can't see the file dialog or recent files.

ganttprojects version:3.1.3100

**Comment by nigo81** [comment]
my os is ArcoLinux.
the log is:
```
/home/nigo/.ganttproject.d/logs/.ganttproject-20220108000422.log

GanttProject 3.1.3100
Settings file:
	location: /home/nigo/.ganttproject
	size:4918
	is readable: true
java.class.path: :/opt/ganttproject/eclipsito.jar
java.home: /usr/lib/jvm/java-11-openjdk
java.ext.dirs: null
java.io.tmpdir: /tmp
java.runtime.version: 11.0.13+8
java.vendor: Oracle Corporation
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 11.0.13+8
os.arch: amd64
os.name: Linux
os.version: 5.15.5-arch1-1
sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs /opt/ganttproject/plugins:~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject -log true -log_file /home/nigo/.ganttproject.d/logs/.ganttproject-20220108000422.log
user.country: US
user.dir: /home/nigo
user.home: /home/nigo
user.language: en
user.timezone: Asia/Shanghai

Jan 07, 2022 4:04:26 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Jan 07, 2022 4:04:29 PM net.sourceforge.ganttproject.GPLogger log
INFO: Starting RSS check...
```

**Comment by dbarashev** [comment]
You need Java Runtime with JavaFX libraries. The runtime from Oracle does not include JavaFX. You need BellSoft Liberica or Azul Zulu.

**Comment by nigo81** [comment]
> You need Java Runtime with JavaFX libraries. The runtime from Oracle does not include JavaFX. You need BellSoft Liberica or Azul Zulu.

Thanks.I have solve the problem.
In arch linux os:
1. install liberica-jdk-11-full-bin
```bash
yay -S liberica-jdk-11-full-bin
```
2. check default java environments:
```bash
archlinux-java status
```
the results is:
```bash
Available Java environments:
  java-11-openjdk (default)
  java-17-openjdk
  java-8-openjdk
  liberica-jdk-11-full
```
3. set  liberica-jdk-11-full as default java environment:
```bash
sudo archlinux-java set liberica-jdk-11-full
```
then start ganttproject , I could open other projects:
![image](https://user-images.githubusercontent.com/38601513/148672405-48bf224c-9e4f-4227-aa67-742234664bf2.png)
