### ISSUE TITLE
Task table row padding option

### ISSUE THREAD

**Issue by cakepuller** [bardsoftware/ganttproject#2020]
Hi GanttProject Devs
Thank you for creating and maintaining GanttProject. :)
I recently updated to v3.2.32 from v3.0 and found that the row height for tasks/gantt a bit too much, taking up too much vertical space.  Looks like 50% more than v3.0's.  Any chance there could be an option to reduce that row height to, say, v3.0's?  This is so that one may see more tasks in one screen.
:-)
Thanks.
-cp

**Comment by dbarashev** [comment]
You can find the option which controls the row height here:
https://help.ganttproject.biz/t/3-2-changed-output-of-png-export/4292

There is no UI for this option yet.

**Comment by cakepuller** [comment]
@dbarashev 
THANKS, it works!
Now, about that big fat ribbon under the menu bar... :)  (just kidding)
Thanks again for the prompt advice.
