### ISSUE TITLE
`expand` attribute of task does not take effect

### ISSUE THREAD

**Issue by guenbakku** [bardsoftware/ganttproject#2021]
Hi GanttProject Devs
Thank you for creating and maintaining GanttProject.

After updated to version v3.2.32, every time when I open an existing project, all tasks in that project are automatically expanded. 
Is there any option that make the gantproject remember the expand/collapse status of tasks in previous save?

In previos vesion 3.0.0, there was no problem with this behavior.

Thank you.

**Comment by dbarashev** [comment]
Ooops, indeed, it is broken. Thanks for reporting! Will be fixed in the first bugfix update.
