### ISSUE TITLE
Column automaticilly resized when alerts columns is shown

### ISSUE THREAD

**Issue by Loughead** [bardsoftware/ganttproject#2031]
Hi GanttProject Devs,

Since 3.2.3210 version, some column are automaticilly resized under specific conditions. #2026

The reason seems to be when "Alerts" column is shown, all this actions reduce column width:
- Opening "Manage columns"
- Creating new task 
- Saving project
- Opening & Closing task properties
- Assigning ressource from task menu

Thanks for all your contributions to improve this soft :D

**Comment by dbarashev** [comment]
Please record a screencast showing this issue.

**Comment by dbarashev** [comment]
Ah, I see, it seems that it is also necessary to show at least one column other than name-begin-end triple and alerts. And the alerts gets duplicated as an icon and as a separate column.
