### ISSUE TITLE
Cannot Open Files

### ISSUE THREAD

**Issue by RandomExplosion** [bardsoftware/ganttproject#2044]
# Expected Behaviour: 
Pressing the open button opens the my projects window and entering the Open Other Project tab shows a file browser (of some description)
# Actual Behaviour: 
No file browser is shown under the other project tab (see below)
![image](https://user-images.githubusercontent.com/42421984/156905620-966a95bc-51db-4bd0-a326-addde2c56597.png)

# System Information
OS: Arch (Endeavouros) Linux x86_64
Installer: https://aur.archlinux.org/packages/ganttproject
S

**Comment by dbarashev** [comment]
You need to install Java Runtime with JavaFX.
See #1985
