### ISSUE TITLE
Holiday creation date range

### ISSUE THREAD

**Issue by markluax** [bardsoftware/ganttproject#2045]
Vacations often come in blocks of several days. Adding as one-off is a drag.
Having a start-date to end-date selection would help a lot.

(Not sure whether the purpose of "Recurring" holidays is supposed to handle this, since the date-format parsing doesn't work there. Needs another issue for that, I think)

**Comment by dbarashev** [comment]
Duplicates #946 
Thanks for reminding about this.

**Comment by markluax** [comment]
@dbarashev sorry, didn't see that old one. It has different tags. Would be great if this feature was added.
