### ISSUE TITLE
Export/Print problem

### ISSUE THREAD

**Issue by francoergo** [bardsoftware/ganttproject#2046]
I just installed the latest versione and I noticed there is a problem when I try to export/print the diagram. As you can see on the image below, the gray bar at the top is super-big and this makes the rest of the diagram small.

![image](https://user-images.githubusercontent.com/101145110/157114291-08f76274-1150-4fa7-9060-33283730a7a8.png)

**Comment by dbarashev** [comment]
You need to choose a smaller image as the logo.
