### ISSUE TITLE
Restart GanttProject after update is broken

### ISSUE THREAD

**Issue by higamma** [bardsoftware/ganttproject#2063]
When I update, ganttproject cannot reboot

https://user-images.githubusercontent.com/166818/159596801-d7c80d75-57ac-4a18-9ec0-5e199cdb807d.mov

https://user-images.githubusercontent.com/166818/159596814-6f93b405-af5b-4751-a9f0-210b47f5eb51.mov

.

**Comment by dbarashev** [comment]
It will be fixed once 3240 is installed

**Comment by Asgatlat** [comment]
> It will be fixed once 3240 is installed

yes, it is working now 👍
