### ISSUE TITLE
Issues with the clipboard operations with tasks having dependencies

### ISSUE THREAD

**Issue by dasu88** [bardsoftware/ganttproject#2104]
When copying and pasting tasks normally, the right window will increase with the Gantt column, but if the dependency is increased, copying and pasting will cause the right window to be abnormal and unable to scroll, which will cause the program to crash in serious cases, with the deletion of javaw.exe interrupting the operation
![錄製_2022_04_26_07_53_02_991](https://user-images.githubusercontent.com/23251263/165193838-d0a1d846-f532-401f-b63c-606f76497a9d.gif)
.

**Comment by dbarashev** [comment]
Thanks for reporting!
