### ISSUE TITLE
Tasks and Timeline does not match

### ISSUE THREAD

**Issue by FlorianKolich** [bardsoftware/ganttproject#2113]
Dear all, 
the tasks on the left and the timeline on the right does not match. This means the timline is app. one row to high.

 
Can you give me a solution 

Best regards Florian

**Comment by dbarashev** [comment]
Touching the chart, e.g. dragging it back and forth usually makes everything lined up.

**Comment by FlorianKolich** [comment]
Thanks, now it works again.
Have a nice day.
Florian

Florian Kolich
Operative Head of Product Segment Endodontics
Tel +49 7345 805-119
Von: Dmitry Barashev ***@***.***>
Gesendet: Sonntag, 1. Mai 2022 19:54
An: bardsoftware/ganttproject ***@***.***>
Cc: Kolich Florian ***@***.***>; Author ***@***.***>
Betreff: [EXTERNAL] Re: [bardsoftware/ganttproject] Tasks and Timeline does not match (Issue #2113)

CAUTION: This email originated from outside the COLTENE organization. Do not follow guidance, click links or open attachments unless you recognize the sender and know the content is safe.


Touching the chart, e.g. dragging it back and forth usually makes everything lined up.

-
