### ISSUE TITLE
Portuguese translation: "Pessoas" (Resources) instead of "Pessoa" (menu and task properties)

### ISSUE THREAD

**Issue by carloscadux** [bardsoftware/ganttproject#2138]
Hi.
In the "menu" and "task properties", the current Portuguese translation is "Pessoa" (singular).
Pessoas (plural) is more proper. 
Could you please consider updating it?
Thanks!

Ps.: Other places "Pessoa" is used in singular is already perfect.

![image](https://user-images.githubusercontent.com/7339389/171430099-8ec5de76-145e-46a2-af33-8978736794c7.png)

**Comment by dbarashev** [comment]
We use Crowdin service for translating the user interface. If you want to contribute your updates, please register on CrowdIn and submit the changes here: https://crowdin.com/translate/ganttproject/27698/en-pt

**Comment by carloscadux** [comment]
Thanks for informing about Crowdin.
I just updated there a few translations, and completed all translations that were missing.
Cheers
