### ISSUE TITLE
New Task Date: Windows and Gantt are set properly to "today", but when a new task is created the date added is "yesterday"

### ISSUE THREAD

**Issue by carloscadux** [bardsoftware/ganttproject#2139]
Hi.
As shown in the screen-recording, Windows and Gantt are set properly to the current date.
But when a new task is created the date added is yesterday.
Could you please consider when a new task date is added automatically by Gantt Project, it matches the current date (today) instead of yesterday?
Thanks!

![Gantt_2022-06-01_11 43 14](https://user-images.githubusercontent.com/7339389/171433417-6613da3f-6202-4450-bbe6-4d763fe56293.gif)

**Comment by dbarashev** [comment]
The default start date is first date which is visible in the chart area. In your screencast, the first visible date is May 31st.
