### ISSUE TITLE
Quick navigation dropdown shows up far from the click point

### ISSUE THREAD

**Issue by carloscadux** [bardsoftware/ganttproject#2142]
Hi.

As shown in the screenshot below, currently you need to click on (1) today on the right, then (2) move the mouse to the very left side to interact with the drop-down menu.

The suggestion is that today's drop-down menu could appear just below the click area, making steps (1) and (2) faster and more UI friendly.

Thanks!

![image](https://user-images.githubusercontent.com/7339389/172183617-ef896e37-0edd-42ba-bb7a-254128ef6290.png)

**Comment by dbarashev** [comment]
Related: #1747
