### ISSUE TITLE
Non-internationalized string in custom properties UI

### ISSUE THREAD

**Issue by carloscadux** [bardsoftware/ganttproject#2143]
I searched the [ptbr translation](https://crowdin.com/translate/ganttproject/27698/en-ptbr) in crowding, but didn't find the following string, which is not translated to ptbr yet:
(default) => (padrão)
Could you please inform if that string can be translated?
Thanks

![image](https://user-images.githubusercontent.com/7339389/172237873-206efbe1-8d9b-4c3e-ac67-aa0c159c2f72.png)

**Comment by dbarashev** [comment]
I removed this string completely.
