### ISSUE TITLE
The tool name becomes a rectangle.

### ISSUE THREAD

**Issue by highrev123** [bardsoftware/ganttproject#2160]
I'm using it on Windows 10.
The display of the menu bar etc. is displayed as a rectangle. How can I fix it?
![manu](https://user-images.githubusercontent.com/73318811/173494377-8c200543-b2a0-40f3-a51f-7553baef4f80.png)

**Comment by C-R-L** [comment]
The font used by the application is the problem.

Press [**Ctrl**]+[**G**] to open the "Preferences" menu.
then, on the second list-box "Application Font" choose another font like "Arial".

**Comment by highrev123** [comment]
All the settings are displayed as rectangles, and I cannot select Arial etc.It is a symptom only of GanttProject.

![setting](https://user-images.githubusercontent.com/73318811/173556722-5f96d6ef-9c0c-437a-8d67-a281c0a08dc6.png)

**Comment by dbarashev** [comment]
As mentioned above, you need to choose a font which supports the symbols from your language (is it Japanese or Chinese?)
Droid Sans Fullback Full H must be ok for that.

You can change the font by editing the config file. The config file name is `.ganttproject` and it sits in _your user home folder_ (which is usually `C:\Users\<user name>` on Windows). Find the line which looks like this (the font name will likely be different)

```
    <option id="ui.appFontSpec" value="Droid Sans Fallback Full H-NORMAL"/>
```

and replace the font name in `value` with e.g. that "Droid Sans Fallback Full H-NORMAL".
