### ISSUE TITLE
Some French texts do not display the apostrophe.

### ISSUE THREAD

**Issue by C-R-L** [bardsoftware/ganttproject#2161]
In some places, the apostrophes from the French translation are invisible.
Maybe use an other sign or used the encode `&apos;` / `&#39;` / `&rsquo;` / `&#8217;` / `’` / …

About page:
![image](https://user-images.githubusercontent.com/96880963/173537030-99f2adec-c817-458f-b5a0-1a48b47fa0b2.png)

Scheduler report: (no Title name?)
![image](https://user-images.githubusercontent.com/96880963/173536987-4f0fc157-efd6-421e-8070-e13e6dd9b2f4.png)

My projects:
![image](https://user-images.githubusercontent.com/96880963/173550005-9898838a-872f-4102-a28c-764f24590bd3.png)

**Comment by dbarashev** [comment]
Thanks for reporting. Apostrophes must be doubled. I'll check if it can be configured in Crowdin.
