### ISSUE TITLE
An option to change the default directory for GanttProject documents

### ISSUE THREAD

**Issue by blame2020** [bardsoftware/ganttproject#2174]
GanttProject v3 creates directory such as `$HOME/Documents/GanttProject`  on startup.

However, I want to manage files with a directory layout that I have decided.
So that's a little intrusive to me.

Is it possible to disable or change the creation of a directory?

**Comment by dbarashev** [comment]
This is not possible at the moment, unless you change the source code and build your own package. I converted this issue to enhancement request.

**Comment by blame2020** [comment]
Thank you for your work!
I'll try enhanced version.

**Comment by dbarashev** [comment]
You don't know yet how it works :)
The option has no UI. You need to edit `.ganttproject` file which sits in your home directory and insert the following tag:

```xml
<option id="localStorage.defaultDirectory" value="/tmp"/>
```

Replace the value attribute with the path to your favorite directory.
