### ISSUE TITLE
Suggestion: Add filter (free search and resource) for selection on previous task 

### ISSUE THREAD

**Issue by DinoBellini** [bardsoftware/ganttproject#2206]
![immagine](https://user-images.githubusercontent.com/109912954/180654814-cbc67f67-1a0d-40c2-8cd8-62ece94a68a4.png)

it is more easy to search in all open tasks by resource;

**Comment by dbarashev** [comment]
I don't understand the request, sorry. What do you mean as "filter for selection on previous task"?

**Comment by DinoBellini** [comment]
In a task, adding a predecessor/ previous / dependancy task is easy if you have a few task, if you have lots of tasks it could be usefull to add a textual search filter through the list.

**Comment by dbarashev** [comment]
Duplicates #176
