### ISSUE TITLE
Task dates in the table won't update immediately after changing the project start date

### ISSUE THREAD

**Issue by DinoBellini** [bardsoftware/ganttproject#2208]
Begin data for task is not updated in gant column view (it is ok in graphic calendar view) after modifying properties data

**Comment by dbarashev** [comment]
For the record, it updates after the first selection change in the table.

**Comment by dbarashev** [comment]
Scenario:
1. Create a task in a new project
2. Open Project > Properties > Project calendar and change the project start date to any other date. Click OK

Expected: task start date in the task table updates immediately
Actual: it updates only after some activity in the task table, e.g. after the selection change
