### ISSUE TITLE
Only one task from a multiselection can be dragged

### ISSUE THREAD

**Issue by arrkh** [bardsoftware/ganttproject#2217]
Hi,

I just updated from version 2.8.10 to 3.2.3246. Now, I cannot move more than one task at the same time inside the chart. In 2.8.10 it was possible to select several tasks by holding Ctrl and clicking on the bars, than move them all at once while holding Ctrl. That doesn't work anymore, it just moves one task.

**Comment by dbarashev** [comment]
Thanks for reporting, I will look at this issue.
