### ISSUE TITLE
Better png export

### ISSUE THREAD

**Issue by Zahrun** [bardsoftware/ganttproject#2246]
Hi

Thank you for the great software.
I find the png export difficult to read.
I think if we could set the font type and font size, it could be easier to read.
See the default png export:
![image](https://user-images.githubusercontent.com/10415894/192086342-e578ec57-9a2d-4131-ab70-d84d0ddd3d7f.png)
What I did was to export as pdf, open it in LibreOffice Draw, change the font size and make it bold. Then replace the chart in with GIMP since Draw screws it. I find it easier to read:
![image](https://user-images.githubusercontent.com/10415894/192086427-30708675-1692-4c0d-bbac-b1bb943621b8.png)
But the process of manually editing is long.
I wished we could set the export font size and type.

**Comment by dbarashev** [comment]
Duplicates https://github.com/bardsoftware/ganttproject/issues/2220
