### ISSUE TITLE
Huge display | unusable app

### ISSUE THREAD

**Issue by titou3011** [bardsoftware/ganttproject#2248]
Hey from France.
I changed sizes in "preferences" option and now my app is unusable.
How can i reset the appearence ?

![image](https://user-images.githubusercontent.com/78096053/192464940-74212c4f-856c-44fa-89ab-bbe4d47327e7.png)

Many thanks

**Comment by dbarashev** [comment]
Hello, please refer to FAQ article on the support portal: https://help.ganttproject.biz/t/read-me-first-faq-and-search/8
(I just've added a new entry there)

**Comment by titou3011** [comment]
That's great, thanks a lot !
