### ISSUE TITLE
Performance issues on Apple Silicon platform 

### ISSUE THREAD

**Issue by samqjf** [bardsoftware/ganttproject#2259]
Numerous reports about chart interface being unresponsive as soon as the first task is created.

https://help.ganttproject.biz/t/gp-3-2-is-laggy-on-m1pro-mbp/5190
https://help.ganttproject.biz/t/macos-monterey-et-puce-m1-max/4943/
https://help.ganttproject.biz/t/gantt-software-started-lagging-while-using-apple-m1/2536/

**Comment by dbarashev** [comment]
Please try GanttProject 3.3 Beta packaged for Apple Silicon. See the [announcement on Facebook](https://www.facebook.com/ganttproject/posts/pfbid0236P6rQpsPJJRK9FLty6D4c75dnraNQfeuW7CBan5XNSni8NNJfYkh5u83cA1PjbPl) or [on the Support Portal](https://help.ganttproject.biz/t/macos-monterey-et-puce-m1-max/4943/31)
