### ISSUE TITLE
Recent colors stays empty

### ISSUE THREAD

**Issue by balks** [bardsoftware/ganttproject#2302]
Thanks for the nice software

Using 3.3.3292. 
It looks like the 'recent colors' right of the color-picker (popup of the task-details)- stays empty. Well, it will include the color of selection, but after 'ok' and re-opening the dialog the recent color-matrix is empty again. 

![image](https://user-images.githubusercontent.com/14887900/222120822-bfc92ba3-b760-483e-a177-5abcc28629da.png)

**Comment by dbarashev** [comment]
This is the way it works in Java platform. It shows the recently selected colors. We show the recently chosen colors in a bottom pane, above the buttons (this is the reason why it is there).
