### ISSUE TITLE
Wrong ordering by outline number

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/ganttproject#2336]
1. Create 10 top-level tasks and 2 subtasks under task 1
2. Make the outline number column visible and sort tasks by the outline number

The tasks will be ordered lexicographically, as if outline numbers were just strings.

Expected task order:
```
1
1.1
1.2
2
.
.
9
10
```
Actual order:
```
1
1.1
1.2
10
2
.
.
9
```

Discussion on the support portal:
https://help.ganttproject.biz/t/sort-tasks-by-outline-number/7403

**Comment by Radian327** [comment]
May I suggest this update to the bug report:

Insert WBS 1.1.1 and 1.1.2 between the 1.1 and the 1.2?  This ensures developers recognize at least three levels of "nesting" in the WBS structure.

Expected task order:
`1
1.1
1.1.1
1.1.2
1.2
2
.
.
9
10`

WBS structures typically extend down three levels.

A good descriptive link on the WBS structure can be found here:  [https://project-management.com/work-breakdown-structure-wbs/](https://protect-de.mimecast.com/s/E7p0CEqYoEs3NWPjsNFpbP?domain=project-management.com/)
