### ISSUE TITLE
GP cloud stops at "Creating access token"

### ISSUE THREAD

**Issue by leandrovegacon** [bardsoftware/ganttproject#2355]
I did search for this issue here, but I did found nothing.

Today, when I tried to open my projects files in the cloud, the authentication page just stoped at "Creating access token", and I can't get access to my projects files.
I tried in Firefox and Brave. I clean it up cache files, but it didn't work.
I'm desperate, because I can't open any of my projects files.
I'm using Windows 10.
![2023-09-01 11_39_15-Authenticate Desktop Application -- GanttProject Cloud — Mozilla Firefox](https://github.com/bardsoftware/ganttproject/assets/143820513/0db4a489-5dfa-4472-8a01-9f11ecacb5b1)

This is the GP logs:
C:\Users\me\ganttproject.log

GanttProject 3.1.3103
Settings file:
	location: C:\Users\me\.ganttproject
	size:17643
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject
java.home: C:\Program Files (x86)\GanttProject\runtime
java.ext.dirs: null
java.io.tmpdir: C:\Users\me\AppData\Local\Temp\
java.runtime.version: 11.0.11+9-LTS
java.vendor: BellSoft
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: BellSoft
java.vm.version: 11.0.11+9-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs plugins;~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject
user.country: BR
user.dir: C:\Program Files (x86)\GanttProject
user.home: C:\Users\me
user.language: pt
user.timezone: America/Sao_Paulo

set 01, 2023 1:58:37 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't set awtAppClassName (needed on Linux to show app name in the top panel)
set 01, 2023 1:58:38 PM net.sourceforge.ganttproject.GPLogger log
INFORMAÇÕES: Deleting old auto-save files
set 01, 2023 1:58:40 PM biz.ganttproject.LoggerImpl debug
DETALHADO: Creating main frame...
set 01, 2023 1:58:40 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 1. loading look'n'feels
set 01, 2023 1:58:42 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 2. loading options
set 01, 2023 1:58:42 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 3. creating menus...
set 01, 2023 1:58:42 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 4. creating views...
set 01, 2023 1:58:42 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 5. calculating size and packing...
set 01, 2023 1:58:43 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 6. changing language ...
set 01, 2023 1:58:43 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 7. first attempt to restore bounds
set 01, 2023 1:58:43 PM biz.ganttproject.LoggerImpl debug
DETALHADO: 8. finalizing...
set 01, 2023 1:58:53 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave470386838957625562.gan
set 01, 2023 1:58:53 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave13301299728928088278.gan
set 01, 2023 1:58:53 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave6708005615909129928.gan
set 01, 2023 1:58:53 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\Documents\#Clientes\MNOP\Morelli\Morelli_Proposta.gan
set 01, 2023 1:58:53 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave9061633830020501775.gan
set 01, 2023 2:05:18 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave470386838957625562.gan
set 01, 2023 2:05:18 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave13301299728928088278.gan
set 01, 2023 2:05:18 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave6708005615909129928.gan
set 01, 2023 2:05:18 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\Documents\#Clientes\MNOP\Morelli\Morelli_Proposta.gan
set 01, 2023 2:05:18 PM biz.ganttproject.LoggerImpl error
GRAVE: Can't parse this recent document record: C:\Users\me\AppData\Local\Temp\_ganttproject_autosave9061633830020501775.gan

**Comment by dbarashev** [comment]
Can you please try using Chrome?

**Comment by leandrovegacon** [comment]
Isn't Brave “as same as” Chrome for this matters?
Sorry, I hope to not been rude.
Well, anyway, I don't know what happened, but some days after I post this, the GP get back to work again.
So I do not know what solved the issue and I can't reproduce it anymore.
This can be closed in my opinion.
---
Something that may help anyone in the same situation as mine in the future.
I managed to edit my projects offline, downloading my data in the “Settings -> Account and Data Control -> [start export]”.
---
