### ISSUE TITLE
Letters not readable in the second screen with scale 100%. Main screen has scale 125% (Windows 11)

### ISSUE THREAD

**Issue by gotocode20** [bardsoftware/ganttproject#2360]
All the letters in the section Gantt (Name, Start Date, End Date, Zoom, Zoom-out, ...) are not readable when you move the application to the second screen with scale 100%. Main screen has scale 125% (notebook)

Application should adapt to the scale of the second screen. 

![image](https://github.com/bardsoftware/ganttproject/assets/71592538/ecc23fc8-0696-4e59-91fd-6f6bbdd481fc)

**Comment by dbarashev** [comment]
Can you please try the solution from this topic on the support portal?

https://help.ganttproject.biz/t/task-font-illegibile-aliasing-in-3-2-3240/4742/6

**Comment by dbarashev** [comment]
This is [reportedly fixed in Java 17 Runtime version 17.0.12](https://help.ganttproject.biz/t/low-resolution-on-27-inch-external-monitor/8711/5)  which is bundled with [GanttProject 3.3.3312](https://github.com/bardsoftware/ganttproject/releases/tag/ganttproject-3.3.3312).
