### ISSUE TITLE
x86_64 macOS release for version 3.3.3300 is not signed, arm64 version is.

### ISSUE THREAD

**Issue by ryangball** [bardsoftware/ganttproject#2400]
The x86_64 release for macOS is not signed.

https://github.com/bardsoftware/ganttproject/releases/download/ganttproject-3.3.3300/ganttproject-3.3.3300-intel.dmg

**Comment by mihelm** [comment]
Yes, I just ran into the same issue.

**Comment by dbarashev** [comment]
Thanks for reporting, I will take a look.

**Comment by dbarashev** [comment]
Can you please try this one?
https://storage.googleapis.com/dl.ganttproject.biz/ganttproject-3.3.3300/ganttproject-3.3.3300-intel.dmg

**Comment by suschizu** [comment]
hello - yes I can confirm that this intel version is signed properly - could you please replace it on  github :)

```
Signature size=8987
Authority=Developer ID Application: BarD Software s.r.o (QDCH4KTVP7)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
```
<img width="563" alt="Screenshot 2024-01-23 at 17 57 32" src="https://github.com/bardsoftware/ganttproject/assets/16004333/af4b7f57-75bb-44c0-abf4-797ce56d6ea2">
