### ISSUE TITLE
Earliest begin not working in 3.3.3300 version

### ISSUE THREAD

**Issue by adiazubierna** [bardsoftware/ganttproject#2402]
Hi,

I updated to the 3.3.3300 version and now the option earliest begin is not working for the tasks.

![image](https://github.com/bardsoftware/ganttproject/assets/10388491/a6ff6a0c-c4f2-4d1a-ae22-45f3452b08ed)

When I select that option and select a different date and then click on Ok, that option is not saved and if I open again the propierties of the tasks the option is unselected.

Everything was working fine with the previous version 3.2. I reproduced it in different computers and configurations.

Thank you,

**Comment by dbarashev** [comment]
Thanks for reporting!
