### ISSUE TITLE
Version 3309 or 3390 in ganttproject-builder/VERSION ? 

### ISSUE THREAD

**Issue by StephaneIFO** [bardsoftware/ganttproject#2478]
Hi, 

I think the "3390" is an error in https://github.com/bardsoftware/ganttproject/blob/master/ganttproject-builder/VERSION

Stéphane

**Comment by dbarashev** [comment]
It is as designed. 
The `master` branch is the unstable one, the version is chosen to be closer to 3400. If you need version 3309, check out `BRANCH_3.3`
