### ISSUE TITLE
Ganttproject 3.3 requires JDK 21, but the startup script does not allow JDK 21

### ISSUE THREAD

**Issue by nakic** [bardsoftware/ganttproject#2491]
Just installed v. 3.3 on Ubuntu 20.04 by manually downloading the .deb. The installation had a dependency on JDK 21, so that got installed as well.

Observed behaviour:
when running "$ ganttproject", I would get:
Searching for Java in /usr/share/ganttproject/runtime/bin/java
...missing or not executable
Searching for Java in /usr/lib/jvm/java-11-openjdk-amd64/bin/java
...found openjdk version "11.0.23" 2024-04-16
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/bin/java
...found openjdk version "21.0.3" 2024-04-16
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/lib/jvm/default-java/bin/java
...found openjdk version "11.0.23" 2024-04-16
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java
...found openjdk version "11.0.23" 2024-04-16
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/lib/jvm/java-11-openjdk-amd64/bin/java
...found openjdk version "11.0.23" 2024-04-16
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/lib/jvm/java-1.21.0-openjdk-amd64/bin/java
...found openjdk version "21.0.3" 2024-04-16
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java
...found openjdk version "1.8.0_412"
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/lib/jvm/java-21-openjdk-amd64/bin/java
...found openjdk version "21.0.3" 2024-04-16
...this seems to be an old Java Runtime (or maybe just too new)
Searching for Java in /usr/lib/jvm/java-8-openjdk-amd64/bin/java
...found openjdk version "1.8.0_412"
...this seems to be an old Java Runtime (or maybe just too new)
JavaVM executable not found.
  You may want to set the path to the root of your Java Runtime installation
  in JAVA_HOME environment variable or pass it to ganttproject in --java-home argumen

Expected behaviour:
ganttproject starts successfully when invoked.

Repeatability: 4/4 times

Workarounds:

I opened the ganttproject script and added the last line around line number 147:

  [[ "$VERSION" =~ 17\.? ]] && return 0;
  [[ "$VERSION" =~ 18\.? ]] && return 0;
  [[ "$VERSION" =~ 19\.? ]] && return 0;
  [[ "$VERSION" =~ 21\.? ]] && return 0;

Once I did that, it could start properly. I think this is a bug in the startup script and this workaround might be an appropriate fix, although it would be better to find a fix that doesn't break with the first subsequent version of the JDK.

**Comment by dbarashev** [comment]
GanttProject 3.3 requires Java 17. It is explicitly written in the [release notes](https://github.com/bardsoftware/ganttproject/releases/tag/ganttproject-3.3.3309)

**Comment by nakic** [comment]
@dbarashev , thank you for the quick reply. I don't know why it required installation of JDK 21 on my machine, but it did.

In any case, if JDK 21 is allowed and is the only one available, I think it should not fail to run (as it does), so I would say a fix to the launch script is still warranted.
