### ISSUE TITLE
Interfacing projects via an API

### ISSUE THREAD

**Issue by michael1maass** [bardsoftware/ganttproject#2504]
Hi, 

is there a way to interface projects via any type of API other than csv / excel? The intent is, to connect task and Ressourceplanning from GanttProject to a kanban board style Service (kanboard) for agile implementation of the plan and return the status of workpackages. 

I like the Software!!

Michael

**Comment by dbarashev** [comment]
There is no API that was officially supported. You may try using MPXJ library though, they can read GanttProject files.

**Comment by michael1maass** [comment]
Thank you for your Quick reply. Will check and reportMichael MaaßAm 31.07.2024 um 16:26 schrieb Dmitry Barashev ***@***.***>:﻿
There is no API that was officially supported. You may try using MPXJ library though, they can read GanttProject files.
