### ISSUE TITLE
Additional dependency needed for Ubuntu in .deb package for openjdk

### ISSUE THREAD

**Issue by raymck** [bardsoftware/ganttproject#2524]
The free download linux .deb file does not install with the common openjdk jre. The Ubuntu package name is openjdk-17-jre for version 17.

It's a trivial change to the package control file, and I think this PR #2525 addresses that change in the build process.

**Comment by dbarashev** [comment]
GanttProject 3.3 build 3312 was re-packaged with this fix applied.
