### ISSUE TITLE
ganttproject does not launch

### ISSUE THREAD

**Issue by otcalli** [bardsoftware/ganttproject#2528]
From one day to the next, while everything was working, the software stops launching. I'm the 2nd position in the company this has happened to (2 months after another person). The resource is well launched, here's what I have in the task managers.

![image](https://github.com/user-attachments/assets/1f07bab7-20d4-4f1b-8757-c1598c2af20f)

**Comment by dbarashev** [comment]
Please share the log file, the project file if any, and the details on how you launch the application.

**Comment by otcalli** [comment]
Hi, Thanks for your answer, i open the .exe with WinDbg : 

************* Preparing the environment for Debugger Extensions Gallery repositories **************
   ExtensionRepository : Implicit
   UseExperimentalFeatureForNugetShare : true
   AllowNugetExeUpdate : true
   NonInteractiveNuget : true
   AllowNugetMSCredentialProviderInstall : true
   AllowParallelInitializationOfLocalRepositories : true
   EnableRedirectToChakraJsProvider : false

   -- Configuring repositories
      ----> Repository : LocalInstalled, Enabled: true
      ----> Repository : UserExtensions, Enabled: true

>>>>>>>>>>>>> Preparing the environment for Debugger Extensions Gallery repositories completed, duration 0.000 seconds

************* Waiting for Debugger Extensions Gallery to Initialize **************

>>>>>>>>>>>>> Waiting for Debugger Extensions Gallery to Initialize completed, duration 0.015 seconds
   ----> Repository : UserExtensions, Enabled: true, Packages count: 0
   ----> Repository : LocalInstalled, Enabled: true, Packages count: 42

Microsoft (R) Windows Debugger Version 10.0.27668.1000 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: C:\Program Files\GanttProject-3.3\GanttProject-3.3.exe

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff6`34d90000 00007ff6`34e06000   jpackageapplauncherw.exe
ModLoad: 00007ff9`b70f0000 00007ff9`b7307000   ntdll.dll
ModLoad: 00007ff9`b5a30000 00007ff9`b5af4000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ff9`b4a70000 00007ff9`b4e1d000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ff9`b4e20000 00007ff9`b4fce000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ff9`b4660000 00007ff9`b4686000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ff9`b59f0000 00007ff9`b5a19000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ff9`b4540000 00007ff9`b4659000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ff9`b4740000 00007ff9`b47da000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ff9`b4950000 00007ff9`b4a61000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ff9`b6840000 00007ff9`b70a8000   C:\WINDOWS\System32\SHELL32.dll
(2554.4cfc): Break instruction exception - code 80000003 (first chance)
ntdll!LdrpDoDebuggerBreak+0x30:
00007ff9`b71cbed4 cc              int     3
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\atlmfc.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\ObjectiveC.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\concurrency.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\cpp_rest.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\stl.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\Windows.Data.Json.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\Windows.Devices.Geolocation.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\Windows.Devices.Sensors.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\Windows.Media.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\windows.natvis'
NatVis script unloaded from 'C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2407.24003.0_x64__8wekyb3d8bbwe\amd64\Visualizers\winrt.natvis'

**Comment by dbarashev** [comment]
I am not interested in this Windows executable information, thanks. 
I need a log file that GanttProject produces when you launch it. You can find the `ganttproject.log` file in your home directory.

**Comment by dbarashev** [comment]
No response, closing.
