### ISSUE TITLE
pb earliest start date

### ISSUE THREAD

**Issue by csanouk** [bardsoftware/ganttproject#2581]
Hello,
I think the function "earliest start date" in the task doesn't work with the last version 3.3.3312
Regards

**Comment by dbarashev** [comment]
What exactly is wrong?

**Comment by csanouk** [comment]
On version 3.2 the function work, on version 3.3 the function is disable

![image](https://github.com/user-attachments/assets/9597076c-8b36-4ddc-a08b-fc0b2afe36dc)

**Comment by dbarashev** [comment]
The control on the screenshot looks like enabled. Please share a reproducible scenario and attach a sample to file that helps with reproducing the issue.

**Comment by csanouk** [comment]
It's the screenshot with version 3.2. Withe tha last version,  it'a always disable.

**Comment by dbarashev** [comment]
It is enabled in my tests. Please share a reproducible scenario and attach a sample to file that helps with reproducing the issue.
