### ISSUE TITLE
Avira detect Malware

### ISSUE THREAD

**Issue by apiconnectplus** [bardsoftware/ganttproject#2635]
Avira detect Drop.Win64.UserProfileSelfRun.232

![imagen](https://github.com/user-attachments/assets/a87767a6-5258-4523-8e31-5ca1f7b3e660)

**Comment by dbarashev** [comment]
Everything about the false positives is written in the release notes:
https://github.com/bardsoftware/ganttproject/releases/tag/ganttproject-3.3.3312
