### ISSUE TITLE
Option to control application font size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#615]
```
One high resolution screens default font size might be too small, and one may 
want to increase font size across the whole application (menus, dialogs, etc.)
```

Original issue reported on code.google.com by `dbarashev` on 16 Oct 2012 at 4:17

**Comment by foice** [comment]
is this still up to date? 
I have changed the fonts from the preferences but the names of the tasks in the left panale (not in the chart) do not change size.

I have tried
<option id="ui.ui.appFontSize" value="12"/>
 but it has not effect. Any idea?

**Comment by dbarashev** [comment]
You can change the ont size in Application UI settings, field "Application font". It works fine at least wth Plastic appearance.

**Comment by foice** [comment]
yes, with plastic appearance this works. thanks a lot.
