### ISSUE TITLE
Task move function doesn't work on Mac OSX

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#706]
```
Moving tasks with mouse doesn't work on Mac OSX: holding Ctrl with left mouse 
button makes context menu showing up. holding Cmd does nothing

Initially reported here: 
http://code.google.com/p/ganttproject/issues/detail?id=270#c6
```

Original issue reported on code.google.com by `dbarashev` on 2 Jan 2013 at 4:24

**Comment by askoobe** [comment]
It is still an issue with v2.8.7 on OSX High Sierra with Java Runtime 1.8.0_152-b16. Holding shift while moving the mouse does not work.  A workaround is editing the mouse.properties as mentioned above.
