### ISSUE TITLE
Duration on CSV import is calculated without weekends

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#897]
```
Is there a way to import a CSV and have the duration interpreted to include 
weekend days?
```

Original issue reported on code.google.com by `ksimmons` on 27 Feb 2014 at 8:30

**Comment by znittzel** [comment]
Something more on this? Is there a way to include weekends so that "duration: 7" is a week, not a week and 2 days.

**Comment by dbarashev** [comment]
Sorry? This issue is about a particular bug in CSV export. It was fixed and closed two years ago. If your question is about making weekend days working then go to Project->Properties->Calendar. Uncheck all days and get duration=7 is a week.

**Comment by znittzel** [comment]
Oh, ok. But yes! That was exactly what my question was. Thank you!
