### ISSUE TITLE
How to add the holiday calendar of a country

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#997]
```
I've already read the thread about the chinese calendar, what I would like to 
do is to add the holiday calendar of Panama (in this particular case), and then 
share with you for next release (...)

I created the .calendar file, edited it and ... nothing happens. I closed the 
app and then open it, but ... nothing happens, the "Panama" (new country) 
option does not appears on the Calendar Settings page under holidays calendar 
option.

What am I missing?
```

Original issue reported on code.google.com by `ecede...@gmail.com` on 10 Oct 2014 at 8:11

Attachments:
- [Captura de pantalla 2014-10-10 a la(s) 15.00.30.png](https://storage.googleapis.com/google-code-attachments/ganttproject/issue-997/comment-0/Captura de pantalla 2014-10-10 a la%28s%29 15.00.30.png)

**Comment by hslxxxx** [comment]
<a href="https://www.cosplayonline.es/">Película Disfraces</a>
<a href="https://www.cosplayonlineshop.com/category/marvel-costumes/">Marvel Costumes</a>
<a href="https://www.agcosplay.it/categoria-prodotto/costumi-anime/">COSTUMI ANIME</a>
<a href="https://www.rolepartycosplay.de/">Halloween dresses</a>
<a href="https://www.cosplayinside.com/">party suit</a>
<a href="https://www.agcosplay.it/categoria-prodotto/anime-costumes/a-certain-magical-index/">axis powers hetalia</a>
<a href="https://www.cosplayonline.es/categoria/anime-costumes/">goblin slayer gotoubun</a>
<a href="https://www.rolepartycosplay.de/produkt-kategorie/movie-costumes/">cm rhapsody lolita</a>
<a href="https://www.cosplayinside.com/category/game-costumes/">wear parties daily</a>
<a href="https://www.cosplayonlineshop.com/category/cosplay-wigs/">COSPLAY WIGS</a>
<a href="https://www.cosplayonline.es/producto/demon-slayer-kanroji-mitsuri-disfraces-de-cosplay-de-uniforme-femenino/">uccisore di demoni</a>
